realtek: cleanup LAG logging
openwrt/openwrt pull request #10114
Opened 2022-06-24 06:57 UTC by plappermaul

Setting up DSA bond silently fails if mode is not 802.3ad. Add log message
to fix it. As we are already here hamonize all logging messages in the
add/delete functions.

2022-06-25 13:58 UTC, svanheule requested changes

2022-06-25 13:58 UTC, svanheule commented on target/linux/realtek/files-5.10/drivers/net/dsa/rtl83xx/common.c
> +	pr_info("%s: Adding port %d to LA group %d\n", __func__, port, group);
There's a pr_debug at the end of the function. These drivers are verbose enough as they are, I don't think this line really adds value, being so verbose all the time.

2022-06-25 13:58 UTC, svanheule commented on target/linux/realtek/files-5.10/drivers/net/dsa/rtl83xx/common.c
> + */
This is a short line, doesn't need to be changed to a multi-line comment.

2022-06-25 13:58 UTC, svanheule commented on target/linux/realtek/files-5.10/drivers/net/dsa/rtl83xx/common.c
> + */
Same as above. Not really a useful change IMHO.

2022-06-25 14:00 UTC, svanheule commented
Thanks for improving the driver's feedback a bit.

checkpatch.pl also has some remarks about this patch:

```WARNING: line length of 108 exceeds 100 columns
#66: FILE: target/linux/realtek/files-5.10/drivers/net/dsa/rtl83xx/common.c:488:
+	pr_debug("%s: LA group %d members now %016llx.\n", __func__, group, priv->lags_port_members[group]);

WARNING: line length of 108 exceeds 100 columns
#105: FILE: target/linux/realtek/files-5.10/drivers/net/dsa/rtl83xx/common.c:520:
+	pr_debug("%s: LA group %d members now %016llx.\n", __func__, group, priv->lags_port_members[group]);

ERROR: Missing Signed-off-by: line(s)

total: 1 errors, 2 warnings, 89 lines checked
```

2022-06-26 07:52 UTC, svanheule reviewed
Any reason you went with "LA group" instead of just "LAG"? The former does no appear to be used elsewhere in the kernel.

2022-06-26 07:55 UTC, plappermaul commented
> Any reason you went with "LA group" instead of just "LAG"? The former does no appear to be used elsewhere in the kernel.

This comes from the old pr_info() at the beginning of the functions.

2022-06-26 08:30 UTC, plappermaul commented
changed everything to LAG

2022-06-26 09:30 UTC, svanheule commented
Thanks! Merged into master with commit 78b7be9f6c6961b3c71f213c9e4bde18af5c8ee6.

2022-06-26 09:30 UTC, closed without merging