(tools/)elfutils: fix compilation with gcc-12.2.0
openwrt/openwrt pull request #10521
Opened 2022-08-26 17:18 UTC by PolynomialDivision

Import a patch to disable werror.

2022-08-27 12:27 UTC, BKPepe requested changes
Just no. You are just trying to hide warnings or errors with tape, and that's not a good approach. Also, you introduced patches, which we never get rid of as they were refused by upstream or discussed with upstream and did not get through. Why are you trying to have them here? Please avoid doing this.

2022-08-27 12:27 UTC, BKPepe commented on package/libs/elfutils/patches/102-configure-add-a-disable-werror-option.patch
> +https://sourceware.org/pipermail/elfutils-devel/2022q3/005342.html
Just no. They said:
```
This warning is definitely wrong, looks like a regression in gcc, please
report this to compiler people, otherwise they will never know they
introduced a bug that needs fixing.

```

2022-08-27 12:27 UTC, BKPepe commented on package/libs/elfutils/patches/102-configure-add-a-disable-werror-option.patch
> +https://sourceware.org/legacy-ml/elfutils-devel/imported/msg00994.html
```
Please do report any issues you find with -Werror. **We explicitly enable
specific -W flags to catch issues.** With a modern GNU toolchain the codebase
really should be warning/error free with the default flags. If not, that is
certainly a bug.
```

2022-08-27 12:51 UTC, PolynomialDivision commented on package/libs/elfutils/patches/102-configure-add-a-disable-werror-option.patch
> +https://sourceware.org/pipermail/elfutils-devel/2022q3/005342.html
That is what I wrote?

2022-08-27 12:54 UTC, PolynomialDivision commented on package/libs/elfutils/patches/102-configure-add-a-disable-werror-option.patch
> +https://sourceware.org/legacy-ml/elfutils-devel/imported/msg00994.html
I already reported it here:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104069

Interesting is this comment:
```
This warning, like all others, is meant to help find common bugs in ordinary code.  It shouldn't be expected to reflect implementation-defined behavior or to be free of false positives.  Tricky code that tries to work around implementation specifics or divergences might be better off suppressing it using a #pragma.  Now that pragma suppression works reliably with inlining it should be straightforward to do.  Since -Wuse-after-free is a multi-level warning and this instance triggers only at level 2 ("may be used"), for code that can't be changed I suggest reducing the level to 1 on the command line.
```

2022-08-27 13:00 UTC, PolynomialDivision commented
This is just a draft for discussion. I am also not happy with this solution. However, it seems common to do it in openwrt like all the other tools that have `--disable-werror` as configure flag. Than we should also remove the flags from the other tools. This issue blocks the gcc-12.2.0 version update and I thought we could use it as workaround until it is fixed upstream. I am happy if someone shows a better appraoch.

2022-08-27 18:30 UTC, hauke commented
Does the elfutils from tools compile on Linux distributions with gcc 12?
We can not control the compiler used to compile the tools.

2022-08-27 18:38 UTC, PolynomialDivision commented
> Does the elfutils from tools compile on Linux distributions with gcc 12?

On my system with gcc version 12.2.0 it compiles fine. Just wanted to add the patch to both elfutils. However, I can delete the patch for tools/elfutils again. But it seems that adding --disable-werror seems to receive a nack as workaround.

2022-12-24 11:20 UTC, Ansuel commented
@hauke i notice this? afaik we already handle this for the default gcc 12 pr?

2023-01-21 11:15 UTC, Ansuel commented
Closing this as suppressed by 2748c45d468b6208f70972adc7ae2e532b2c3015

2023-01-21 11:15 UTC, closed without merging