uboot-bcm4908: fix build error on GCC >= 10
openwrt/openwrt pull request #11449
Opened 2022-12-07 17:25 UTC by jclehner

GCC versions 10 and up default to `-fno-common`, causing the build to fail with the following error:

```
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
```

This patch mirrors the one in uboot-zync (8b870418).

Signed-off-by: Joseph C. Lehner <joseph.c.lehner@gmail.com>

2022-12-07 18:30 UTC, Ansuel commented
@jclehner i mean can't you just take the same patch?

2022-12-08 09:43 UTC, BKPepe requested changes
I think that OpenWrt no longer need to have our separate repository for [bcm63xx U-boot](https://git.openwrt.org/?p=project/bcm63xx/u-boot.git;a=summary) anymore because I see:

https://github.com/openwrt/openwrt/blob/69f0c29b8b3339ef93c04f6c7f92481e8e223e2f/package/boot/uboot-bcm4908/Makefile#L23

https://github.com/openwrt/openwrt/blob/69f0c29b8b3339ef93c04f6c7f92481e8e223e2f/package/boot/uboot-bcm4908/Makefile#L29

It is used for ``bcm4908`` and ``bcm4912``targets, but recently there was added support for it in mainline U-boot:

- https://source.denx.de/u-boot/u-boot/-/commit/e5703df2626885f30f0bc61d82022923200e01a7

- https://source.denx.de/u-boot/u-boot/-/commit/dc6117dcb35999a7f60ae443757bd4857254abc2

Since I don't have any devices with this SoC, let's mention @rmilecki who added this package https://github.com/openwrt/openwrt/commit/0d45e1ea96ef29649f080c54f99fb1c80482421b

2022-12-08 09:43 UTC, BKPepe commented on package/boot/uboot-bcm4908/patches/101-fix-gcc-10-build-error.patch
> +-YYLTYPE yylloc;
This is missing usual formal stuff - who is the author of the commit, why it is necessary (some description, etc.)

2022-12-08 11:11 UTC, rmilecki commented
57a8ea6d749e ("uboot-bcm4908: update to the latest generic master")

2022-12-08 11:11 UTC, closed without merging