ipq40xx: Fix Linksys upgrade, restore config step
openwrt/openwrt pull request #11692
Opened 2023-01-04 17:43 UTC by jeffsf

It appears that the refactor of the upgrade process for NAND devices resulted in the nand_do_upgrade_success step not being called for devices using the linksys.sh script. As a result, configuration was not preserved over sysupgrade steps.

This was restored for some devices in commit 84ff6c9. This commit restores preservation of config for ipq40xx devices using the linksys.sh script. Other devices and targets have not been examined.

Closes: #11677
Fixes: e25e6d8e54 ("base-files: fix and clean up nand sysupgrade code") Tested-on: EA8300

Signed-off-by: Jeff Kletsky <git-commits@allycomm.com>

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

2023-01-04 17:53 UTC, Ansuel commented
no new line between sob and fixes tag.

Also I think we should follow how it was done in the related commit. 

Since success will reboot the system 

I would use something like 

```
tar_upgrade && nand_success
nand_fail
```

2023-01-04 17:53 UTC, Ansuel commented
@robimarko what do you think ?

2023-01-04 19:01 UTC, jeffsf commented
While I appreciate the brevity of assuming that the call to `nand_do_upgrade_success` reboots the system, this bug apparently arose when a refactor wasn't aware of assumptions around how consumers of generic functions behaved.

Functionally, they achieve the same goal at run time. I can't get worked out about it one way or another. I was just trying to reduce the chances of this happening again. Let me know consensus and I'll update content and the commit message in one pass.

2023-01-04 19:26 UTC, robimarko commented
I am really not any kind of an expert when it comes to sysupgrade, ideally somebody familiar should take a look

2023-02-03 20:43 UTC, diizzyy commented
While either might not the be perfect solution can we please commit at least one soltion for now instead of having it broken?
I'd say for consistency go with what @Ansuel suggested.

2023-02-04 05:00 UTC, ascendbeing commented
I've never done any work on these pulls before, but the function is called "nand_do_upgrade_failed" not "nand_do_upgrade_failure" so if you're committing it please send in another commit to make sure you are using an actual function.
I'm going through the same thing with a Kirkwood target ea3500 right now. Sometime in the last year or 2, master sysupgrade doesn't preserve config on Kirkwood master->master. so I'm going to be trying this pull in the relevant section of the linksys.sh with my fix, for Kirkwood target, and I'll let you know if it bricked or kept my settings. without this pull the expected behavior is upgrade works and preserve config does nothing.

2023-02-06 08:34 UTC, ascendbeing requested changes
Concise and fixed (failure->failed) two liner adapted from your commit and Ansuel's pseudo code:

nand_upgrade_tar "$1" && nand_do_upgrade_success
nand_do_upgrade_failed


Tested on Kirkwood (ea3500). Same principle, replace line `nand_upgrade_tar "$1"` with my two liner.


Please swap in my two liner both for this target and for Kirkwood and rename the pull to reflect this fix is also for Kirkwood (at least ea3500 and ea4500 are affected on Kirkwood). Thanks.

2023-02-17 05:18 UTC, ascendbeing commented
I am new to GitHub so my "review" was not very useful m consider it 1. a request to expand this pull to include Kirkwood. 2. a 2 liner which addresses a) failure->failed (there is no failure, only failed) b) incorporates @Ansuel suggested improvements (if/else becomes && and another line)

e8625c89efbbbe12a5934c10fc3478fd2f70fb21 just adjusted these files but did not incorporate this pull. I don't believe that any changes further than my first suggestion are needed but I will admit I haven't checked after this recent commit.

2023-03-23 16:08 UTC, Ansuel commented
@jeffsf I remember this fix... I would drop the if else and use the pattern used also in the linked fix...
Consider that we are in ramfs and the system must be rebooted if something fail in the process

This is why the pattern
&& _succes
_fail 

works since _success should reboot and _fail should never be reached. It's really a nitpick but it's for consistency. Ok for you ?

2023-03-26 14:43 UTC, chunkeey commented
Merged. Thanks!

2023-03-26 14:43 UTC, closed without merging

2023-03-28 00:09 UTC, ascendbeing commented
@chunkeey can you please also do this for Kirkwood? Kirkwood was also affected. I put the code above it's replacing 1 line with 2 lines which should be the same line you changed out in the ipq40xx line in Linksys.sh.

2023-03-31 08:37 UTC, ascendbeing commented
@chunkeey should I create a separate issue? This issue also applies to Kirkwood, in the same Linksys.sh file (you edit the same line, and put your fix here, or mine, whichever is better, I've tested mine against the latest version of the file)? You fixed it for ipq but not for Kirkwood. With my 1 line -> 2 lines code I posted above, Kirkwood gets fixed, but nobody has merged it into master, as of time of writing.

2023-05-20 03:21 UTC, jeffsf commented
Thanks all - Appreciate the time in getting this merged