fix-add_ap3935i
openwrt/openwrt pull request #11994
Opened 2023-02-12 10:50 UTC by nbtby22

Hi dmascord

We need your support to update your Extreme AP3935i implementation.
IPQ8068 is already supported by OpenWRT for https://openwrt.org/toh/meraki/mr52 and https://openwrt.org/toh/hwdata/edge-core/edge-core_ecw5410.

In my opinion, we no longer need the board images (from an external source).
However, the dts file must be updated (for example it is now called &nand instead of &nand_controller).

I have a suggestion for a change here.
[ap3935i_files.zip](https://github.com/openwrt/openwrt/files/10715864/ap3935i_files.zip)

Unfortunately, I am still an absolute newbie in Openwrt, so in my example not all things have been brought up to date.

Could you take a look and update this please?

2023-02-12 14:33 UTC, hauke commented
Please clean up your pull request.
* remove the merge commits, rebase on top of current master
* Remove patches for old unsupported kernel only keep 5.,15 and maybe 5.10 
* Remove the custom feed
* Follow this guideline: https://openwrt.org/submitting-patches

2023-02-12 14:36 UTC, hauke requested changes
This needs bigger cleanup:
* Remove the merge commits
* Do not add a custom feed
* Do not add patches for unsupported kernel versions, only 5.15 and maybe 5.10 is needed
* Follow https://openwrt.org/submitting-patches

2023-02-13 14:12 UTC, nbtby22 commented
Hi hauke
thanks for your feedback
I thought this pull request would go into the dmascord project. I guess I was wrong.

I made a few changes to the existing files. However, that is only as far as my technical understanding goes.
But I'm not a developer. I implemented my changes for kernel 5.15 (I believe).
I was able to compile the image without errors, but haven't been able to test it yet.

Forgive me if I can't keep up here and take a long time to do something.
I have to get used to Github and find my way around as someone who has no idea about programming.

I give my best. Sorry the review request was an oversight on my part.

By "Do not add a custom feed" do you mean my ZIP file?

2023-02-15 15:00 UTC, nbtby22 commented
Thank you very much for the information.
I just need a few days for it.

2023-07-01 21:34 UTC, apdev-2023 commented
Since this pull-request has been abandoned for 2yrs and gone stale, I have continued the original author's work and made a new pull request:

https://github.com/openwrt/openwrt/pull/13030

2025-09-07 00:30 UTC, Djfe commented
the device has been merged already
could you close this stake pr please? :)

2025-09-07 09:31 UTC, hauke commented
Support was added in https://github.com/openwrt/openwrt/pull/13030

2025-09-07 09:31 UTC, closed without merging