TP-Link Archer MR200-v4 support added
openwrt/openwrt pull request #12423
Opened 2023-04-18 20:10 UTC by MiKuBB

2023-04-19 05:04 UTC, obsy requested changes

2023-04-19 05:04 UTC, obsy commented on target/linux/ramips/mt76x8/base-files/etc/board.d/01_leds
> +;;
no indentation

2023-04-19 05:04 UTC, obsy commented on target/linux/ramips/image/mt76x8.mk
> +  DEVICE_TITLE := TP-Link Archer MR200 v4
Squash this into one commit

2023-04-19 05:29 UTC, musashino205 commented on target/linux/ramips/mt76x8/base-files/etc/board.d/02_network
> +                        "1:lan" "2:lan" "3:lan" "4:wan" "6t@eth0"
This should be moved to ```ramips_setup_interfaces()```

2023-04-19 05:55 UTC, MiKuBB reviewed
thx

2023-04-20 20:22 UTC, andyboeh commented
You are missing a proper commit message and all commits should be squashed into one - amongst others. Please see here for the guidelines: https://openwrt.org/submitting-patches

2023-04-21 05:03 UTC, MiKuBB commented
> You are missing a proper commit message and all commits should be squashed into one - amongst others. Please see here for the guidelines: https://openwrt.org/submitting-patches

2023-04-23 07:00 UTC, closed without merging

2023-04-23 07:01 UTC, MiKuBB commented
iam lost