ramips: mt7621: add Cudy X6 v2
openwrt/openwrt pull request #12425
Opened 2023-04-20 03:39 UTC by Djfe

This PR adds support for the Cudy X6 v2 and at the same time improves support for v1:
- Corrects the WiFi MAC addresses to match oem/stock behavior.
- Also makes use of the red led: default for failsafe and upgrade (instead of the blue led)

This adds a common .dtsi file for both devices. The .dts files themselves only differ due to the smaller flash size of v2 which causes the partitions to be at different offsets.

The second commit adds oem device names to mt7621.mk to remove the force upgrade warning from Cudy's OpenWrt fork on
Cudy M1800, Cudy WR1300 and Cudy WR2100.
This change wasn't tested on devices, but is unlikely to break anything. I could test the installation process on all affected devices except the WR2100 if required.
______________

About the WiFi Mac correction:
v1 and v2 assign the MAC for 5GHz WiFi slightly differently.
Both set the LA bit, but v1 then adds 0x100000 while v2 adds 0x200000. (at least this is the case for the two devices I own)
OpenWrt now adds 0x100000 in all cases, which is fine I think (the LA bit is set after all).
The previously used mac addresses from the factory partition were completely wrong and belong to Ralink instead of Cudy.

2023-04-20 09:13 UTC, blocktrron commented
Please add a short overview which states the full MAC-address in OpenWrt and stock-firmware respectively.

2023-04-20 14:37 UTC, Djfe commented
Sure, I updated the commit message and here you go for the full comparison:

stock firmware X6 v1:
```
use   address             source
LAN   b4:4b:d6:2d:c8:4a   label
WAN   b4:4b:d6:2d:c8:4b   label + 1
2g    b4:4b:d6:2d:c8:4a   label
5g    b6:4b:d6:3d:c8:4a   label + LA-Bit set + 4th oktet increased
```
openwrt 5GHz mac:
```
5g    b6:4b:d6:3d:c8:4a
```
______________
stock firmware X6 v2:
```
use   address             source
LAN   f4:a4:54:86:75:a2   label
WAN   f4:a4:54:86:75:a3   label + 1
2g    f4:a4:54:86:75:a2   label
5g    f6:a4:54:b6:75:a2   label + LA-Bit set + 4th oktet increased
```
openwrt 5GHz mac:
```
5g    f6:a4:54:96:75:a2
```

2023-04-20 14:50 UTC, blocktrron requested changes

2023-04-20 14:50 UTC, blocktrron commented on target/linux/ramips/dts/mt7621_cudy_x6-v1.dts
> +		label-mac-device = &gmac0;
Can be put in dtsi

2023-04-20 14:50 UTC, blocktrron commented on target/linux/ramips/dts/mt7621_cudy_x6.dtsi
> +		led-failsafe = &led_internet_red;
Put this change into separate commit, presumably befoe adding v2

2023-04-20 14:50 UTC, blocktrron commented on target/linux/ramips/mt7621/base-files/etc/hotplug.d/ieee80211/10_fix_wifi_mac
> +		macaddr_setbit_la "$(macaddr_add $hw_mac_addr 0x100000)" > /sys${DEVPATH}/macaddress
Fix the MAC address for v1 before introducing v2.

2023-04-24 01:09 UTC, blocktrron commented
Applied the fixes for rev A to master.

2023-05-02 20:28 UTC, blocktrron commented
Merged, thanks!

2023-05-02 20:28 UTC, closed without merging