kirkwood: add support for Iomega Storcenter ix4-200d
openwrt/openwrt pull request #12543
Opened 2023-05-05 15:53 UTC by sanderpqr

Iomega Storcenter ix4-200d is a four-bay SATA NAS powered by a Marvell
 Kirkwood SoC clocked at 1.2GHz. It has 512MB of RAM and 32MB of
 flash memory, 3x USB 2.0 and 2x 1Gbit/s NIC

Specification:
- SoC: Marvell Kirkwood 88F6281
- CPU/Speed: 1200Mhz
- Flash size: 32 MiB
- RAM: 512MB
- LAN: 2x 1Gbit/s
- 3x USB 2.0

Notes:
- The blue drive LED is triggered by HDD activity, it can not be controlled via GPIO.
- The LCD screen requires proprietary code and does not function at this time.
- Due to a kernel-related issue with the Marvell 88SE6121 SATA controller, currently only trays numbered 3 and 4 work, 1 and 2 do not. [1]

Serial pinout:

    CN4
    --------------
    | 10 8 6 4 2 |
    |  9 7 5 3 1 |
    -------------- PIN 1 Mark (fat line)

     1 = RXD
     4 = TXD
     6 = GND
     9 = 3.3V (not necessary to connect)

Installation instructions:
1. download initramfs-uImage and copy into tftp server
2. connect the tftp server to network port 1
3. access uboot environment with serial cable and run 
    ```
    setenv mainlineLinux yes
    setenv arcNumber 1682
    setenv console 'console=ttyS0,115200n8'
    setenv mtdparts 'mtdparts=orion_nand:0x100000@0x000000(u-boot)ro,0x20000@0xA0000(u-boot environment)ro,0x300000@0x100000(kernel),0x1C00000@0x400000(ubi)'
    setenv bootargs_root 'root='
    setenv bootcmd 'setenv bootargs ${console} ${mtdparts} ${bootargs_root}; nand read.e 0x800000 0x100000 0x300000; bootm 0x00800000'
    saveenv
    setenv serverip 192.168.1.1
    setenv ipaddr 192.168.1.2
    tftpboot 0x00800000 [initramfs-uImage filename]
    bootm 0x00800000
    ```
4. connect to LAN on network port 2, log into openwrt and sysupgrade to install into flash

[1] https://bugzilla.kernel.org/show_bug.cgi?id=216094

2023-05-05 16:48 UTC, obsy requested changes

2023-05-05 16:48 UTC, obsy commented on target/linux/kirkwood/base-files/etc/board.d/02_network
>  	iptime,nas1|\
This broke other devices like sheevaplug, iconnect or ix2-200.

2023-05-05 16:59 UTC, obsy commented on target/linux/kirkwood/base-files/etc/board.d/02_network
>  	iptime,nas1|\
Oryginal:
```
	cloudengines,pogoe02|\
	cloudengines,pogoplugv4|\
	ctera,c200-v1|\
	globalscale,sheevaplug|\
	iom,iconnect-1.1|\
	iom,ix2-200|\
	iptime,nas1|\
	netgear,readynas-duo-v2|\
	raidsonic,ib-nas62x0|\
	seagate,blackarmor-nas220|\
	seagate,dockstar|\
	seagate,goflexhome|\
	seagate,goflexnet|\
	zyxel,nsa310b|\
	zyxel,nsa310s|\
	zyxel,nsa325)
		ucidef_set_interface_lan "eth0" "dhcp"
		;;
```

So your code should be
```
	cloudengines,pogoe02|\
	cloudengines,pogoplugv4|\
	ctera,c200-v1|\
	globalscale,sheevaplug|\
	iom,iconnect-1.1|\
	iom,ix2-200|\
	iptime,nas1|\
	netgear,readynas-duo-v2|\
	raidsonic,ib-nas62x0|\
	seagate,blackarmor-nas220|\
	seagate,dockstar|\
	seagate,goflexhome|\
	seagate,goflexnet|\
	zyxel,nsa310b|\
	zyxel,nsa310s|\
	zyxel,nsa325)
		ucidef_set_interface_lan "eth0" "dhcp"
		;;
       iom,ix4-200d)
		ucidef_set_interfaces_lan_wan "eth0" "eth1"
		;;
```
Not inside existing statement.

2023-05-05 17:16 UTC, obsy commented on target/linux/kirkwood/base-files/etc/board.d/02_network
>  	iptime,nas1|\
No. this is "normal", not inside. 
If you have
```
case $var in
a|\
b)
  echo "1"
  ;;
c)
 echo "2'
 ;;
esac
```

code shows "1" for a or b. but if you change (add) "inside":
```
case $var in
a|\
d)
  echo "0"
  ;;
b)
  echo "1"
  ;;
c)
 echo "2'
 ;;
esac
```

Then for "a" shows 0, not 1, as previous. So you code should not break existing behaviour.

2023-05-06 06:28 UTC, obsy commented on target/linux/kirkwood/base-files/etc/board.d/02_network
> +	iom,ix4-200d)
Please keep the alphabetical order.

2023-05-06 19:10 UTC, CHKDSK88 commented on target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-ix4-200d.dts
> +		spi_pin1: spi-pin1 {
Shrink pin properties into one is easier to read. Please look: https://github.com/openwrt/openwrt/blob/08cc6bc6649f0f184868bd950e38c6107abba0ae/target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-c200-v1.dts#L251

2023-05-06 19:10 UTC, CHKDSK88 commented on target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-ix4-200d.dts
> +	pcie-controller {
Please use aliases where is possible.

2023-05-06 19:10 UTC, CHKDSK88 commented on target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-ix4-200d.dts
> +	partition@0 {
Please wrap partitions. Like this: https://github.com/openwrt/openwrt/blob/ed1217eac188b8d4649730b8cf6d35eac6dcd1a8/target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-ea3500.dts#L145

2023-05-06 19:10 UTC, CHKDSK88 commented on target/linux/kirkwood/image/Makefile
> +  SUPPORTED_DEVICES += marvell,rd88f6281-a
why?

2023-05-06 19:10 UTC, CHKDSK88 commented on target/linux/kirkwood/image/Makefile
> +  DEVICE_PACKAGES := kmod-ata-marvell-sata kmod-fs-ext4 \
Please keep alphabetical order.

2023-05-06 19:37 UTC, CHKDSK88 commented on target/linux/kirkwood/image/Makefile
> +  SUPPORTED_DEVICES += marvell,rd88f6281-a
Why `SUPPORTED_DEVICES ` is added? It is used for legacy purposes.

2023-05-06 19:40 UTC, CHKDSK88 commented on target/linux/kirkwood/base-files/etc/board.d/02_network
> +		ucidef_set_interfaces_lan_wan "eth0" "eth1"
I'm not sure if NAS should be configured like router. Maybe `ucidef_set_interface_lan "eth0 eth1" "dhcp"` will be better?

2023-05-08 06:51 UTC, CHKDSK88 commented on target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-ix4-200d.dts
> +	pcie-controller {
Please look here: https://github.com/openwrt/openwrt/blob/a872570c043f5beee21c3af695f1a5a77f7eab04/target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-nsa310s.dts#L260

You can do it simpler:
```
&pciec {
	status = "okay";
};

&pcie0 {
	status = "okay";
};
```

2023-05-08 06:53 UTC, CHKDSK88 commented on target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-ix4-200d.dts
> +	compatible = "iom,ix4-200d", "marvell,rd88f6281-a", "marvell,rd88f6281", "marvell,kirkwood-88f6281", "marvell,kirkwood";
` "marvell,rd88f6281-a", "marvell,rd88f6281",` should be dropped.

2023-05-08 07:06 UTC, CHKDSK88 commented on target/linux/kirkwood/image/Makefile
> +  SUPPORTED_DEVICES += marvell,rd88f6281-a
And that is wrong.  Please clean this https://github.com/openwrt/openwrt/pull/12543/files#r1187088402 and `SUPPORTED_DEVICES ` line. First sysupgrade must be with `-F` and next should be work normal.

2023-05-11 12:21 UTC, CHKDSK88 commented on target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-ix4-200d.dts
> +			};
One more nitpick: Ident ;)

2023-05-12 08:17 UTC, CHKDSK88 commented on target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-ix4-200d.dts
> +			};
Yep, only `};`.

2023-05-12 08:19 UTC, CHKDSK88 commented on target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-ix4-200d.dts
> +};
You,re right. Indentation is only improper. All subnodes of `/ {`.

2023-05-16 20:42 UTC, CHKDSK88 commented
> @CHKDSK88 anything I can do to help this get merged? Hope to get this in before 23.x branches smiley

@sanderpqr
Please fix ident in `/ {` node and squash all changes into single commit. After that please push branch with `force` option.

2023-05-18 22:41 UTC, closed without merging