ramips: add support for HiWiFi HC5861B
openwrt/openwrt pull request #1264
Opened 2018-08-09 17:38 UTC by dengqf6

HiWiFi "Gee Enjoy1200" HC5861B is a dual-band router based on MediaTek MT7628AN
https://www.hiwifi.com/enjoy-view

Specifications:
- MediaTek MT7628AN 580MHz
- 128 MB DDR2 RAM
- 16 MB SPI Flash
- 2.4G MT7628AN 802.11bgn 2T2R 300Mbps
- 5G MT7612EN 802.11ac 2T2R 867Mbps
- 5x 10/100 Mbps Ethernet

Flash instruction:
1. Get SSH access to the router
2. SSH to router with `ssh -p 1022 root@192.168.199.1`, The SSH password is the same as the webconfig one
3. Upload OpenWrt sysupgrade firmware into the router's `/tmp` folder with SCP
4. Run `mtd write /tmp/<filename> firmware`
5. reboot

2018-08-10 05:26 UTC, mkresin requested changes
Please use ```git commit --amend``` to add changes to your commit. Use ```git push --force``` to overwrite your github repository/branch. The PR will afterwards update automatically. Please don't close this PR and open a new one.

2018-08-10 05:26 UTC, mkresin commented on target/linux/ramips/base-files/lib/ramips.sh
> +	*"HC5861B")
Please drop this block and use the board compatible string instead as userspace boardname (`hiwifi,hc5861b`)

2018-08-10 05:26 UTC, mkresin commented on target/linux/ramips/image/mt76x8.mk
> +define Device/hc5861b
please use `define Device/hiwifi_hc5861b`here

2018-08-10 05:26 UTC, mkresin commented on target/linux/ramips/image/mt76x8.mk
> +  IMAGE_SIZE := $(ralink_default_fw_size_16M)
ralink_default_fw_size_16M is 16121856 byte == 0xF60000. But your firmware partition has a size of 0xf70000 bytes. Please use `15808k` here.

2018-08-10 05:26 UTC, mkresin commented on target/linux/ramips/image/mt76x8.mk
> +TARGET_DEVICES += hc5861b
`TARGET_DEVICES += hiwifi_hc5861b` please

2018-08-10 05:26 UTC, mkresin commented on target/linux/ramips/dts/HC5861B.dts
> +		linux,modalias = "m25p80", "w25q128";
Please drop the linux,modalias. it isn't used since kernel 4.4.

2018-08-10 06:46 UTC, dengqf6 commented
Updated

2018-08-10 18:47 UTC, mkresin commented
And for sure not tested. The userspace boardname used is now wrong:

> Please drop this block and use the board compatible string instead as userspace boardname (hiwifi,hc5861b)

2018-08-10 18:47 UTC, mkresin approved these changes

2018-08-10 18:55 UTC, dengqf6 commented
Oops, forgot to replace it
SEDed

2018-08-11 09:12 UTC, mkresin commented
Please provide a bootlog! It doesn't make any sense if you're doing the requested changes without testing the outcome.

2018-08-13 15:35 UTC, dengqf6 commented
Here it is
```
BusyBox v1.29.2 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r7845-22b8237ba1
 -----------------------------------------------------
root@OpenWrt:~# dmesg
[    0.000000] Linux version 4.14.62 (f@userver) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r7489-2601e34fad)) #0 Fri Aug 10 16:43:23 2018
[    0.000000] Board has DDR2
[    0.000000] Analog PMU set to hw control
[    0.000000] Digital PMU set to hw control
[    0.000000] SoC Type: MediaTek MT7628AN ver:1 eco:2
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019655 (MIPS 24KEc)
[    0.000000] MIPS: machine is HiWiFi HC5861B
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 08000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] On node 0 totalpages: 32768
[    0.000000] free_area_init_node: node 0, pgdat 804a0060, node_mem_map 81000040
[    0.000000]   Normal zone: 256 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 32768 pages, LIFO batch:7
[    0.000000] random: get_random_bytes called from start_kernel+0x8c/0x474 with crng_init=0
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32512
[    0.000000] Kernel command line: console=ttyS0,115200 rootfstype=squashfs,jffs2
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Writing ErrCtl register=00061b70
[    0.000000] Readback ErrCtl register=00061b70
[    0.000000] Memory: 124704K/131072K available (3711K kernel code, 176K rwdata, 852K rodata, 180K init, 209K bss, 6368K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 256
[    0.000000] intc: using register map from devicetree
[    0.000000] CPU Clock: 580MHz
[    0.000000] timer_probe: no matching timers found
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 6590553264 ns
[    0.000012] sched_clock: 32 bits at 290MHz, resolution 3ns, wraps every 7405115902ns
[    0.007895] Calibrating delay loop... 385.84 BogoMIPS (lpj=1929216)
[    0.074142] pid_max: default: 32768 minimum: 301
[    0.079034] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.085683] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.098665] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.108602] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.114829] pinctrl core: initialized pinctrl subsystem
[    0.120634] NET: Registered protocol family 16
[    0.234085] mt7620-pci 10140000.pcie: Port 0 N_FTS = 1b105000
[    0.389658] PCI host bridge /pcie@10140000 ranges:
[    0.394456]  MEM 0x0000000020000000..0x000000002fffffff
[    0.399717]   IO 0x0000000010160000..0x000000001016ffff
[    0.422075] mt7621_gpio 10000600.gpio: registering 32 gpios
[    0.427986] mt7621_gpio 10000600.gpio: registering 32 gpios
[    0.433753] mt7621_gpio 10000600.gpio: registering 32 gpios
[    0.440195] PCI host bridge to bus 0000:00
[    0.444288] pci_bus 0000:00: root bus resource [mem 0x20000000-0x2fffffff]
[    0.451280] pci_bus 0000:00: root bus resource [io  0xffffffff]
[    0.457216] pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
[    0.464090] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    0.472133] pci 0000:00:00.0: [14c3:0801] type 01 class 0x060400
[    0.472175] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    0.472191] pci 0000:00:00.0: reg 0x14: [mem 0x20200000-0x2020ffff]
[    0.472271] pci 0000:00:00.0: supports D1
[    0.472283] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    0.472740] pci 0000:01:00.0: [14c3:7662] type 00 class 0x028000
[    0.472812] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff 64bit]
[    0.472870] pci 0000:01:00.0: reg 0x30: [mem 0x00000000-0x0000ffff pref]
[    0.472973] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold
[    0.473211] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    0.473232] pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 01
[    0.473279] pci 0000:00:00.0: BAR 0: no space for [mem size 0x80000000]
[    0.479963] pci 0000:00:00.0: BAR 0: failed to assign [mem size 0x80000000]
[    0.486955] pci 0000:00:00.0: BAR 8: assigned [mem 0x20000000-0x200fffff]
[    0.493830] pci 0000:00:00.0: BAR 9: assigned [mem 0x20100000-0x201fffff pref]
[    0.501120] pci 0000:00:00.0: BAR 1: assigned [mem 0x20200000-0x2020ffff]
[    0.508005] pci 0000:01:00.0: BAR 0: assigned [mem 0x20000000-0x200fffff 64bit]
[    0.515392] pci 0000:01:00.0: BAR 6: assigned [mem 0x20100000-0x2010ffff pref]
[    0.522691] pci 0000:00:00.0: PCI bridge to [bus 01]
[    0.527699] pci 0000:00:00.0:   bridge window [mem 0x20000000-0x200fffff]
[    0.534572] pci 0000:00:00.0:   bridge window [mem 0x20100000-0x201fffff pref]
[    0.546299] clocksource: Switched to clocksource MIPS
[    0.552522] NET: Registered protocol family 2
[    0.557910] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.564919] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.571400] TCP: Hash tables configured (established 1024 bind 1024)
[    0.577945] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.583808] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.590460] NET: Registered protocol family 1
[    0.594887] PCI: CLS 0 bytes, default 32
[    0.598286] Crashlog allocated RAM at address 0x3f00000
[    0.605083] workingset: timestamp_bits=30 max_order=15 bucket_order=0
[    0.617407] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.623243] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.643661] io scheduler noop registered
[    0.647630] io scheduler deadline registered (default)
[    0.653608] Serial: 8250/16550 driver, 3 ports, IRQ sharing disabled
[    0.661173] console [ttyS0] disabled
[    0.664773] 10000c00.uartlite: ttyS0 at MMIO 0x10000c00 (irq = 28, base_baud = 2500000) is a 16550A
[    0.673967] console [ttyS0] enabled
[    0.680964] bootconsole [early0] disabled
[    0.689587] cacheinfo: Failed to find cpu0 device node
[    0.694799] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.701730] spi-mt7621 10000b00.spi: sys_freq: 193333333
[    0.722134] m25p80 spi0.0: w25q128 (16384 Kbytes)
[    0.726981] 7 fixed-partitions partitions found on MTD device spi0.0
[    0.733422] Creating 7 MTD partitions on "spi0.0":
[    0.738303] 0x000000000000-0x000000030000 : "u-boot"
[    0.744278] 0x000000030000-0x000000040000 : "hw_panic"
[    0.750403] 0x000000040000-0x000000050000 : "factory"
[    0.756415] 0x000000050000-0x000000fc0000 : "firmware"
[    0.836682] 2 uimage-fw partitions found on MTD device firmware
[    0.842711] 0x000000050000-0x0000001d6268 : "kernel"
[    0.848682]  [...]

2018-08-14 08:27 UTC, mkresin commented
merged, thanks!

2018-08-14 08:27 UTC, closed without merging