mediatek: Add support for TP-Link EAP225v5
openwrt/openwrt pull request #13580
Opened 2023-10-01 09:26 UTC by RolandoMagico

Device specification:
- MT7629 with 16MB NOR flash W25Q128 and 128 MB DDR3 RAM.
- MT7761N and MT7762N wireless chips (currenlty no driver in OpenWrt available)
- Dual core but second CPU doesn't seem to work (Error message during boot: "CPU1: failed to come online")

There are two similar merge requests for similar devices with the same issues:
- https://github.com/openwrt/openwrt/pull/12286
- https://github.com/openwrt/openwrt/pull/5084

UART interface is next to the reset button, pinout:
- 1: TX (the pin with the arrow marker)
- 2: RX
- 3: GND
- 4: VCC

UART settings: 115200,8n1, 3.3V

U-Boot menu can be entered by pressing Ctrl+B during startup.

Booting initramfs:
- Set your computers IP adress to 192.168.1.110
- Run a TFTP server providing the initramfs image
- Power on the AP, press Ctrl+B to get to the U-Boot menu
- Select "1. System Load Linux to SDRAM via TFTP"
- Update kernel file name, input server IP and input device IP (if they deviate from the defaults)
- After booting, create a backup of all partitions, especially for kernel and root_fs. They are required for reverting back to stock firmware
- The sysupgrade image can be flashed now

MAC adresses:
- LAN and 2.4GHz use the same MAC (the one printed on the device)
- 5GHz WiFi MAC is LAN MAC + 1

GPIOs:
- GPIO 21 is the reset pin (low active)
- GPIO 55 is for the green LED (active high)
- GPIO 56 is for the yellow/amber LED (active high)

2023-10-29 18:10 UTC, hauke commented
Please use a real email address.

Please configure a lan network, like it is done here: https://github.com/openwrt/openwrt/blob/main/target/linux/mediatek/mt7629/base-files/etc/board.d/02_network#L11

Is sysupgrade working? If not maybe some changes here are needed: https://github.com/openwrt/openwrt/blob/main/target/linux/mediatek/mt7629/base-files/lib/upgrade/platform.sh#L12

2023-10-31 07:08 UTC, RolandoMagico commented
I fixed the mail address and added the device to mediatek_setup_interfaces in /etc/board.d/02_network.
Sysupgrade is already working, form my point of view nothing to do here.

2023-10-31 13:07 UTC, hauke commented
The author mail is still wrong, you can fix it with `git commit --amend --author="Name <email@domain>"`

2023-10-31 13:20 UTC, RolandoMagico commented
Ok, tried to fix it. Somehow it looks like my old "ContextQuickie" account is involved now, is this ok?

2023-11-02 15:57 UTC, blocktrron requested changes
Is WiFi working on this device? I see no extraction of the EEPROM data.

2023-11-03 06:38 UTC, RolandoMagico commented
Hello @blocktrron,
I update the DTS with your remarks. Wifi is not working on this device, there is no driver for it in OpenWrt as far as I saw. I updated the description and the commit message accordingly to make it more clear.
Best Regards
Roland

2023-11-12 16:40 UTC, merged