ramips: Add support for ASUS RT-AC51U / RT-AC54U
openwrt/openwrt pull request #137
Opened 2016-10-16 12:50 UTC by p055877632

[https://github.com/openwrt/openwrt/pull/132](https://github.com/openwrt/openwrt/pull/132)

The previous version did not complete

I am so sorry

2016-10-16 12:57 UTC, p055877632 commented
p.s.

power2 {
label = "rt-ac51u:blue:power2";
gpios = <&gpio0 10 0>;

is ALL LED Control  FOR
5G WIFI LED (mt76 not support)
2.4G WIFI LED
USB LED
WAN LED
LAN LED

don't  remove

2016-10-16 13:24 UTC, p055877632 commented
gpio10 LED trap......

Asus and odm Factory edimax/acelink group "thanks a lot"

f*** you

2016-10-27 11:38 UTC, blogic requested changes
the two dts files look almost identical. please consider merging them into a dtsi file and including this in botht he dts files.

2016-10-27 11:38 UTC, blogic commented on target/linux/ramips/base-files/lib/ramips.sh
>  	*"RT-N15")
please stick to alphabetical ordering

2016-10-27 11:38 UTC, blogic commented on target/linux/ramips/base-files/lib/upgrade/platform.sh
>  	rt-n15|\
please stick to alphabetical ordering

2016-10-28 04:43 UTC, p055877632 commented on target/linux/ramips/base-files/lib/upgrade/platform.sh
>  	rt-n15|\
NO

AC51U 
AC54U

This is 2 Router
(maybe one pcb)

2016-11-23 11:53 UTC, wigyori commented on target/linux/ramips/base-files/lib/upgrade/platform.sh
>  	rt-n15|\
"Yes". If you add separate entries, stick to alphabetical ordering.

2017-11-07 21:53 UTC, blogic commented
already part of the LEDE tree which will replace the OWRT tree shortly

2017-11-07 21:53 UTC, closed without merging