filogic: add support for ASUS RT-AX52
openwrt/openwrt pull request #14206
Opened 2023-12-12 09:37 UTC by liudongdongdong7397

Hardware
--------
SOC:   MediaTek MT7981b
RAM:   256MB DDR3
FLASH: 128MB SPI-NAND (Winbond W25N01GV)
WIFI:  Mediatek MT7981b DBDC 802.11ax 2.4/5 GHz
ETH:   MediaTek MT7531 Switch
UART:  3V3 115200 8N1 (Pinout silkscreened / Do not ocnnect VCC)

Installation
-------------------Install openwrt image-------------------------------:
1. Download the OpenWrt initramfs image. 
    Copy the image to a TFTP server reachable at 192.168.1.70/24. 
    Rename the image to rtax52.bin.

2. Connect the PC with TFTP server to the RT-AX52. 
    Set a static ip on the ethernet interface of your PC. (ip address: 192.168.1.70, subnet mask:255.255.255.0) .
    Conect to the serial console, interrupt the autoboot process by pressing '4' when prompted.

3. Download & Boot the OpenWrt initramfs image.

   $ setenv ipaddr 192.168.1.1 
   $  setenv serverip 192.168.1.70 
   $ tftpboot 0x46000000 rtax52.bin 
   $ bootm 0x46000000

4. Wait for OpenWrt to boot. Transfer the sysupgrade image to the device using scp and install using sysupgrade.

   $ sysupgrade -n <path-to-sysupgrade.bin>

----------------------------------------------------------------------------------
-------Revert to stock asus firmware ---------:
1: Download the rt-ax52 firmware from ASUS official website. 
     Save the firmware to tftp server directory and rename  to RT-AX52.trx

2: Connect the PC with TFTP server to the RT-AX52.
   Set a static ip on the ethernet interface of your PC.
     (ip address: 192.168.1.70, subnet mask:255.255.255.0)

3: Conect to the serial console,  power on again,  interrupt the autoboot process by pressing '4' when prompted.
  $  ubi remove linux
  $  ubi remove jffs2
  $  ubi remove rootfs
  $  ubi remove rootfs_data
  $  ubi create linux 0x45fe000
  $  reset
  then the dut will reboot,interrupt the autoboot process by pressing '2' when prompted.
            2: Load System code then write to Flash via TFTP.
             Warning!! Erase Linux in Flash then burn new one. Are you sure?(Y/N)
             $: enter y
  you will see the follow, type enter directly:
        Input device IP (192.168.1.1) ==:
        Input server IP (192.168.1.70) ==:
        Input Linux Kernel filename (RT-AX52.trx) ==:

4: wait for the device run up

2023-12-13 10:15 UTC, musashino205 commented
Please,

- use your real name for ```Signed-off-by``` line in the commit message
  - also on [the author field (```From: ```)](https://github.com/openwrt/openwrt/pull/14206.patch) of the commit
- use the target name instead of sub-target name (```mediatek: ```)

 see details: https://openwrt.org/submitting-patches#submission_guidelines

2023-12-18 07:28 UTC, rmilecki commented on target/linux/mediatek/dts/mt7981b-asus-rt-ax52.dts
> +/dts-v1/;
You didn't include SPDX line at the top of this file. It makes DTS fall under OpenWrt's default licensing which is GPL 2.0.

DTS files for mt7981* are licensed under GPL 2.0 and MIT. Please license your file the same way to make them compatible. For that you need
```
// SPDX-License-Identifier: GPL-2.0-only OR MIT
```

2024-01-06 17:41 UTC, hauke commented
Please rebase this on top of main.

2024-03-29 20:59 UTC, SorCelien commented
Is there a way for me to help on this topic? I have the asus AX52 too.

2024-08-06 08:12 UTC, tapper82 commented
Ping @liudongdongdong7397

2024-09-09 15:01 UTC, rmilecki requested changes

2024-09-09 15:01 UTC, rmilecki commented on target/linux/mediatek/dts/mt7981b-asus-rt-ax52.dts
> +			label = "wps";
Is this a mesh button (see node name) or WPS (see `label`)?

2024-10-22 10:55 UTC, liudongdongdong7397 commented
> Please,
> 
> * use your real name for `Signed-off-by` line in the commit message
>   
>   * also on [the author field (`From: `)](https://github.com/openwrt/openwrt/pull/14206.patch) of the commit
> * use the target name (`mediatek: `) instead of sub-target name for the commit title
> 
> see details: https://openwrt.org/submitting-patches#submission_guidelines

Thank you, it has been adjusted

2025-01-20 11:48 UTC, cociweb commented
@rmilecki is there anything we need to do with this PR?

2025-01-20 22:09 UTC, hauke commented
Please rebase this on top of main.

2025-01-24 21:03 UTC, cociweb commented
ping @liudongdongdong7397

2025-02-02 19:47 UTC, cociweb commented
it seems @liudongdongdong7397 is offline for a while. Does anybody has right to rebase this PR?

2025-03-20 01:19 UTC, liudongdongdong7397 commented
@

> it seems @liudongdongdong7397 is offline for a while. Does anybody has right to rebase this PR?

Hello : rebase completed.

2025-03-23 09:23 UTC, achterin commented on target/linux/mediatek/image/filogic.mk
> +define Device/asus_rt-ax52
this should be moved above "define Device/asus_rt-ax59u" to follow the alphabetical sorting. the asus_tuf-ax6000 needs to be moved as well but i'll post a small pr for that.

2025-03-23 13:37 UTC, achterin commented
i just tested your pr but cannot get the lan ports to work. i see the leds light up but no log message about link up in the logs.

2025-03-23 13:49 UTC, achterin commented
are these changes (33197d22f0045b491ddea580bb2940a730918233, 4387de94454913aa79bb88971eabcf1bfca78141) applied to other asus devices also relevant to this one?

2025-03-23 13:50 UTC, achterin commented on target/linux/mediatek/dts/mt7981b-asus-rt-ax52.dts
> +&xhci {
is this really needed as the device has no usb ports?

2025-03-23 13:52 UTC, achterin commented on target/linux/mediatek/dts/mt7981b-asus-rt-ax52.dts
this file contains a mix of spaces and tabs but only tabs should be used.

2025-03-23 16:18 UTC, achterin commented on target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh
> +	asus,rt-ax52|\
please sort alphabetically

2025-03-23 16:19 UTC, achterin commented on target/linux/mediatek/filogic/base-files/etc/board.d/02_network
> +	asus,rt-ax52)
please sort alphabetically

2025-03-23 16:21 UTC, achterin commented on target/linux/mediatek/filogic/base-files/etc/board.d/01_leds
> +asus,rt-ax52)
please sort alphabetically

2025-03-24 01:11 UTC, dangowrt requested changes

2025-03-24 01:11 UTC, dangowrt commented on target/linux/mediatek/filogic/base-files/etc/hotplug.d/firmware/11-mt76-caldata
> +		caldata_extract_ubi "Factory" 0x0 0x1000
Please use nvmem in DT instead of extraction in userspace. See other ASUS devices.

2025-03-24 01:11 UTC, dangowrt commented on target/linux/mediatek/filogic/base-files/etc/hotplug.d/ieee80211/11_fix_wifi_mac
> +	asus,rt-ax52|\
also here, please nvmem in DT.

2025-03-24 22:37 UTC, achterin commented
@liudongdongdong7397 i just fixed all the issues i identified and added the changed @dangowrt suggested. lan ports do work now (also the labels are correct). mac addr are identical to vendor except like all the other asus devices the upper bit is also incremented. you can find the changes here: https://github.com/achterin/openwrt/commit/3dc114996297b91913410c1b055bf19a6cb5a6fe

2025-03-25 06:52 UTC, achterin commented on target/linux/mediatek/filogic/base-files/etc/board.d/01_leds
> +asus,rt-ax52)
also the case above is not terminated

2025-03-25 06:52 UTC, achterin commented on target/linux/mediatek/filogic/base-files/etc/board.d/02_network
> +	asus,rt-ax52)
missing case termination as well

2025-03-26 02:44 UTC, liudongdongdong7397 commented on target/linux/mediatek/image/filogic.mk
> +define Device/asus_rt-ax52
Adjusted.
Thank you.

2025-03-26 02:45 UTC, liudongdongdong7397 commented on target/linux/mediatek/dts/mt7981b-asus-rt-ax52.dts
> +&xhci {
Adjusted.
Thank you.

2025-03-26 02:46 UTC, liudongdongdong7397 commented on target/linux/mediatek/dts/mt7981b-asus-rt-ax52.dts
Adjusted.
Thank you.

2025-03-26 02:46 UTC, liudongdongdong7397 commented on target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh
> +	asus,rt-ax52|\
Adjusted.
Thank you.

2025-03-26 02:46 UTC, liudongdongdong7397 commented on target/linux/mediatek/filogic/base-files/etc/board.d/02_network
> +	asus,rt-ax52)
Adjusted.
Thank you.

2025-03-26 02:47 UTC, liudongdongdong7397 commented on target/linux/mediatek/filogic/base-files/etc/board.d/01_leds
> +asus,rt-ax52)
Adjusted.
Thank you.

2025-03-26 02:47 UTC, liudongdongdong7397 commented on target/linux/mediatek/filogic/base-files/etc/board.d/02_network
> +	asus,rt-ax52)
Adjusted.
Thank you.

2025-03-26 02:49 UTC, liudongdongdong7397 commented on target/linux/mediatek/filogic/base-files/etc/hotplug.d/firmware/11-mt76-caldata
> +		caldata_extract_ubi "Factory" 0x0 0x1000
Adjusted，according to @actherin's changes;
Thank you.

2025-03-26 02:50 UTC, liudongdongdong7397 commented on target/linux/mediatek/filogic/base-files/etc/hotplug.d/ieee80211/11_fix_wifi_mac
> +	asus,rt-ax52|\
Adjusted，according to @actherin's changes;
Thank you.

2025-04-03 06:38 UTC, achterin commented
@dangowrt anything else missing here to get this into main?

2025-04-06 21:20 UTC, achterin commented
@liudongdongdong7397 have you tried generating asuswrt compatible images? using https://github.com/openwrt/firmware-utils/blob/master/src/asusuimage.c by adapting these [changes ](https://github.com/openwrt-xiaomi/openwrt/commit/20c381a2c06655f1633d216e9a60a9265fafbde2) should be sufficient.

2025-04-06 21:31 UTC, hauke commented on target/linux/mediatek/dts/mt7981b-asus-rt-ax52.dts
> +	};
Why do you need these pwm pin settings?

2025-04-06 21:33 UTC, hauke commented on target/linux/mediatek/dts/mt7981b-asus-rt-ax52.dts
> +		};
Is this and the `compatible = "u-boot-dont-touch-spi-nand";` workaround needed also for this Asus boot loader?

@dangowrt are both workarounds needed or is the `compatible = "u-boot-dont-touch-spi-nand";` one sufficient?

2025-04-06 21:48 UTC, dangowrt commented on target/linux/mediatek/dts/mt7981b-asus-rt-ax52.dts
> +		};
It depends on the version of U-Boot on the device -- some devices look for a `partitions` label and replace the partitions therein, newer versions look for the `spi-nand` compatible and the `partitions` subnode. Some ASUS devices were shipped with an older loader and later on the loader was updated in-field by a firmware update... So unless there is a good reason to believe that a particular device was only produced recently and hence always comes with newer U-Boot (like MT7988D-based BT8 Wi-Fi 7 router), I would suggest to keep both work-arounds for Wi-Fi 6 and earlier generations.

2025-04-21 09:32 UTC, Pterosaur commented
Hi Openwrt community, when can this PR get merged?

2025-04-21 13:12 UTC, achterin commented
> Hi Openwrt community, when can this PR get merged?

When its ready and all comments are resolved.

2025-04-24 13:59 UTC, achterin commented
As my pr got merged to @blocktrron 's staging tree, i guess this pr can be closed as well.

2025-04-25 15:01 UTC, blocktrron commented
Closing.

2025-04-25 15:01 UTC, closed without merging

2025-04-25 20:23 UTC, Neustradamus commented
Merged commit:
- https://github.com/openwrt/openwrt/commit/50d9ca6e5a04724e4263a348bdbe5ff4b1c43998

Linked to:
- https://github.com/openwrt/openwrt/pull/18555

2025-09-06 04:23 UTC, jvdar1981 commented
how to revert to stock asus firmware using linux mint? anyone can help me... thank you