dnsmasq: Add EDNS0 Upstream support
openwrt/openwrt pull request #14349
Opened 2024-01-06 14:18 UTC by db260179

Forward client mac address and subnet on dns queries.

Pi-hole and Adguard use this feature to send the originators ip address/subnet so it can be logged and not just the nat address of the router.

This feature has been added since version 2.56 of dnsmasq and would be nice to expose this feature in openwrt.

2024-01-15 08:25 UTC, schuettecarsten commented
Please make this configurable (default: on), as adding the requestors MAC address to upstream forwarded requests might have security or privacy implications. Forwarding MAC address and subnet is only useful if you use Pihole/Adguard but not for external upstream servers.

2024-01-15 09:57 UTC, KanjiMonster commented
> Please make this configurable (default: on), as adding the requestors MAC address to upstream forwarded requests might have security or privacy implications. It is only useful if you use Pihole/Adguard but not for external upstream servers.

If this can have security or privacy implications the default should be off, not on.

2024-02-20 08:23 UTC, schuettecarsten commented
Tested together with PiHole (development-v6), works.
I would also suggest to add an option for "--strip-subnet":

```
append_bool "$cfg" strip_subnet "--strip-subnet"
```

I've also created a draft to add this to LuCI in dhcp.js (line 650):

```
s.taboption('forward', form.Flag, 'add_mac',
        _('Add requestor MAC address to forwards'),
        _('Add the MAC address of the requestor to DNS queries which are forwarded upstream.'));

o = s.taboption('forward', form.Value, 'add_subnet',
        _('Add subnet address to forwards'),
        _('Add a subnet address to the DNS queries which are forwarded upstream.'));
o.optional = true;

s.taboption('forward', form.Flag, 'strip_subnet',
        _('Remove any subnet address before forwarding query'),
        _('Remove any subnet address already present in a downstream query before forwarding it upstream.'));
```

2024-02-20 08:28 UTC, schuettecarsten approved these changes

2024-02-20 09:29 UTC, DBenthamSporting commented
> Tested together with PiHole (development-v6), works. I would also suggest to add an option for "--strip-subnet" and "--strip-mac":
> 
> ```
> append_bool "$cfg" strip_mac "--strip-mac"
> append_bool "$cfg" strip_subnet "--strip-subnet"
> ```
> 
> I've also created a draft to add this to LuCI in dhcp.js (line 650):
> 
> ```
> s.taboption('forward', form.Flag, 'add_mac',
>         _('Add requestor MAC address to forwards'),
>         _('Add the MAC address of the requestor to DNS queries which are forwarded upstream.'));
> 
> s.taboption('forward', form.Flag, 'strip_mac',
>         _('Remove MAC address before forwarding query'),
>         _('Remove any MAC address information already in downstream queries before forwarding upstream.'));
> 
> o = s.taboption('forward', form.Value, 'add_subnet',
>         _('Add subnet address to forwards'),
>         _('Add a subnet address to the DNS queries which are forwarded upstream, e.g. {32,128} for full requestor address.'));
> o.optional = true;
> 
> s.taboption('forward', form.Flag, 'strip_subnet',
>         _('Remove subnet address before forwarding query'),
>         _('Remove any subnet address already present in a downstream query before forwarding it upstream.'));
> ```

Ok, you want me to add your suggestions to this commit?

2024-03-07 16:04 UTC, schuettecarsten approved these changes

2024-03-08 00:29 UTC, systemcrash requested changes

2024-04-23 12:12 UTC, systemcrash commented
ping @db260179 - please resolve the code-change comments

2024-04-25 08:52 UTC, db260179 commented
> ping @db260179 - please resolve the code-change comments

When i get time to do this, busy at the moment

2024-07-17 20:06 UTC, schuettecarsten commented
I've created two new PRs for this, one for the openwrt core system and a luci patch.

2024-07-17 22:48 UTC, systemcrash commented
Please close this PR as outdated/abandoned.

2024-07-18 03:52 UTC, closed without merging