feat(mvebu): add kernel modules for Turris Omnia Wi-Fi 6 upgrade kit
openwrt/openwrt pull request #14553
Opened 2024-02-05 08:03 UTC by PsychoGame

The following kernel module packages were added to the build recipe for the Turris Omnia:
- kmod-mt76
- kmod-mt76-connac
- kmod-mt7915e These modules enable support for the official Wi-Fi 6 upgrade kit sold by CZ.NIC, which includes the AW7915-NP1 miniPCIE board based on Mediatek MT7915AN, providing 5 GHz Wi-Fi 6 connectivity.

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

2024-02-05 22:06 UTC, neheb approved these changes

2024-02-08 11:00 UTC, Alphix commented
@PsychoGame isn't `kmod-mt7915-firmware` necessary as well? Or will it be automatically included in the build via some kind of dependency? (asking because I had to manually install both `kmod-mt7915-firmware` and `kmod-mt7915e` after installing 23.05.2).

2024-02-11 12:19 UTC, hauke requested changes
@Alphix is right. To support the AW7915-NP1 you only have to add `mt7915-firmware` to the dependencies. This package depends itself on `kmod-mt76`, `kmod-mt76-connac` and  `kmod-mt7915e`

2024-02-11 12:19 UTC, chunkeey commented
> @PsychoGame isn't `kmod-mt7915-firmware` necessary as well? Or will it be automatically included in the build via some kind of dependency? (asking because I had to manually install both `kmod-mt7915-firmware` and `kmod-mt7915e` after installing 23.05.2).

Good point, it looks like including  `kmod-mt7915-firmware`  is what's needed. The `kmod-mt7915-firmware` will pull in kmod-mt7915e.

2024-02-11 16:40 UTC, PsychoGame commented
@Alphix, Yes you're right I oversaw this in my router, that's my mistake. Sorry for my late response, I'm currently at sea due to the nature of my profession. But for now I'm in reach of cellular reception, so I'll fix-up my MR ASAP.

@hauke: Will fix-it up right away

2024-02-16 18:20 UTC, BKPepe approved these changes

2024-02-26 20:34 UTC, merged