[RFC] gre: add static ip on setup
openwrt/openwrt pull request #1471
Opened 2018-10-15 12:12 UTC by feckert

@dedeckeh 
Normaly the gre proto handler will only setup the tunnel configuration
params. If you want to send traffic over this interface you need also
set an address to this interface. This is normaly done with a ralated
interface with the openwrt "@" syntax on an additonal configuration step.

To simplify the configuration setps add the possibility setting up the static
ip for this gre interface in the proto handler during setup step. So you
do mot need an additonal configuration section in the network config.

If the params iface_ipaddr and/or iface_netmask is specified in the
interface config section then the gre interface will also get a static
ip or network assigned.

2018-10-15 19:01 UTC, dedeckeh requested changes
I'm not convinced if the gre protocol handler script should be bloated with such logic.
Why are the iface_ipaddr/iface_netmask parameters only added for the gretap protocol while you add the logic in the proto_gre_setup script which handles the gre protocol ?

2018-10-16 06:17 UTC, feckert commented
@dedeckeh 

> I'm not convinced if the gre protocol handler script should be bloated with such logic.

Explanation:
I have also written a luci-proto-gre for LuCI which I want to contribute as well. During development I setup a GRE interface with this LuCI proto handler. This is not straight forward.

We have to setup an additional logical interface on top with the '@' option. With the new logical interface I can append the interface the proto static and so set the IP (https://wiki.openwrt.org/doc/uci/routing_in_gre).
This interface is then seen in the interface overview page as well. After that I have to add a firewall zone to this intefaces. But this is not clear should i add both to wan or only one of them?

Conclusion:
So I think it is a bit cumbersome to setup a GRE interface in LuCI.
Independently the qmi proto is setting up a dynamic dhcp interface in his proto setup as well.
So why have we added the dhcp creation logic to this proto?

> Why are the iface_ipaddr/iface_netmask parameters only added for the gretap protocol while you add the logic in the proto_gre_setup script which handles the gre protocol ?

From my point of view adding a static ip to the interface make only sense for the proto gre and grev6 and **not** for gretap and grev6tap.
I will also add the logic to grev6 as well if we decide, this is the way we want to go.
I have added the proto to proto_gre_setup this is for **greip** (ipv4).

2018-10-16 06:54 UTC, dedeckeh commented
> @dedeckeh
> 
> > I'm not convinced if the gre protocol handler script should be bloated with such logic.
> 
> Explanation:
> I have also written a luci-proto-gre for LuCI which I want to contribute as well. During development I setup a GRE interface with this LuCI proto handler. This is not straight forward.
> 
> We have to setup an additional logical interface on top with the '@' option. With the new logical interface I can append the interface the proto static and so set the IP (https://wiki.openwrt.org/doc/uci/routing_in_gre).
> This interface is then seen in the interface overview page as well. After that I have to add a firewall zone to this intefaces. But this is not clear should i add both to wan or only one of them?
> 
> Conclusion:
> So I think it is a bit cumbersome to setup a GRE interface in LuCI.
But shouldn't this be fixed in Luci ?
> Independently the qmi proto is setting up a dynamic dhcp interface in his proto setup as well.
> So why have we added the dhcp creation logic to this proto?
What about other tunneling interfaces like ipip ? It looks suboptimal to me if we've to add logic in each tunnel protocol shell handler.
> 
> > Why are the iface_ipaddr/iface_netmask parameters only added for the gretap protocol while you add the logic in the proto_gre_setup script which handles the gre protocol ?
> 
> From my point of view adding a static ip to the interface make only sense for the proto gre and grev6 and **not** for gretap and grev6tap.
> I will also add the logic to grev6 as well if we decide, this is the way we want to go.
> I have added the proto to proto_gre_setup this is for **greip** (ipv4).
My mistake as I initially thought the parameters were added to the gretap protocol

2018-10-16 13:27 UTC, feckert commented
> But shouldn't this be fixed in LuCI ?

I have no idea how to fix this in LuCI. Is there a better way @jow- ?

Maybe we could use the same procedure as with the wwan proto https://github.com/openwrt/openwrt/blob/master/package/network/utils/wwan/files/wwan.sh
This is build on top of qmi, mbim, directip, 3g and ncm?

So we could setup a proto gre_static/grev6_static which uses the gre/grev6. 
So we could split this?

> What about other tunneling interfaces like ipip ? It looks suboptimal to me if we've to add logic in each tunnel protocol shell handler.

We have also vti which is also a tunneling proto.

2018-10-19 11:38 UTC, feckert commented
@dedeckeh I have added a **proof of concept** to use a stacked proto handling.
On top we have the new proto iptunnel which is handling the static ip assignment. All other tunnel handling are made by the lower proto handler.

> I'm not convinced if the gre protocol handler script should be bloated with such logic.

So the logic to assign a static ip is handeled by the new proto iptunnel.

For now i have only implement gre. As described by you we could also add ipip and grev6. Maybe vti and vtiv6 is also possible.

2018-11-06 08:08 UTC, feckert commented
As discussed on the owrt-summit if have palyed arround with your suggestion to configure it without the protohandler gre.

```
config interface 'gre_red'
	option proto 'tunnel'
	option mode 'greip'
	option device 'gre0'
	option local '10.1.3.71'
	option remote '10.1.3.72'
	option ipaddr '10.99.99.1'
	option netmask '255.255.255.255'
```

but this does not work the "gre" interface will no setup. But the kernel modules are loaded and the "netifd" is triggered to reload the configuration.
Any suggestion howto to procceed?

2018-11-12 08:19 UTC, feckert commented
@dedeckeh did you have any advice?

2018-11-12 10:14 UTC, dedeckeh commented
@feckert With the config below it's possible to create a static interface on top of a gre device 

```
config interface 'gre_red'
        option proto 'static'
        option ifname 'gre'
	option ipaddr '10.99.99.1'
	option netmask '255.255.255.255'

config device 'gre'
        option name 'gre'
        option type 'tunnel'
        option mode 'greip'
	option local '10.1.3.71'
	option remote '10.1.3.72'
```

However there're limitations in comparison with the interface proto gre approach

- it's not possible to set gre specific settings like ikey, okey, icsum, ocsum, iseqno, oseqno and encaplimit as the settings are expected to be stored in a data json attribute which is not the case when device uci config is parsed

- The gre proto shell handler installed a dependency on the remote IP address being reachable in order to bring up the gre interface. This is not possible with this approach at the moment which means the  gre_red interface will be up even if the remote GRE tunnel endpoint is not reachable. Need to discuss with @nbd168 how to proceed on this as this is a major issue

2019-01-24 13:58 UTC, feckert commented
@dedeckeh 
I close the pull-request because nothing happend so far.
Instead I will open a follow up PR with the following changes which could be merged without the new proposed package iptunnel.

https://github.com/openwrt/openwrt/pull/1471/commits/2b74685678279d2982812883f28e3738c2d4d9e3
https://github.com/openwrt/openwrt/pull/1471/commits/696d308927100d95b8674f46edf5fc20954089bd

2019-01-24 13:58 UTC, closed without merging