wifi-scripts: client_cert should be commented out when (.p12/.pfx) private keys are used
openwrt/openwrt pull request #14929
Opened 2024-03-19 06:25 UTC by morse-sophronia

When PKCS#12/PFX file (.p12/.pfx) is used, client_cert should be commented out. Both the private key and certificate will be read      from the PKCS#12 file in this case.

In this case, client_cert was always configured in wpa_supplicant.conf causing errors, 

`
Mon Mar 18 16:36:30 2024 daemon.notice wpa_supplicant[21735]: phy0-sta0: CTRL-EVENT-EAP-STARTED EAP authentication started
Mon Mar 18 16:36:30 2024 daemon.notice wpa_supplicant[21735]: phy0-sta0: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=13
Mon Mar 18 16:36:30 2024 daemon.notice wpa_supplicant[21735]: OpenSSL: pending error: error:80000002:system library::No such file or directory
Mon Mar 18 16:36:30 2024 daemon.notice wpa_supplicant[21735]: OpenSSL: pending error: error:10080002:BIO routines::system lib
Mon Mar 18 16:36:30 2024 daemon.notice wpa_supplicant[21735]: OpenSSL: pending error: error:0A080002:SSL routines::system lib
Mon Mar 18 16:36:30 2024 daemon.notice wpa_supplicant[21735]: TLS: Failed to set TLS connection parameters
Mon Mar 18 16:36:30 2024 daemon.notice wpa_supplicant[21735]: EAP-TLS: Failed to initialize SSL.
Mon Mar 18 16:36:30 2024 daemon.notice wpa_supplicant[21735]: phy0-sta0: EAP: Failed to initialize EAP method: vendor 0 method 13 (TLS)
Mon Mar 18 16:36:30 2024 daemon.notice wpa_supplicant[21735]: phy0-sta0: CTRL-EVENT-EAP-FAILURE EAP authentication failed
Mon Mar 18 16:36:30 2024 daemon.notice netifd: Network device 'phy0-sta0' link is down
Mon Mar 18 16:36:30 2024 daemon.notice netifd: Interface 'wwan' has link connectivity loss
Mon Mar 18 16:36:30 2024 kern.info kernel: [ 5251.345598] phy0-sta0: deauthenticated from b8:d8:12:68:04:e0 (Reason: 23=IEEE8021X_FAILED)
Mon Mar 18 16:36:30 2024 daemon.notice wpa_supplicant[21735]: phy0-sta0: CTRL-EVENT-DISCONNECTED bssid=b8:d8:12:68:04:e0 reason=23
Mon Mar 18 16:36:30 2024 daemon.notice wpa_supplicant[21735]: phy0-sta0: CTRL-EVENT-SSID-TEMP-DISABLED id=4 ssid="Test_wpa3_mtk" auth_failures=1 duration=10 reason=AUTH_FAILED
`

`root@ekh03-680869:~# cat /var/run/wpa_supplicant-phy0-sta0.conf

network={
        scan_ssid=1
        ssid="Test_wpa3"
        key_mgmt=WPA-EAP-SHA256
        ca_cert="/etc/luci-uploads/ca.pem"
        identity="user"
        client_cert=""
        private_key="/etc/luci-uploads/client.p12"
        private_key_passwd="password"
        eap=TLS
        proto=RSN
        ieee80211w=2
        beacon_int=100
}
`

2024-03-19 07:12 UTC, systemcrash requested changes

2024-03-19 07:12 UTC, systemcrash commented on package/network/config/wifi-scripts/files/lib/netifd/hostapd.sh
> +     					if [[ -n "$priv_key" && "$priv_key" != *".p12"* && "$priv_key" != *".pfx"* ]]; then
`[[` and `]]` is bash syntax. Don't use it. Globs within `[` and `]` also no go. Needs a `case...esac`.
Suggest
```sh
if [ -n "$priv_key" ]; then
	case "$priv_key" in
	 *".p12")
		;;
	 *".pfx")
		;;
	 *)
	 append ...
	esac
fi
```

2024-03-21 13:22 UTC, systemcrash commented
Please squash your two commits and force push

2024-03-21 13:27 UTC, systemcrash commented
> In this case, client_cert was always configured in wpa_supplicant.conf causing errors,

Does this mean that the logged errors prevent normal operation? Or does normal operation continue?

2024-03-22 06:20 UTC, morse-sophronia commented
@systemcrash  Yes it blocks normal operation and authentication fails in that case

2024-03-22 12:09 UTC, systemcrash commented
Push the correct commits to the correct branch :)

2025-09-15 01:02 UTC, closed without merging