ramips: add support for D-Link DWR-118 A1
openwrt/openwrt pull request #1499
Opened 2018-10-26 17:02 UTC by CHKDSK88

The DWR-118-A1 Wireless Router is based on the MT7620A SoC.

Specification:

- MediaTek MT7620A (580 Mhz)
- 64 MB of RAM
- 16 MB of FLASH
- 1x 802.11bgn radio
- 1x 802.11ac radio (MT7610EN)
- 3x 10/100 Mbps Ethernet (3 LAN)
- 2x 10/100/1000 Mbps ICPlus IP1001 Ethernet PHY (1 WAN AND 1 LAN)
- 1x internal, non-detachable antenna
- 2x external, non-detachable antennas
- 1x USB 2.0
- UART (J1) header on PCB (57600 8n1)
- 7x LED (5x GPIO-controlled), 2x button
- JBOOT bootloader

Known issues:
- WIFI 5G LED not working
- flash is very slow

The status led has been assigned to the dwr-118-a1:green:internet led.
At the end of the boot it is switched off and is available for other
operation. Work correctly also during sysupgrade operation.

Installation:
Apply factory image via http web-gui or JBOOT recovery page

How to revert to OEM firmware:
- push the reset button and turn on the power. Wait until LED start
  blinking (~10sec.)
- upload original factory image via JBOOT http (IP: 192.168.123.254)

Signed-off-by: Pawel Dembicki <paweldembicki@gmail.com>

2018-11-27 22:10 UTC, rozhuk-im commented
IMHO you are erase jboot recovery, it wont work without `0x000000010000-0x000000150000 : "Kernel"`, this is not kernel.
I m erase this on mine DIR-506L and recovery stop work.

2018-11-28 05:54 UTC, CHKDSK88 commented
> IMHO you are erase jboot recovery, it wont work without `0x000000010000-0x000000150000 : "Kernel"`, this is not kernel.
> I m erase this on mine DIR-506L and recovery stop work.

Mobile jboot devices have additional partition. This is regular jboot device and a kernel partition is a kernel partition. Recovery is working.

2018-11-28 06:44 UTC, CHKDSK88 commented
> I write to `0x000000010000` on DIR-510L too and lost recovery too. :)
> Nice to hear that it happen only with me.

On old openwrt forum was a guy, who made 510l a brick.
If You have solder skils, it't possible to repair Your router.

2018-11-28 06:50 UTC, rozhuk-im commented
Sorry for noise here, I m in that topic too.
I have full flash dump, and will restore it after get 16 pin test clip.

2018-11-28 07:15 UTC, krystiansliwa commented
Hi @CHKDSK88,
Can I try that firmware (creating patch) or should I wait for merging it? Is it stable enough?

2018-11-29 12:44 UTC, jej commented
Hi @CHKDSK88,
Thanks for this patch. I would like to try it but I cannot apply the patch anymore. Too far from HEAD...
Do you think it will be merged one day? Do you have another version for the current branch?

2018-11-29 12:52 UTC, CHKDSK88 commented
Hi @jej 

>Do you think it will be merged one day? 

It will be merged if mkresin will have time for this device, I think.

>Do you have another version for the current branch?

I will rebase to current branch. Stay tunned.

2018-11-29 13:04 UTC, jej commented
Ok thanks.
I tried to apply the changes manually but it seems the HEAD changed a lot since your patch...

2018-11-29 13:48 UTC, CHKDSK88 commented
> Ok thanks.
> I tried to apply the changes manually but it seems the HEAD changed a lot since your patch...

Try now.

2018-11-29 13:57 UTC, jej commented
So, I `git clone openwrt/openwrt`, then I download your patch and `git apply` it?

2018-11-29 23:51 UTC, jej commented
Working like a charm! Thanks for your work, waiting for the merge!
Jej

Sent from my new opensourced router

2018-11-30 00:40 UTC, jej commented
I am a bit confused concerning the led configuration. That's not the most important but just to play a bit...
I mapped the "internet led" (earth icon) to my wwan LTE modem, the led is named dwr-118-a1:green:wan. Working well.
For the wireless I have 2 led icons (one for each 2.4 and 5ghz), but in the source only "phy1:radio" led exists. And I cannot light any wireless led with that.
Any idea?...

2018-11-30 06:14 UTC, CHKDSK88 commented
> I am a bit confused concerning the led configuration. That's not the most important but just to play a bit...
> I mapped the "internet led" (earth icon) to my wwan LTE modem, the led is named dwr-118-a1:green:wan. Working well.

I check the names at evening.

> For the wireless I have 2 led icons on the modem (one for each 2.4 and 5ghz), but in the source only "phy1:radio" led exists. And I cannot light any wireless led with that. phy1:assoc and and phy1:quality leds do not exist physically nor work to light the leds.
> Any idea?...

5GHz LED is connected directly do MT7610. At this moment it isn't supported by driver.

2018-11-30 08:25 UTC, mkresin requested changes
Looks good as usual. I found only minor stuff. Please ping me if you fixed these and consider the PR as ready to merge.

2018-11-30 12:19 UTC, jej commented
Sorry I cannot help much, I don't understand most of your changes and their consequences... I am openwrt newbie and for now I just discover.
My bandwith is now almost twice what I had with the genuine firmware, incredible... I had to unbrick tonight because the upgrade didn't go well, maybe the process is slow and I rebooted to early. An occasion to try jboot recovery. I confirm it works.
Thanks.

2018-11-30 18:13 UTC, CHKDSK88 commented
> I mapped the "internet led" (earth icon) to my wwan LTE modem, the led is named dwr-118-a1:green:wan.

Earth icon is WAN. I checked in manual. :)

@mkresin 
>Isn't it? 

I can't find it:

```
root@OpenWrt:~# ls /sys/class/leds/
dwr-118-a1:green:internet  dwr-118-a1:green:usb       dwr-118-a1:green:wlan2g    rt2800soc-phy1::quality
dwr-118-a1:green:lan       dwr-118-a1:green:wan       rt2800soc-phy1::assoc      rt2800soc-phy1::radio
```

2018-11-30 18:46 UTC, jej commented
> Earth icon is WAN. I checked in manual. :)

Maybe, but I don't have wired wan, only LTE. So for my setup the "world" is LTE...!

2018-12-03 09:53 UTC, mkresin commented
You are right, there is no led code yet for mt76x0.

2018-12-03 10:17 UTC, CHKDSK88 commented
> You are right, there is no led code yet for mt76x0.

I will make patch when support will be ready.

> Please ping me if you fixed these and consider the PR as ready to merge.

Can You merge?

2018-12-03 14:35 UTC, mkresin commented
merged, thanks!

2018-12-03 14:35 UTC, closed without merging

2019-05-17 15:14 UTC, jej commented
Hi all,
Still confused with these leds... I can manage the wifi led (2.4ghz) with this config:
```
system.@led[2]=led
system.@led[2].name='wifi'
system.@led[2].trigger='netdev'
system.@led[2].mode='link tx rx'
system.@led[2].dev='wlan1'
system.@led[2].default='0'
system.@led[2].sysfs='mt76-phy0'
```
But the led is inverted and I cannot reverse it.
If I use _dwr-118-a1:green:internet_ instead, it works as expected. It's 'on' and 'blinking' when my wireless interface is up, and 'off' when it's down.
If I force _mt76-phy0_ Always off or Always on, it works as expected (not inverted)
Any idea where is the trick?

2019-05-29 08:43 UTC, CHKDSK88 commented
@jej 

My 2.4G LED work as expected with stock config:

````config led 'led_wifi_led'
        option name 'wifi'
        option sysfs 'dwr-118-a1:green:wlan2g'
        option trigger 'netdev'
        option mode 'link tx rx'
        option dev 'wlan1'
````

Only 5G LED is inverted. I will send PR for that problem.