ramips: add support for WINSTARS WS-WN536P3
openwrt/openwrt pull request #15631
Opened 2024-06-05 03:46 UTC by huangsvengood

WS-WN536P3 is a 2.4/5 GHz band 11ac router, based on MT7621DA.

Specification:

- SoC              : MediaTek MT7621DA
- RAM             : DDR3 128 MB
- Flash             : SPI-NOR 16MB
- WLAN           : 2.4/5 GHz 2T2R (MediaTek MT7603e/MT7613)
- Ethernet        : 5x 10/100/1000 Mbps
- LEDs              : 1x Sys 1x WIFI 5x Ethernet LEDs(connect to switch)
- Keys               : 1x Reset 1x WPS 1x Tubro
- USB                : x1
- UART              : 1xUART
- settings          : 115200n8

How to upgrade image in uboot

1. press reset button when boot for 5sec.
2. access 192.168.10.1 in web ui.
3. select image and upload

Product Link:
https://www.winstars.com/en_us/product/WS_WN536P3.html

2024-06-05 05:17 UTC, namiltd requested changes

2024-06-05 05:17 UTC, namiltd commented on target/linux/ramips/dts/mt7621_winstars_ws-wn536p3.dts
> +			color = <LED_COLOR_ID_BLUE>;
Add:
```
function = LED_FUNCTION_WLAN
```
Remove label if you use color/function

2024-06-05 05:18 UTC, namiltd commented on target/linux/ramips/dts/mt7621_winstars_ws-wn536p3.dts
> +			label = "blue:system";
Remove label if you use color/function

2024-06-05 06:28 UTC, huangsvengood commented on target/linux/ramips/dts/mt7621_winstars_ws-wn536p3.dts
> +			label = "blue:system";
Hi @namiltd  help to check again

2024-06-05 14:40 UTC, namiltd commented
Tubro instead of Turbo in PR and commit: - Keys              : 1x Reset 1x WPS 1x Tubro"

2024-06-05 14:52 UTC, huangsvengood commented
> Tubro instead of Turbo in PR and commit: - Keys : 1x Reset 1x WPS 1x Tubro"

Sorry, i have updated it @namiltd

2024-06-05 15:10 UTC, namiltd commented
But you changed turbo to turbo instead of tubro to turbo.

2024-06-05 15:23 UTC, huangsvengood commented
> But you changed turbo to tubro instead of tubro to turbo.

sorry again, updated

2024-06-10 10:43 UTC, namiltd commented on target/linux/ramips/dts/mt7621_winstars_ws-wn536p3.dts
> +
Remove empty line at the end.

2024-06-10 14:43 UTC, DragonBluep commented on target/linux/ramips/dts/mt7621_winstars_ws-wn536p3.dts
> +	mt76@0,0 {
```suggestion
	wifi@0,0 {

```

2024-06-10 14:43 UTC, DragonBluep commented on target/linux/ramips/dts/mt7621_winstars_ws-wn536p3.dts
> +	mt76@0,0 {
```suggestion
	wifi@0,0 {

```

2024-06-10 14:43 UTC, DragonBluep commented on target/linux/ramips/dts/mt7621_winstars_ws-wn536p3.dts
> +		groups = "wdt";
```suggestion
		groups = "i2c", "jtag", "wdt";

```

2024-06-10 14:43 UTC, DragonBluep commented on target/linux/ramips/dts/mt7621_winstars_ws-wn536p3.dts
> +		broken-flash-reset;
`broken-flash-reset;` is useless for 16 MiB Flash.

2024-06-11 10:06 UTC, DragonBluep reviewed
The label MAC address is missing.

2024-06-11 10:06 UTC, DragonBluep commented on target/linux/ramips/image/mt7621.mk
> +  kmod-usb3 -uboot-envtools
Using tab instead of the space here.

2024-06-12 01:09 UTC, DragonBluep approved these changes

2024-06-12 22:32 UTC, ahmedarif193 commented
Hi just tested your commit in WS-WN536E4 as they should have the same dts except for the EC25 4G support (I suppose) after flushing the image i got this :

`CPU:   MediaTek MT7621AT ver 1, eco 3
Clocks: CPU: 880MHz, DDR: 1200MHz, Bus: 220MHz, XTAL: 40MHz
Model: MediaTek MT7621 reference board
DRAM:  128 MiB
Loading Environment from SPI Flash... SF: Detected FM25Q128 with page size 256 Bytes, erase size 64 KiB, total 16 MiB
*** Warning - bad CRC, using default environment
`


later on : 

`
[    1.012431] mt7621-pci 1e140000.pcie: PCI host bridge to bus 0000:00
[    1.018741] pci_bus 0000:00: root bus resource [bus 00-ff]
[    1.024149] pci_bus 0000:00: root bus resource [mem 0x60000000-0x6fffffff]
[    1.031007] pci_bus 0000:00: root bus resource [io  0x0000-0xffff]
[    1.037160] pci 0000:00:00.0: [0e8d:0801] type 01 class 0x060400
[    1.043108] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    1.049333] pci 0000:00:00.0: reg 0x14: [mem 0x00000000-0x0000ffff]
[    1.055581] pci 0000:00:00.0: supports D1
[    1.059517] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    1.066129] pci 0000:00:01.0: [0e8d:0801] type 01 class 0x060400
[    1.072146] pci 0000:00:01.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    1.078325] pci 0000:00:01.0: reg 0x14: [mem 0x00000000-0x0000ffff]
[    1.084643] pci 0000:00:01.0: supports D1
[    1.088608] pci 0000:00:01.0: PME# supported from D0 D1 D3hot
[    1.096200] pci 0000:00:00.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    1.104199] pci 0000:00:01.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    1.112409] pci 0000:01:00.0: [14c3:7603] type 00 class 0x028000
[    1.118363] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff]
[    1.124742] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold
[    1.131149] pci 0000:00:00.0: PCI bridge to [bus 01-ff]
[    1.136307] pci 0000:00:00.0:   bridge window [io  0x0000-0x0fff]
[    1.142389] pci 0000:00:00.0:   bridge window [mem 0x00000000-0x000fffff]
[    1.149108] pci 0000:00:00.0:   bridge window [mem 0x00000000-0x000fffff pref]
[    1.156257] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    1.163115] pci 0000:02:00.0: [14c3:7663] type 00 class 0x000280
[    1.169158] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x000fffff 64bit pref]
[    1.176314] pci 0000:02:00.0: reg 0x18: [mem 0x00000000-0x00003fff 64bit pref]
[    1.183520] pci 0000:02:00.0: reg 0x20: [mem 0x00000000-0x00000fff 64bit pref]
[    1.190792] pci 0000:02:00.0: supports D1 D2
[    1.194969] pci 0000:02:00.0: PME# supported from D0 D1 D2 D3hot D3cold
[    1.201606] pci 0000:02:00.0: 2.000 Gb/s available PCIe bandwidth, limited by 2.5 GT/s PCIe x1 link at 0000:00:01.0 (capable of 4.000 Gb/s with 5.0 GT/s PCIe x1 link)
[    1.216741] pci 0000:00:01.0: PCI bridge to [bus 02-ff]
[    1.221950] pci 0000:00:01.0:   bridge window [io  0x0000-0x0fff]
[    1.227955] pci 0000:00:01.0:   bridge window [mem 0x00000000-0x000fffff]
[    1.234734] pci 0000:00:01.0:   bridge window [mem 0x00000000-0x000fffff pref]
[    1.241902] pci_bus 0000:02: busn_res: [bus 02-ff] end is updated to 02
[    1.248517] pci 0000:00:00.0: BAR 0: no space for [mem size 0x80000000]
[    1.255039] pci 0000:00:00.0: BAR 0: failed to assign [mem size 0x80000000]
[    1.261978] pci 0000:00:01.0: BAR 0: no space for [mem size 0x80000000]
[    1.268549] pci 0000:00:01.0: BAR 0: failed to assign [mem size 0x80000000]
[    1.275435] pci 0000:00:00.0: BAR 8: assigned [mem 0x60000000-0x600fffff]
[    1.282204] pci 0000:00:00.0: BAR 9: assigned [mem 0x60100000-0x601fffff pref]
[    1.289378] pci 0000:00:01.0: BAR 8: assigned [mem 0x60200000-0x602fffff]
[    1.296079] pci 0000:00:01.0: BAR 9: assigned [mem 0x60300000-0x604fffff pref]
[    1.303286] pci 0000:00:00.0: BAR 1: assigned [mem 0x60500000-0x6050ffff]
[    1.310025] pci 0000:00:01.0: BAR 1: assigned [mem 0x60510000-0x6051ffff]
[    1.316730] pci 0000:00:00.0: BAR 7: assigned [io  0x0000-0x0fff]
[    1.322817] pci 0000:00:01.0: BAR 7: assigned [io  0x1000-0x1fff]
[    1.328861] pci 0000:01:00.0: BAR 0: assigned [mem 0x60000000-0x600fffff]
[    1.335568] pci 0000:00:00.0: PCI bridge to [bus 01]
[    1.340522] pci 0000:00:00.0:   bridge window [io  0x0000-0x0fff]
[    1.346537] pci 0000:00:00.0:   bridge window [mem 0x60000000-0x600fffff]
[    1.353314] pci 0000:00:00.0:   bridge window [mem 0x60100000-0x601fffff pref]
[    1.360488] pci 0000:02:00.0: BAR 0: assigned [mem 0x60300000-0x603fffff 64bit pref]
[    1.368147] pci 0000:02:00.0: BAR 2: assigned [mem 0x60400000-0x60403fff 64bit pref]
[    1.375868] pci 0000:02:00.0: BAR 4: assigned [mem 0x60404000-0x60404fff 64bit pref]
[    1.383560] pci 0000:00:01.0: PCI bridge to [bus 02]
[    1.388440] pci 0000:00:01.0:   bridge window [io  0x1000-0x1fff]
[    1.394493] pci 0000:00:01.0:   bridge window [mem 0x60200000-0x602fffff]
[    1.401254] pci 0000:00:01.0:   bridge window [mem 0x60300000-0x604fffff pref]
[    1.410266] Serial: 8250/16550 driver, 3 ports, IRQ sharing disabled
`

and : 

`
[    1.490582] Creating 4 MTD partitions on "spi0.0":
[    1.495383] 0x000000000000-0x000000030000 : "u-boot"
[    1.502115] 0x000000030000-0x000000040000 : "config"
[    1.508250] 0x000000040000-0x000000050000 : "factory"
[    1.514676] OF: Bad cell count for /palmbus@1e000000/spi@b00/flash@0/partitions
[    1.522389] 0x000000050000-0x000001000000 : "firmware"
[    1.528936] 2 uimage-fw partitions found on MTD device firmware
[    1.534874] Creating 2 MTD partitions on "firmware":
[    1.539842] 0x000000000000-0x000000312c8d : "kernel"
[    1.544790] mtd: partition "kernel" doesn't end on an erase/write block -- force read-only
[    1.554276] 0x000000312c8d-0x000000fb0000 : "rootfs"
[    1.559285] mtd: partition "rootfs" doesn't start on an erase/write block boundary -- force read-only
[    1.569589] mtd: setting mtd5 (rootfs) as root device
[    1.574724] 1 squashfs-split partitions found on MTD device rootfs
[    1.580952] 0x000000920000-0x000000fb0000 : "rootfs_data"
`

`
root@OpenWrt:/# cat /proc/mtd 
dev:    size   erasesize  name
mtd0: 00030000 00010000 "u-boot"
mtd1: 00010000 00010000 "config"
mtd2: 00010000 00010000 "factory"
mtd3: 00fb0000 00010000 "firmware"
mtd4: 00312c8d 00010000 "kernel"
mtd5: 00c9d373 00010000 "rootfs"
mtd6: 00690000 00010000 "rootfs_data"
root@OpenWrt:/# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 6.0M      6.0M         0 100% /rom
tmpfs                    58.1M    200.0K     57.9M   0% /tmp
/dev/mtdblock6            6.6M    356.0K      6.2M   5% /overlay
overlayfs:/overlay        6.6M    356.0K      6.2M   5% /
tmpfs                   512.0K         0    512.0K   0% /dev
`

those 3 partitions are not defined in your dts:
mtd4: 00312c8d 00010000 "kernel"
mtd5: 00c9d373 00010000 "rootfs"
mtd6: 00690000 00010000 "rootfs_data"

It appears that the previous prod uses ubifs

2024-06-13 00:55 UTC, huangsvengood commented
> Hi just tested your commit in WS-WN536E4 as they should have the same dts except for the EC25 4G support (I suppose) after flushing the image i got this :
> 
> CPU: MediaTek MT7621AT ver 1, eco 3 Clocks: CPU: 880MHz, DDR: 1200MHz, Bus: 220MHz, XTAL: 40MHz Model: MediaTek MT7621 reference board DRAM: 128 MiB Loading Environment from SPI Flash... SF: Detected FM25Q128 with page size 256 Bytes, erase size 64 KiB, total 16 MiB *** Warning - bad CRC, using default environment
> 
> later on :
> 
> [ 1.012431] mt7621-pci 1e140000.pcie: PCI host bridge to bus 0000:00 [ 1.018741] pci_bus 0000:00: root bus resource [bus 00-ff] [ 1.024149] pci_bus 0000:00: root bus resource [mem 0x60000000-0x6fffffff] [ 1.031007] pci_bus 0000:00: root bus resource [io 0x0000-0xffff] [ 1.037160] pci 0000:00:00.0: [0e8d:0801] type 01 class 0x060400 [ 1.043108] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x7fffffff] [ 1.049333] pci 0000:00:00.0: reg 0x14: [mem 0x00000000-0x0000ffff] [ 1.055581] pci 0000:00:00.0: supports D1 [ 1.059517] pci 0000:00:00.0: PME# supported from D0 D1 D3hot [ 1.066129] pci 0000:00:01.0: [0e8d:0801] type 01 class 0x060400 [ 1.072146] pci 0000:00:01.0: reg 0x10: [mem 0x00000000-0x7fffffff] [ 1.078325] pci 0000:00:01.0: reg 0x14: [mem 0x00000000-0x0000ffff] [ 1.084643] pci 0000:00:01.0: supports D1 [ 1.088608] pci 0000:00:01.0: PME# supported from D0 D1 D3hot [ 1.096200] pci 0000:00:00.0: bridge configuration invalid ([bus 00-00]), reconfiguring [ 1.104199] pci 0000:00:01.0: bridge configuration invalid ([bus 00-00]), reconfiguring [ 1.112409] pci 0000:01:00.0: [14c3:7603] type 00 class 0x028000 [ 1.118363] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff] [ 1.124742] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold [ 1.131149] pci 0000:00:00.0: PCI bridge to [bus 01-ff] [ 1.136307] pci 0000:00:00.0: bridge window [io 0x0000-0x0fff] [ 1.142389] pci 0000:00:00.0: bridge window [mem 0x00000000-0x000fffff] [ 1.149108] pci 0000:00:00.0: bridge window [mem 0x00000000-0x000fffff pref] [ 1.156257] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01 [ 1.163115] pci 0000:02:00.0: [14c3:7663] type 00 class 0x000280 [ 1.169158] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x000fffff 64bit pref] [ 1.176314] pci 0000:02:00.0: reg 0x18: [mem 0x00000000-0x00003fff 64bit pref] [ 1.183520] pci 0000:02:00.0: reg 0x20: [mem 0x00000000-0x00000fff 64bit pref] [ 1.190792] pci 0000:02:00.0: supports D1 D2 [ 1.194969] pci 0000:02:00.0: PME# supported from D0 D1 D2 D3hot D3cold [ 1.201606] pci 0000:02:00.0: 2.000 Gb/s available PCIe bandwidth, limited by 2.5 GT/s PCIe x1 link at 0000:00:01.0 (capable of 4.000 Gb/s with 5.0 GT/s PCIe x1 link) [ 1.216741] pci 0000:00:01.0: PCI bridge to [bus 02-ff] [ 1.221950] pci 0000:00:01.0: bridge window [io 0x0000-0x0fff] [ 1.227955] pci 0000:00:01.0: bridge window [mem 0x00000000-0x000fffff] [ 1.234734] pci 0000:00:01.0: bridge window [mem 0x00000000-0x000fffff pref] [ 1.241902] pci_bus 0000:02: busn_res: [bus 02-ff] end is updated to 02 [ 1.248517] pci 0000:00:00.0: BAR 0: no space for [mem size 0x80000000] [ 1.255039] pci 0000:00:00.0: BAR 0: failed to assign [mem size 0x80000000] [ 1.261978] pci 0000:00:01.0: BAR 0: no space for [mem size 0x80000000] [ 1.268549] pci 0000:00:01.0: BAR 0: failed to assign [mem size 0x80000000] [ 1.275435] pci 0000:00:00.0: BAR 8: assigned [mem 0x60000000-0x600fffff] [ 1.282204] pci 0000:00:00.0: BAR 9: assigned [mem 0x60100000-0x601fffff pref] [ 1.289378] pci 0000:00:01.0: BAR 8: assigned [mem 0x60200000-0x602fffff] [ 1.296079] pci 0000:00:01.0: BAR 9: assigned [mem 0x60300000-0x604fffff pref] [ 1.303286] pci 0000:00:00.0: BAR 1: assigned [mem 0x60500000-0x6050ffff] [ 1.310025] pci 0000:00:01.0: BAR 1: assigned [mem 0x60510000-0x6051ffff] [ 1.316730] pci 0000:00:00.0: BAR 7: assigned [io 0x0000-0x0fff] [ 1.322817] pci 0000:00:01.0: BAR 7: assigned [io 0x1000-0x1fff] [ 1.328861] pci 0000:01:00.0: BAR 0: assigned [mem 0x60000000-0x600fffff] [ 1.335568] pci 0000:00:00.0: PCI bridge to [bus 01] [ 1.340522] pci 0000:00:00.0: bridge window [io 0x0000-0x0fff] [ 1.346537] pci 0000:00:00.0: bridge window [mem 0x60000000-0x600fffff] [ 1.353314] pci 0000:00:00.0: bridge window [mem 0x60100000-0x601fffff pref] [ 1.360488] pci 0000:02:00.0: BAR 0: assigned [mem 0x60300000-0x603fffff 64bit pref] [ 1.368147] pci 0000:02:00.0: BAR 2: assigned [mem 0x60400000-0x60403fff 64bit pref] [ 1.375868] pci 0000:02:00.0: BAR 4: assigned [mem 0x60404000-0x60404fff 64bit pref] [ 1.383560] pci 0000:00:01.0: PCI bridge to [bus 02] [ 1.388440] pci 0000:00:01.0: bridge window [io 0x1000-0x1fff] [ 1.394493] pci 0000:00:01.0: bridge window [mem 0x60200000-0x602fffff] [ 1.401254] pci 0000:00:01.0: bridge window [mem 0x60300000-0x604fffff pref] [ 1.410266] Serial: 8250/16550 driver, 3 ports, IRQ sharing disabled
> 
> and :
> 
> [ 1.490582] Creating 4 MTD partitions on "spi0.0": [ 1.495383] 0x000000000000-0x000000030000 : "u-boot" [ 1.502115] 0x000000030000-0x000000040000 : "config" [ 1.508250] 0x000000040000-0x000000050000 : "factory" [ 1.514676] OF: Bad cell count for /palmbus@1e000000/spi@b00/flash@0/partitions [ 1.522389] 0x000000050000-0x000001000000 : "firmware" [ 1.528936] 2 uimage-fw partitions found on MTD device firmware [ 1.534874] Creating 2 MTD partitions on "firmware": [ 1.539842] 0x000000000000-0x000000312c8d : "kernel" [ 1.544790] mtd: partition "kernel" doesn't end on an erase/write block -- force read-only [ 1.554276] 0x000000312c8d-0x000000fb0000 : "rootfs" [ 1.559285] mtd: partition "rootfs" doesn't start on an erase/write block boundary -- force read-only [ 1.569589] mtd: setting mtd5 (rootfs) as root device [ 1.574724] 1 squashfs-split partitions found on MTD device rootfs [ 1.580952] 0x000000920000-0x000000fb0000 : "rootfs_data" `
> 
> ` root@OpenWrt:/# cat /proc/mtd dev: size erasesize name mtd0: 00030000 00010000 "u-boot" mtd1: 00010000 00010000 "config" mtd2: 00010000 00010000 "factory" mtd3: 00fb0000 00010000 "firmware" mtd4: 00312c8d 00010000 "kernel" mtd5: 00c9d373 00010000 "rootfs" mtd6: [0069000](https://github.com/openwrt/openwrt/commit/00690000b4fc104996f0f1ada3a937e665d2b931) 00010000 "rootfs_data" root@OpenWrt:/# df -h Filesystem Size Used Available Use% Mounted on /dev/root 6.0M 6.0M 0 100% /rom tmpfs 58.1M 200.0K 57.9M 0% /tmp /dev/mtdblock6 6.6M 356.0K 6.2M 5% /overlay overlayfs:/overlay 6.6M 356.0K 6.2M 5% / tmpfs 512.0K 0 512.0K 0% /dev
> 
> those 3 partitions are not defined in your dts: mtd4: 00312c8d 00010000 "kernel" mtd5: 00c9d373 00010000 "rootfs" mtd6: [0069000](https://github.com/openwrt/openwrt/commit/00690000b4fc104996f0f1ada3a937e665d2b931) 00010000 "rootfs_data"
> 
> It appears that the previous production layout uses ubifs, do you have any idea why this is happening?

536P3 is different from 536E4, 536E4 use different flash, So you need to add flash patch first

2024-06-13 09:22 UTC, ahmedarif193 commented
can you point me to that patch  ?

> > Hi just tested your commit in WS-WN536E4 as they should have the same dts except for the EC25 4G support (I suppose) after flushing the image i got this :
> > CPU: MediaTek MT7621AT ver 1, eco 3 Clocks: CPU: 880MHz, DDR: 1200MHz, Bus: 220MHz, XTAL: 40MHz Model: MediaTek MT7621 reference board DRAM: 128 MiB Loading Environment from SPI Flash... SF: Detected FM25Q128 with page size 256 Bytes, erase size 64 KiB, total 16 MiB *** Warning - bad CRC, using default environment
> > later on :
> > [ 1.012431] mt7621-pci 1e140000.pcie: PCI host bridge to bus 0000:00 [ 1.018741] pci_bus 0000:00: root bus resource [bus 00-ff] [ 1.024149] pci_bus 0000:00: root bus resource [mem 0x60000000-0x6fffffff] [ 1.031007] pci_bus 0000:00: root bus resource [io 0x0000-0xffff] [ 1.037160] pci 0000:00:00.0: [0e8d:0801] type 01 class 0x060400 [ 1.043108] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x7fffffff] [ 1.049333] pci 0000:00:00.0: reg 0x14: [mem 0x00000000-0x0000ffff] [ 1.055581] pci 0000:00:00.0: supports D1 [ 1.059517] pci 0000:00:00.0: PME# supported from D0 D1 D3hot [ 1.066129] pci 0000:00:01.0: [0e8d:0801] type 01 class 0x060400 [ 1.072146] pci 0000:00:01.0: reg 0x10: [mem 0x00000000-0x7fffffff] [ 1.078325] pci 0000:00:01.0: reg 0x14: [mem 0x00000000-0x0000ffff] [ 1.084643] pci 0000:00:01.0: supports D1 [ 1.088608] pci 0000:00:01.0: PME# supported from D0 D1 D3hot [ 1.096200] pci 0000:00:00.0: bridge configuration invalid ([bus 00-00]), reconfiguring [ 1.104199] pci 0000:00:01.0: bridge configuration invalid ([bus 00-00]), reconfiguring [ 1.112409] pci 0000:01:00.0: [14c3:7603] type 00 class 0x028000 [ 1.118363] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff] [ 1.124742] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold [ 1.131149] pci 0000:00:00.0: PCI bridge to [bus 01-ff] [ 1.136307] pci 0000:00:00.0: bridge window [io 0x0000-0x0fff] [ 1.142389] pci 0000:00:00.0: bridge window [mem 0x00000000-0x000fffff] [ 1.149108] pci 0000:00:00.0: bridge window [mem 0x00000000-0x000fffff pref] [ 1.156257] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01 [ 1.163115] pci 0000:02:00.0: [14c3:7663] type 00 class 0x000280 [ 1.169158] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x000fffff 64bit pref] [ 1.176314] pci 0000:02:00.0: reg 0x18: [mem 0x00000000-0x00003fff 64bit pref] [ 1.183520] pci 0000:02:00.0: reg 0x20: [mem 0x00000000-0x00000fff 64bit pref] [ 1.190792] pci 0000:02:00.0: supports D1 D2 [ 1.194969] pci 0000:02:00.0: PME# supported from D0 D1 D2 D3hot D3cold [ 1.201606] pci 0000:02:00.0: 2.000 Gb/s available PCIe bandwidth, limited by 2.5 GT/s PCIe x1 link at 0000:00:01.0 (capable of 4.000 Gb/s with 5.0 GT/s PCIe x1 link) [ 1.216741] pci 0000:00:01.0: PCI bridge to [bus 02-ff] [ 1.221950] pci 0000:00:01.0: bridge window [io 0x0000-0x0fff] [ 1.227955] pci 0000:00:01.0: bridge window [mem 0x00000000-0x000fffff] [ 1.234734] pci 0000:00:01.0: bridge window [mem 0x00000000-0x000fffff pref] [ 1.241902] pci_bus 0000:02: busn_res: [bus 02-ff] end is updated to 02 [ 1.248517] pci 0000:00:00.0: BAR 0: no space for [mem size 0x80000000] [ 1.255039] pci 0000:00:00.0: BAR 0: failed to assign [mem size 0x80000000] [ 1.261978] pci 0000:00:01.0: BAR 0: no space for [mem size 0x80000000] [ 1.268549] pci 0000:00:01.0: BAR 0: failed to assign [mem size 0x80000000] [ 1.275435] pci 0000:00:00.0: BAR 8: assigned [mem 0x60000000-0x600fffff] [ 1.282204] pci 0000:00:00.0: BAR 9: assigned [mem 0x60100000-0x601fffff pref] [ 1.289378] pci 0000:00:01.0: BAR 8: assigned [mem 0x60200000-0x602fffff] [ 1.296079] pci 0000:00:01.0: BAR 9: assigned [mem 0x60300000-0x604fffff pref] [ 1.303286] pci 0000:00:00.0: BAR 1: assigned [mem 0x60500000-0x6050ffff] [ 1.310025] pci 0000:00:01.0: BAR 1: assigned [mem 0x60510000-0x6051ffff] [ 1.316730] pci 0000:00:00.0: BAR 7: assigned [io 0x0000-0x0fff] [ 1.322817] pci 0000:00:01.0: BAR 7: assigned [io 0x1000-0x1fff] [ 1.328861] pci 0000:01:00.0: BAR 0: assigned [mem 0x60000000-0x600fffff] [ 1.335568] pci 0000:00:00.0: PCI bridge to [bus 01] [ 1.340522] pci 0000:00:00.0: bridge window [io 0x0000-0x0fff] [ 1.346537] pci 0000:00:00.0: bridge window [mem 0x60000000-0x600fffff] [ 1.353314] pci 0000:00:00.0: bridge window [mem 0x60100000-0x601fffff pref] [ 1.360488] pci 0000:02:00.0: BAR 0: assigned [mem 0x60300000-0x603fffff 64bit pref] [ 1.368147] pci 0000:02:00.0: BAR 2: assigned [mem 0x60400000-0x60403fff 64bit pref] [ 1.375868] pci 0000:02:00.0: BAR 4: assigned [mem 0x60404000-0x60404fff 64bit pref] [ 1.383560] pci 0000:00:01.0: PCI bridge to [bus 02] [ 1.388440] pci 0000:00:01.0: bridge window [io 0x1000-0x1fff] [ 1.394493] pci 0000:00:01.0: bridge window [mem 0x60200000-0x602fffff] [ 1.401254] pci 0000:00:01.0: bridge window [mem 0x60300000-0x604fffff pref] [ 1.410266] Serial: 8250/16550 driver, 3 ports, IRQ sharing disabled
> > and :
> > [ 1.490582] Creating 4 MTD partitions on "spi0.0": [ 1.495383] 0x000000000000-0x000000030000 : "u-boot" [ 1.502115] 0x000000030000-0x000000040000 : "config" [ 1.508250] 0x000000040000-0x000000050000 : "factory" [ 1.514676] OF: Bad cell count for /palmbus@1e000000/spi@b00/flash@0/partitions [ 1.522389] 0x000000050000-0x000001000000 : "firmware" [ 1.528936] 2 uimage-fw partitions found on MTD device firmware [ 1.534874] Creating 2 MTD partitions on "firmware": [ 1.539842] 0x000000000000-0x000000312c8d : "kernel" [ 1.544790] mtd: partition "kernel" doesn't end on an erase/write block -- force read-only [ 1.554276] 0x000000312c8d-0x000000fb0000 : "rootfs" [ 1.559285] mtd: partition "rootfs" doesn't start on an erase/write block boundary -- force read-only [ 1.569589] mtd: setting mtd5 (rootfs) as root device [ 1.574724] 1 squashfs-split partitions found on MTD device rootfs [ 1.580952] 0x000000920000-0x000000fb0000 : "rootfs_data" `
> > ` root@OpenWrt:/# cat /proc/mtd dev: size erasesize name mtd0: 00030000 00010000 "u-boot" mtd1: 00010000 00010000 "config" mtd2: 00010000 00010000 "factory" mtd3: 00fb0000 00010000 "firmware" mtd4: 00312c8d 00010000 "kernel" mtd5: 00c9d373 00010000 "rootfs" mtd6: [0069000](https://github.com/openwrt/openwrt/commit/00690000b4fc104996f0f1ada3a937e665d2b931) 00010000 "rootfs_data" root@OpenWrt:/# df -h Filesystem Size Used Available Use% Mounted on /dev/root 6.0M 6.0M 0 100% /rom tmpfs 58.1M 200.0K 57.9M 0% /tmp /dev/mtdblock6 6.6M 356.0K 6.2M 5% /overlay overlayfs:/overlay 6.6M 356.0K 6.2M 5% / tmpfs 512.0K 0 512.0K 0% /dev
> > those 3 partitions are not defined in your dts: mtd4: 00312c8d 00010000 "kernel" mtd5: 00c9d373 00010000 "rootfs" mtd6: [0069000](https://github.com/openwrt/openwrt/commit/00690000b4fc104996f0f1ada3a937e665d2b931) 00010000 "rootfs_data"
> > It appears that the previous production layout uses ubifs, do you have any idea why this is happening?
> 
> 536P3 is different from 536E4, 536E4 use different flash, So you need to add flash patch first

2024-06-13 11:45 UTC, namiltd commented
@huangsvengood  Please add the logs as an attachment because they are unreadable.

2024-06-13 15:02 UTC, ahmedarif193 commented
> the log seems no problem, and it can boot, but the flash is FM25Q128,can you upload the log

[kboot.log](https://github.com/user-attachments/files/15822461/kboot.log)
Although there is no issue with the pcie, the /proc/mtd displays an incorrect mtd mapping because I used the 536p3 profile

cat /proc/mtd 
dev:    size   erasesize  name
mtd0: 00030000 00010000 "u-boot"
mtd1: 00010000 00010000 "config"
mtd2: 00010000 00010000 "factory"
mtd3: 00fb0000 00010000 "firmware"
mtd4: 003135f9 00010000 "kernel"
mtd5: 00c9ca07 00010000 "rootfs"
mtd6: 002f0000 00010000 "rootfs_data"

2024-06-13 15:07 UTC, huangsvengood commented
that's right, the sizeof firmware partition is fb0000, it is 16MB=128Mbit FLASH

2024-06-13 20:06 UTC, ahmedarif193 commented
> > Hi just tested your commit in WS-WN536E4 as they should have the same dts except for the EC25 4G support (I suppose) after flushing the image i got this :
> > CPU: MediaTek MT7621AT ver 1, eco 3 Clocks: CPU: 880MHz, DDR: 1200MHz, Bus: 220MHz, XTAL: 40MHz Model: MediaTek MT7621 reference board DRAM: 128 MiB Loading Environment from SPI Flash... SF: Detected FM25Q128 with page size 256 Bytes, erase size 64 KiB, total 16 MiB *** Warning - bad CRC, using default environment
> > later on :
> > [ 1.012431] mt7621-pci 1e140000.pcie: PCI host bridge to bus 0000:00 [ 1.018741] pci_bus 0000:00: root bus resource [bus 00-ff] [ 1.024149] pci_bus 0000:00: root bus resource [mem 0x60000000-0x6fffffff] [ 1.031007] pci_bus 0000:00: root bus resource [io 0x0000-0xffff] [ 1.037160] pci 0000:00:00.0: [0e8d:0801] type 01 class 0x060400 [ 1.043108] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x7fffffff] [ 1.049333] pci 0000:00:00.0: reg 0x14: [mem 0x00000000-0x0000ffff] [ 1.055581] pci 0000:00:00.0: supports D1 [ 1.059517] pci 0000:00:00.0: PME# supported from D0 D1 D3hot [ 1.066129] pci 0000:00:01.0: [0e8d:0801] type 01 class 0x060400 [ 1.072146] pci 0000:00:01.0: reg 0x10: [mem 0x00000000-0x7fffffff] [ 1.078325] pci 0000:00:01.0: reg 0x14: [mem 0x00000000-0x0000ffff] [ 1.084643] pci 0000:00:01.0: supports D1 [ 1.088608] pci 0000:00:01.0: PME# supported from D0 D1 D3hot [ 1.096200] pci 0000:00:00.0: bridge configuration invalid ([bus 00-00]), reconfiguring [ 1.104199] pci 0000:00:01.0: bridge configuration invalid ([bus 00-00]), reconfiguring [ 1.112409] pci 0000:01:00.0: [14c3:7603] type 00 class 0x028000 [ 1.118363] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff] [ 1.124742] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold [ 1.131149] pci 0000:00:00.0: PCI bridge to [bus 01-ff] [ 1.136307] pci 0000:00:00.0: bridge window [io 0x0000-0x0fff] [ 1.142389] pci 0000:00:00.0: bridge window [mem 0x00000000-0x000fffff] [ 1.149108] pci 0000:00:00.0: bridge window [mem 0x00000000-0x000fffff pref] [ 1.156257] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01 [ 1.163115] pci 0000:02:00.0: [14c3:7663] type 00 class 0x000280 [ 1.169158] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x000fffff 64bit pref] [ 1.176314] pci 0000:02:00.0: reg 0x18: [mem 0x00000000-0x00003fff 64bit pref] [ 1.183520] pci 0000:02:00.0: reg 0x20: [mem 0x00000000-0x00000fff 64bit pref] [ 1.190792] pci 0000:02:00.0: supports D1 D2 [ 1.194969] pci 0000:02:00.0: PME# supported from D0 D1 D2 D3hot D3cold [ 1.201606] pci 0000:02:00.0: 2.000 Gb/s available PCIe bandwidth, limited by 2.5 GT/s PCIe x1 link at 0000:00:01.0 (capable of 4.000 Gb/s with 5.0 GT/s PCIe x1 link) [ 1.216741] pci 0000:00:01.0: PCI bridge to [bus 02-ff] [ 1.221950] pci 0000:00:01.0: bridge window [io 0x0000-0x0fff] [ 1.227955] pci 0000:00:01.0: bridge window [mem 0x00000000-0x000fffff] [ 1.234734] pci 0000:00:01.0: bridge window [mem 0x00000000-0x000fffff pref] [ 1.241902] pci_bus 0000:02: busn_res: [bus 02-ff] end is updated to 02 [ 1.248517] pci 0000:00:00.0: BAR 0: no space for [mem size 0x80000000] [ 1.255039] pci 0000:00:00.0: BAR 0: failed to assign [mem size 0x80000000] [ 1.261978] pci 0000:00:01.0: BAR 0: no space for [mem size 0x80000000] [ 1.268549] pci 0000:00:01.0: BAR 0: failed to assign [mem size 0x80000000] [ 1.275435] pci 0000:00:00.0: BAR 8: assigned [mem 0x60000000-0x600fffff] [ 1.282204] pci 0000:00:00.0: BAR 9: assigned [mem 0x60100000-0x601fffff pref] [ 1.289378] pci 0000:00:01.0: BAR 8: assigned [mem 0x60200000-0x602fffff] [ 1.296079] pci 0000:00:01.0: BAR 9: assigned [mem 0x60300000-0x604fffff pref] [ 1.303286] pci 0000:00:00.0: BAR 1: assigned [mem 0x60500000-0x6050ffff] [ 1.310025] pci 0000:00:01.0: BAR 1: assigned [mem 0x60510000-0x6051ffff] [ 1.316730] pci 0000:00:00.0: BAR 7: assigned [io 0x0000-0x0fff] [ 1.322817] pci 0000:00:01.0: BAR 7: assigned [io 0x1000-0x1fff] [ 1.328861] pci 0000:01:00.0: BAR 0: assigned [mem 0x60000000-0x600fffff] [ 1.335568] pci 0000:00:00.0: PCI bridge to [bus 01] [ 1.340522] pci 0000:00:00.0: bridge window [io 0x0000-0x0fff] [ 1.346537] pci 0000:00:00.0: bridge window [mem 0x60000000-0x600fffff] [ 1.353314] pci 0000:00:00.0: bridge window [mem 0x60100000-0x601fffff pref] [ 1.360488] pci 0000:02:00.0: BAR 0: assigned [mem 0x60300000-0x603fffff 64bit pref] [ 1.368147] pci 0000:02:00.0: BAR 2: assigned [mem 0x60400000-0x60403fff 64bit pref] [ 1.375868] pci 0000:02:00.0: BAR 4: assigned [mem 0x60404000-0x60404fff 64bit pref] [ 1.383560] pci 0000:00:01.0: PCI bridge to [bus 02] [ 1.388440] pci 0000:00:01.0: bridge window [io 0x1000-0x1fff] [ 1.394493] pci 0000:00:01.0: bridge window [mem 0x60200000-0x602fffff] [ 1.401254] pci 0000:00:01.0: bridge window [mem 0x60300000-0x604fffff pref] [ 1.410266] Serial: 8250/16550 driver, 3 ports, IRQ sharing disabled
> > and :
> > [ 1.490582] Creating 4 MTD partitions on "spi0.0": [ 1.495383] 0x000000000000-0x000000030000 : "u-boot" [ 1.502115] 0x000000030000-0x000000040000 : "config" [ 1.508250] 0x000000040000-0x000000050000 : "factory" [ 1.514676] OF: Bad cell count for /palmbus@1e000000/spi@b00/flash@0/partitions [ 1.522389] 0x000000050000-0x000001000000 : "firmware" [ 1.528936] 2 uimage-fw partitions found on MTD device firmware [ 1.534874] Creating 2 MTD partitions on "firmware": [ 1.539842] 0x000000000000-0x000000312c8d : "kernel" [ 1.544790] mtd: partition "kernel" doesn't end on an erase/write block -- force read-only [ 1.554276] 0x000000312c8d-0x000000fb0000 : "rootfs" [ 1.559285] mtd: partition "rootfs" doesn't start on an erase/write block boundary -- force read-only [ 1.569589] mtd: setting mtd5 (rootfs) as root device [ 1.574724] 1 squashfs-split partitions found on MTD device rootfs [ 1.580952] 0x000000920000-0x000000fb0000 : "rootfs_data" `
> > ` root@OpenWrt:/# cat /proc/mtd dev: size erasesize name mtd0: 00030000 00010000 "u-boot" mtd1: 00010000 00010000 "config" mtd2: 00010000 00010000 "factory" mtd3: 00fb0000 00010000 "firmware" mtd4: 00312c8d 00010000 "kernel" mtd5: 00c9d373 00010000 "rootfs" mtd6: [0069000](https://github.com/openwrt/openwrt/commit/00690000b4fc104996f0f1ada3a937e665d2b931) 00010000 "rootfs_data" root@OpenWrt:/# df -h Filesystem Size Used Available Use% Mounted on /dev/root 6.0M 6.0M 0 100% /rom tmpfs 58.1M 200.0K 57.9M 0% /tmp /dev/mtdblock6 6.6M 356.0K 6.2M 5% /overlay overlayfs:/overlay 6.6M 356.0K 6.2M 5% / tmpfs 512.0K 0 512.0K 0% /dev
> > those 3 partitions are not defined in your dts: mtd4: 00312c8d 00010000 "kernel" mtd5: 00c9d373 00010000 "rootfs" mtd6: [0069000](https://github.com/openwrt/openwrt/commit/00690000b4fc104996f0f1ada3a937e665d2b931) 00010000 "rootfs_data"
> > It appears that the previous production layout uses ubifs, do you have any idea why this is happening?
> 
> 536P3 is different from 536E4, 536E4 use different flash, So you need to add flash patch first

Which patch you were referring to?

2024-06-14 01:33 UTC, ahmedarif193 commented
@huangsvengood Yes, it's the auto-split from the mtd driver that looks at the dts to figure out how to split the mtd partition labeled "firmware." The remaining space gets tagged as rootfs_data. Then, fstool comes in later and mounts it as overlayfs. What bothers me are the traces about bad cell allocation issues. These can come from RW errors or the dts erase/size addresses, but I don't think it's an RW issue because I just received the board 2 days ago

2024-06-16 21:44 UTC, merged