[23.05] Backport some fixes from master to 23.05 branch
openwrt/openwrt pull request #15836
Opened 2024-06-30 10:23 UTC by lukasz1992

- Backport some mac80211 fixes
- Backport well-tested eip93 crypto engine for ramips (can increase image size!)

2024-07-04 19:49 UTC, hauke commented
Please rebase this on top of #15827. I plan to merge #15827 soon and it probably contains multiple of your mac80211 fixes already. 
Pleas remove the merge commit from this PR.

2024-07-07 16:42 UTC, hauke commented on package/kernel/mac80211/patches/subsys/332-wifi-mac80211-check-clear-fast-rx-for-non-4addr-sta-.patch
> +Subject: [PATCH] wifi: mac80211: check/clear fast rx for non-4addr sta VLAN
This patch was added in #15827

2024-07-07 16:48 UTC, hauke commented on package/kernel/mac80211/patches/subsys/331-wifi-mac80211-only-call-drv_sta_rc_update-for-upload.patch
> + stations
This patch was added in #15827

2024-07-07 16:52 UTC, hauke commented on package/kernel/mac80211/patches/subsys/337-mac80211-fix-sband-iftype-data-lookup-for-AP_VLAN.patch
> +Subject: [PATCH] mac80211: fix sband iftype data lookup for AP_VLAN
This patch was added in #15827

2024-07-07 20:01 UTC, rany2 commented
P.S. when you cherry-pick, use `git cherry-pick -x` as it would add a nice `(cherry picked from commit <hash>)` to your message. I think it's a requirement for all backport commits.

2024-07-07 20:03 UTC, hauke commented
> Edit: actually not sure if #15898 supersedes this PR, maybe @hauke should comment?

I took some of the commits added here which I think should get backported into #15898

2024-07-07 20:15 UTC, lukasz1992 commented
@hauke updated PR; excluded patches present here: https://github.com/openwrt/openwrt/pull/15898

2024-07-07 20:23 UTC, rany2 requested changes

2024-07-07 20:23 UTC, rany2 commented on target/linux/mediatek/patches-5.15/965-v6.10-net-ethernet-mtk_eth_soc-ppe-add-support-for-multipl.patch
You need to backport https://github.com/openwrt/openwrt/commit/8ef4d785829241e3a6f95c896de210fd5d3f073b as well if you want to add the `"generic: 6.6: (re-)add support multiple PPE to mtk_eth_soc"` patch, but personally I'd avoid that patch entirely for now given that it broke previously.

2024-07-08 07:14 UTC, lukasz1992 commented on target/linux/mediatek/patches-5.15/965-v6.10-net-ethernet-mtk_eth_soc-ppe-add-support-for-multipl.patch
There is no "break;" in mtk_eth_soc.c code in 5.15 version, patch also does not apply.
It looks like the regression appeared later than 5.15 with 23.05-SNAPSHOT patches.

@hauke what is your opinion on adding support for multiple PPE - keep it or remove?

2024-07-08 07:16 UTC, lukasz1992 commented
> P.S. when you cherry-pick, use `git cherry-pick -x` as it would add a nice `(cherry picked from commit <hash>)` to your message. I think it's a requirement for all backport commits.
> 
> Edit: actually not sure if #15898 supersedes this PR, maybe @hauke should comment?

I will try to update it today evening, thanks

2024-07-08 10:44 UTC, rmilecki commented
After rebasing, your commit 0b92ea21a5d0 ("`hostapd: don't ignore probe-requests with invalid DSSS params`") seems to be just adding some unneeded lines. You can probably drop it.

2024-07-08 11:16 UTC, rany2 commented on target/linux/mediatek/patches-5.15/965-v6.10-net-ethernet-mtk_eth_soc-ppe-add-support-for-multipl.patch
> There is no "break;" in mtk_eth_soc.c code in 5.15 version, patch also does not apply.

There is, it's at line 159 in your patch

2024-07-08 13:06 UTC, lukasz1992 commented on target/linux/mediatek/patches-5.15/965-v6.10-net-ethernet-mtk_eth_soc-ppe-add-support-for-multipl.patch
You are right, thanks! I will fix it today

2024-07-08 13:07 UTC, lukasz1992 commented
> After rebasing, your commit [0b92ea2](https://github.com/openwrt/openwrt/commit/0b92ea21a5d001155e26f808b06765dbba77d7cc) ("`hostapd: don't ignore probe-requests with invalid DSSS params`") seems to be just adding some unneeded lines. You can probably drop it.

I do not know what happened on github, but if you preview the file - it is actually complete:
https://github.com/openwrt/openwrt/blob/0b92ea21a5d001155e26f808b06765dbba77d7cc/package/network/services/hostapd/patches/762-AP-don-t-ignore-probe-requests-with-invalid-DSSS-par.patch

2024-07-08 13:19 UTC, rany2 commented
> > After rebasing, your commit [0b92ea2](https://github.com/openwrt/openwrt/commit/0b92ea21a5d001155e26f808b06765dbba77d7cc) ("`hostapd: don't ignore probe-requests with invalid DSSS params`") seems to be just adding some unneeded lines. You can probably drop it.
> 
> I do not know what happened on github, but if you preview the file - it is actually complete: https://github.com/openwrt/openwrt/blob/0b92ea21a5d001155e26f808b06765dbba77d7cc/package/network/services/hostapd/patches/762-AP-don-t-ignore-probe-requests-with-invalid-DSSS-par.patch

GitHub is right, the patch is already included in the 23.05 branch: https://github.com/openwrt/openwrt/blob/openwrt-23.05/package/network/services/hostapd/patches/762-AP-don-t-ignore-probe-requests-with-invalid-DSSS-par.patch

2024-07-08 23:11 UTC, hauke commented on package/kernel/mac80211/patches/subsys/317-mac80211-fix-mesh-id-corruption-on-32-bit-systems.patch
> +Fixes: 15ddba5f4311 ("wifi: mac80211: consistently use u64 for BSS changes")
I think we do not ship `wifi: mac80211: consistently use u64 for BSS changes`. Is this patch really needed?

2024-07-08 23:14 UTC, hauke commented on package/kernel/mac80211/patches/subsys/351-mac80211-fix-sband-iftype-data-lookup-for-AP_VLAN.patch
> ++		iftype = NL80211_IFTYPE_AP;
This patch is already included upstream: https://github.com/gregkh/linux/commit/521860ddf31414a58f2dcd41f04b790603db8c8b

2024-07-09 09:20 UTC, rmilecki commented
@dangowrt a kind request to look at those backports

2024-07-09 10:39 UTC, rany2 commented
Did you intentionally drop 8ef4d785829241e3a6f95c896de210fd5d3f073b ?

2024-07-09 12:00 UTC, dangowrt commented
Support for features mostly needed on MT7988 doesn't make much sense for 23.05, as we anyway only support the reference board. Hence please drop patches adding support for multiple PPE, it's a too big change for a stable release to happen on short notice and without much testing imho.

Patches which make sense backporting are:
 * net: ethernet: mtk_eth_soc: handle dma buffer size soc specific
 * net: ethernet: mtk_eth_soc: implement .{get,set}_pauseparam ethtool ops
 * net: ethernet: mtk_ppe: Change PPE entries number to 16K

2024-07-09 12:37 UTC, lukasz1992 commented
@dangowrt updated; @rany2 In that case dropping it

2024-07-09 12:42 UTC, rmilecki commented
Thanks you @dangowrt & @lukasz1992, I'm looking at this right now

2024-07-09 13:16 UTC, rany2 commented
Nitpicking but all kernel-related commits except [generic: mtk_eth_soc: add support for flow-control settings](https://github.com/openwrt/openwrt/pull/15836/commits/7998fc562b26a303b858c155219d3e8a4c31c373) (7998fc562b26a303b858c155219d3e8a4c31c373) should be in `backport-5.15` not `patches-5.15`.

Also [generic: mtk_eth_soc: add support for flow-control settings](https://github.com/openwrt/openwrt/pull/15836/commits/7998fc562b26a303b858c155219d3e8a4c31c373) (7998fc562b26a303b858c155219d3e8a4c31c373) should come before [generic: mtk_eth_soc: import accepted patches](https://github.com/openwrt/openwrt/pull/15836/commits/8462a71d194b86fc10817f40d8ec406550022699) (8462a71d194b86fc10817f40d8ec406550022699) so moving to `backport-5.15` works.

2024-07-09 22:14 UTC, hauke commented on package/kernel/mac80211/patches/subsys/317-mac80211-fix-mesh-id-corruption-on-32-bit-systems.patch
> +Fixes: 15ddba5f4311 ("wifi: mac80211: consistently use u64 for BSS changes")
Thanks for the link. We should backport this patch.

2024-07-10 12:12 UTC, rmilecki commented
I backported `net: ethernet: mtk_eth_soc: handle dma buffer size soc specific` on my own, hopefully the right way. It was terribly annoying as patches were getting mangled.

2024-07-10 13:17 UTC, rmilecki commented
Plus the other two `mtk_eth_soc` patches now.

2024-07-10 16:39 UTC, lukasz1992 commented
So dropping the rest of patches.

2024-07-10 21:38 UTC, merged