[2305]:ath79:DIR-825-B1 Fix LAN and WAN MAC addresses
openwrt/openwrt pull request #15917
Opened 2024-07-10 05:06 UTC by Lucky1openwrt

revert setting back to the same as it's sister device that still works ar7161_trendnet_tew-673gru.dts
snapshot MAC addresses work this is just to get this branch to work

basically reverting this commit has not worked since then https://github.com/openwrt/openwrt/commit/de3d60b982c7b8e1821b90b312db57287e74ede3

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

2024-07-10 13:32 UTC, rmilecki requested changes
I'd really expect and explanation why do we need to revert it.

Also if it's basically a revert, then maybe you could use `git revert`?

2024-07-10 13:44 UTC, Lucky1openwrt commented
well as the wan and lan mac addresses are just random at the moment & have been at lest since 25.03.0
it would be nice not having to manually set them each time I erase settings
I don't know how at the moment to revert I will have to look it up 11:43PM atm so tomorrow

2024-07-11 03:34 UTC, Lucky1openwrt commented
@rmilecki 
I think this is what you ment

2024-07-15 05:09 UTC, rmilecki commented
I was mostly wondering why does it happen.

Did you try cherry picking commit daaa0c1b2504 ("`ath79: replace "mac-address-ascii" with "mac-base"`") instead of reverting this change?

2024-07-15 05:25 UTC, Lucky1openwrt commented
that commit in not part of V23.05
the main snapshots MAC addresses works so nothing to change there 
* the wan port didn't operate atm but  it's MAC address was correct 

the addresses are ok on both wifi bands and so most of it works
just for this version seems easer to revet as I don't know why it's not
but it's twin with less leds is still working so lets just make it the same

2024-07-15 05:31 UTC, rmilecki commented
> that commit in not part of V23.05

I assume you mean commit daaa0c1b2504 ("`ath79: replace "mac-address-ascii" with "mac-base"`"). I know it's not part of `openwrt-23.05` (it wasn't backported yet).
There is some chance it fixes your problem. So I asked you to cherry pick it (`git cherry-pick -x daaa0c1b2504`) instead of reverting another commit and see if that helps with reported problem.

I wasn't talking about doing any `master` / `main` changes.

2024-07-15 05:35 UTC, Lucky1openwrt commented
I did manually edit the .dst with a few options & it just made it worse "lost the wifi MAC's well "
but I can specificity test that if you would like

2024-07-15 08:00 UTC, rmilecki commented
Obsoleted by commit 9276bb1cf590 ("`ath79: replace "mac-address-ascii" with "mac-base"`").

Thank you for testing!

2024-07-15 08:00 UTC, closed without merging

2024-07-15 08:02 UTC, Lucky1openwrt commented
thanks :)