uClibc++: Support quoted argument pass-through
openwrt/openwrt pull request #1620
Opened 2018-12-10 21:11 UTC by jbenden

This patch permits the pass-through of command-line arguments which contain spaces and quotes.

This patch was created due to a problem reported here:
- https://gist.github.com/neheb/5f4ddcfa370952808dca4842f5bd3dc5
- https://github.com/openwrt/packages/pull/7616

Signed-off-by: Joseph Benden <joe@benden.us>

2018-12-11 21:54 UTC, neheb commented
It needs a release version bump in the Makefile.

2018-12-16 17:34 UTC, neheb commented
I tested this. Two comments from IRC.

line 8 seems unnecessary. I tested this and found no difference in compilation.
The exec to eval change changes behavior. However after testing, it only works with eval. Any reason for this?

Btw, package size of aircrack-ng goes from 716323 to 381849 on ar71xx when adjusted.

2018-12-17 02:42 UTC, cshoredaniel commented
eval does a second expansion pass on whatever is passed.  So e.g. eval "$test" is 'eval <contents of test>' .. if test is $t2 then the result would be whatever t2=.  exec only does the first pass expansion.

2018-12-26 19:21 UTC, neheb commented
I have a commit in my tree that backports several C++ fixes. Is it possible to upstream this? Maybe git-send-email to rep.dot.nop@gmail.com as all the commits past 0.2.4 have been done by him.

Note that this would require a slight modification for upstream as they changed around their build system.

2019-03-21 09:12 UTC, ynezz requested changes
> Is it possible to upstream this?

Yes, please try to upstream this first and then backport the accepted patch or wait for a new release. We would like to stay close to the upstream as possible, thanks!

2019-03-21 17:02 UTC, neheb commented
@ynezz note the date. Also note that I have a patch on patchwork that switches a bunch of the local patches to upstream backports. Nobody's applying it.

2019-03-22 02:03 UTC, ynezz commented
> note the date. 

I don't know what do you mean exactly, this PR is "just" about 3 months 

> Also note that I have a patch on patchwork that switches a bunch of the local patches to upstream backports. 

Since the last uclibc++ release was made ~7 years ago, it seems to me, that it would be easier to just use directly the Git repository instead of the dated release tarball. The Git repository seems to contain only fixes anyway.

> Nobody's applying it.

Yeah, day has only 48 hours, musl libc eats the cake.

2019-03-22 02:12 UTC, jbenden commented
I'm in process of submitting this fix upstream.

2019-03-22 16:56 UTC, jbenden commented
http://lists.busybox.net/pipermail/uclibc/2019-March/049272.html

2019-04-06 16:20 UTC, jbenden commented
https://cxx.uclibc.org/src/ChangeLog-0.2.4_0.2.5

2019-04-06 16:20 UTC, closed without merging