ath79: add support for KuWfi WB 5G08 / YunCore WB 5G08
openwrt/openwrt pull request #16242
Opened 2024-08-23 16:18 UTC by grosjo

Short specification:

- QCA9563+9886
- 2x 10/100 Mbps Ethernet, passive PoE support
- 128 MB of RAM (DDR2)
- 16 MB of FLASH
- 2T2R 2.4 GHz with external PA, up to 24 dBm (123mW)
- 2x internal 14 dBi antennas
- 8x LED, 1x button
- No UART on PCB on some versions
- Display panel with 2x buttons (F/N) not supported (and not relevant in OpenWrt)-

Flash instructions

Connect PC with 192.168.0.141 to WAN port
Install a TFTP server on your PC ('atftp' is doing the job for instance)
Copy your firmware in the TFTP folder as upgrade.bin
Power up device pushing the 'reset' button
The device shall upload upgrade.bin, install it and reboot
Device shall be booting on 192.168.1.1 as default
Signed-off-by: Joan Moreau <jom@grosjo.net>

2024-08-23 18:37 UTC, obsy requested changes

2024-08-23 18:37 UTC, obsy commented on target/linux/ath79/generic/base-files/etc/board.d/01_leds
> +	;;
Missing leds in dts?

2024-08-23 20:09 UTC, neheb commented on target/linux/ath79/dts/qca9563_yuncore_wb5g08.dts
> +	wifi@0,0 {
dtc would warn here about missing regs.

2024-08-23 20:10 UTC, neheb commented on target/linux/ath79/dts/qca9563_yuncore_wb5g08.dts
> +		led_system: system {
use LED macros instead of label.

2024-08-23 20:12 UTC, neheb commented on target/linux/ath79/dts/qca9563_yuncore_wb5g08.dts
> +			linux,default-trigger = "phy1tpt";
how is this phy1 when there's no wmac?

2024-08-28 04:06 UTC, Neustradamus commented
To follow this PR

2024-11-09 04:09 UTC, Neustradamus commented
@grosjo: Any progress on your PR?

2024-11-09 09:40 UTC, grosjo commented
> @grosjo: Any progress on your PR?

@Neustradamus waiting for incoming new devices to verify the leds settings on the original firmware

2024-12-13 14:56 UTC, Neustradamus commented
@grosjo: Have you received new one?

2024-12-14 00:45 UTC, grosjo commented
not yet

2024-12-15 13:59 UTC, grosjo commented
Moved to #17281

2024-12-15 13:59 UTC, closed without merging