ramips: add TP-Link TL-WR802N-v4 support
openwrt/openwrt pull request #1653
Opened 2018-12-18 10:36 UTC by majo-icutech

This patch adds support for the TP-Link TL-WR802N-v4.
https://openwrt.org/toh/tp-link/tl-wr802n

Specification:
- MT7628N (580 MHz)
- 64 MB RAM
- 8 MB FLASH
- 2T2R 2.4 GHz
- 1x 10/100 Mbps Ethernet
- 1x LED

Flash instruction:

The only way to flash the image in TL-WR802N v4 is to use
tftp recovery mode in U-Boot:

1. Configure PC with static IP 192.168.0.225/24 and tftp server.
2. Rename "openwrt-ramips-mt76x8-tplink_tl-wr802n-v4-squashfs-tftp-recovery.bin"
   to "tp_recovery.bin" and place it in tftp server directory.
3. Connect PC with the LAN port, press the reset button, power up
   the router and keep button pressed for around 10 seconds, until
   device starts downloading the file.
4. Router will download file from server, write it to flash and reboot.

2018-12-28 09:13 UTC, mkresin requested changes
Please use ```git commit --amend``` to add changes to your commit. Use ```git push --force``` to overwrite your github repository/branch. The PR will afterwards update automatically. Please don't close this PR and open a new one.

2018-12-28 09:13 UTC, mkresin commented on target/linux/ramips/dts/TL-WR802NV4.dts
> +			ralink,group = "p0led_an", "p2led_an", "perst";
Has to be `ralink,group = "refclk", "wdt";`.

Check https://www.kresin.me/files/pinmux_review_ramips.ods for details

2018-12-28 09:15 UTC, mkresin requested changes

2018-12-28 09:15 UTC, mkresin commented on target/linux/ramips/dts/TL-WR802NV4.dts
> +	gpio-keys-polled {
"keys" is enough. (And recommended by the [DeviceTree spec](https://github.com/devicetree-org/devicetree-specification/blob/master/source/devicetree-basics.rst#generic-names-recommendation)])

2018-12-28 09:15 UTC, mkresin commented on target/linux/ramips/dts/TL-WR802NV4.dts
> +	gpio-leds {
"leds" is enough. (And recommended by the [DeviceTree spec](https://github.com/devicetree-org/devicetree-specification/blob/master/source/devicetree-basics.rst#generic-names-recommendation)])

2019-02-28 10:36 UTC, chunkeey commented
Merged. Thanks.

2019-02-28 10:36 UTC, closed without merging