ath79: ubnt-m-xw and ubnt-bullet-m-xw improvements
openwrt/openwrt pull request #1658
Opened 2018-12-19 23:12 UTC by ynezz

This is part of my previous pull request [`ath79: Add support for Ubiquiti Nanostation M (XW)`](https://github.com/openwrt/openwrt/pull/1632) which I've closed since we first need to properly fix the MAC/MDIO reset in the `ath79/ag71xx` in order to proceed with adding support for Nanostation M (XW), but this is going to take some time, so I've now taken out patches which are making `ubnt-m-xw` and `ubnt-bullet-m-xw` DTS files cleaner and add LED aliases for diag.sh support which is currently missing.

2018-12-20 07:02 UTC, 981213 requested changes
two things inline :)

2018-12-20 07:02 UTC, 981213 commented on target/linux/ath79/dts/ar9342_ubnt_xw.dtsi
> +&mdio1 {
mdio1 is a subdevice of eth1 so it isn't enabled if eth1 is disabled. This isn't needed.

2018-12-20 07:02 UTC, 981213 commented on target/linux/ath79/dts/ar9342_ubnt_xw.dtsi
> +&eth1 {
eth1 is disabled by default. (see ath79.dtsi)

2018-12-20 11:02 UTC, ynezz commented
@981213 Thanks for the review, indeed I've just removed it, tested it and it works as you've suggested.

2018-12-27 15:34 UTC, chunkeey commented
Merged. Thanks.

2018-12-27 15:35 UTC, closed without merging