mikrotik: mtdsplit_minor: return 0 if not fatal, and accept filename "bootimage"
openwrt/openwrt pull request #16780
Opened 2024-10-25 01:21 UTC by john-tho

Adjust mtdsplit_minor so that it only returns an error if something fatal happens. This is required for Linux 6.7+: https://github.com/torvalds/linux/commit/5c2f7727d437

Secondly, accept the YAFFS filename `bootimage`.
This is the (Linux OpenWrt) kernel change needed for RouterBOOTv7 NOR `bootimage` to work, otherwise mtdsplit_minor will not partition to the rootfs.
With this inplace, building a RouterBOOTv7 NOR compatible image is just packing the file, which can be done later in ImageBuilder, once a process has been tidied and finalised.

@f00b4r0 @kempniu @robimarko 

---

Background:
mtdsplit_minor does very minimal checks at the start of the kernel partition to test that these bytes match what is expected for a Mikrotik NOR device with an OpenWrt kernel written to it (YAFFS filesystem with `kernel` filename in the first YAFFS object block). If successful, it then uses the OpenWrt downstream kernel function [`mtd_find_rootfs_from`](https://github.com/openwrt/openwrt/blob/27657050d02f13d1e737293ac7ad08686b4c6fd3/target/linux/generic/files/drivers/mtd/mtdsplit/mtdsplit.c#L108) to walk through the NOR to find the OpenWrt rootfs magic.

RouterBOOT v7 on NOR devices no longer works with YAFFS `kernel` ELF boot. Analysis of OEM firmware on NOR found that an NPK (fairly well known Mikrotik image format) is instead copied to `bootimage` filename on YAFFS. This file is very similar to the Mikrotik (Downloads) main (upgrade) package, with some changes to the squashfs container on NOR.

An existing NPK library (https://github.com/botlabsDev/npkpy) was modified and used to test and help trial and error which parts of the NOR NPK mattered to boot a kernel, and what the minimum NPK looked like.
(Long time ago, and very rough notes, I believe this was) kernel sits ZLIB encoded within the NPK file container block. This need to detail `boot` folder, `boot/kernel` (our kernel ELF) file, and `UPGRADED` file, but there must be a squashfs block to a 0x1000 byte boundary beforehand.
Could confirm through decompiling RouterBOOT, or additional trial and error.

A rough proof of concept was put together using this tool: https://github.com/john-tho/npkpy/blob/create-npk/tools/demo_pack_kernel/poc_pack_kernel.py, integrated to OpenWrt: https://github.com/john-tho/openwrt/pull/7, but it needs more work before it could be used in the OpenWrt build system (ideally someone build a simple tool specifically to pack OpenWrt kernel to NPK).

2024-10-28 13:07 UTC, f00b4r0 requested changes
Thanks for taking care of this! LMGTM.
Pending this very minor formatting nit, this is `Acked-by: Thibaut VARENE <hacks@slashdirt.org>`.

2024-10-28 13:07 UTC, f00b4r0 commented on target/linux/generic/files/drivers/mtd/mtdsplit/mtdsplit_minor.c
> +					sizeof(YAFFS_NAME_BOOTIMAGE)))) {
a very minor nit: the wrapping seems a little excessive to me, the kernel has deprecated 80-col wrapping some 4 years ago now :) and I would also align the checks differently to highlight that both `memcmp()` happen at the same logical level.

So I'd write this like so:
```
        if ((memcmp(hdr.yaffs_name, YAFFS_NAME_KERNEL, sizeof(YAFFS_NAME_KERNEL))) &&
            (memcmp(hdr.yaffs_name, YAFFS_NAME_BOOTIMAGE, sizeof(YAFFS_NAME_BOOTIMAGE)))) {
```

That aside, this LGTM

2024-10-29 07:48 UTC, f00b4r0 approved these changes
All good thanks, as mentioned you can add my Acked-by :)

2024-10-30 10:15 UTC, merged

2024-10-30 10:15 UTC, robimarko commented
Thanks! Rebased on top of main and merged!