ramips add support for GeHua GHL-R-001
openwrt/openwrt pull request #1682
Opened 2018-12-27 06:07 UTC by dengqf6

This PR depends on #1681 

Specs
- 	SoC: MT7621AT
- 	RAM: 512MiB
- 	Flash: 32MiB SPI NOR
- 	2.4G: MT7603EN
- 	5G: MT7612EN
- 	Ethernet: 4x GE ports (1x WAN, 3x LAN) with link status LEDs
- 	USB 3.0
- 	LEDs: POWER, 5G WIFI, 2.4G WIFI, USB, Internet.
	The last two ones are controlled by GPIO
- 	UART: There are 2 UARTs (UARTLITE1/ttyS0 and UARTLITE3/ttyS1) on board.
	UARTLITE1 is close to LEDs, and UARTLITE3 is close to flash chip.
	The stock u-boot uses UARTLITE1 by default. Baud rate is 57600

Flash instruction
1. `telnet 192.168.9.1 2317`, username is "root" and password is "admin"
One can alternatively use UART to log in
2. Put OpenWrt firmware in a FAT32 USB drive, and connect it to the router
One can alternatively download the firmware via `wget` through Internet
3. `mtd write /path/to/openwrt.bin firmware`
4. reboot

2018-12-28 11:48 UTC, rmilecki commented on target/linux/ramips/dts/GHL-R-001.dts
> +/dts-v1/;
Please include licensing info for your DTS file, see
https://openwrt.org/submitting-patches#dts_checklist
e.g. a line like:
```
// SPDX-License-Identifier: GPL-2.0-or-later OR MIT
```
above the /dts-v1/;

2018-12-28 11:54 UTC, mkresin requested changes
Please use ```git commit --amend``` to add changes to your commit. Use ```git push --force``` to overwrite your github repository/branch. The PR will afterwards update automatically. Please don't close this PR and open a new one.

2018-12-28 11:54 UTC, mkresin commented on target/linux/ramips/dts/GHL-R-001.dts
> +	gpio-leds {
"leds" is enough. (And recommended by the [DeviceTree spec](https://github.com/devicetree-org/devicetree-specification/blob/master/source/devicetree-basics.rst#generic-names-recommendation)])

2018-12-28 11:54 UTC, mkresin commented on target/linux/ramips/dts/GHL-R-001.dts
> +	gpio-keys-polled {
"keys" is enough. (And recommended by the [DeviceTree spec](https://github.com/devicetree-org/devicetree-specification/blob/master/source/devicetree-basics.rst#generic-names-recommendation)])

2018-12-28 11:54 UTC, mkresin commented on target/linux/ramips/dts/GHL-R-001.dts
> +	m25p80@0 {
flash@ please. (And recommended by the [DeviceTree spec](https://github.com/devicetree-org/devicetree-specification/blob/master/source/devicetree-basics.rst#generic-names-recommendation)])

2018-12-28 11:54 UTC, mkresin commented on target/linux/ramips/dts/GHL-R-001.dts
> +			ralink,group = "wdt";
You need to switch the jtag group to gpio as well.

Check https://www.kresin.me/files/pinmux_review_ramips.ods for details.

2018-12-28 14:17 UTC, dengqf6 commented
Corrected

2018-12-29 15:04 UTC, mkresin commented
merged, thanks!

2018-12-29 15:04 UTC, closed without merging

2019-08-15 16:08 UTC, adrianschmutzler commented
Hi, I'm currently reviewing the MAC address assignment on ramips target.
For your device, you are currently using MAC address from <&factory 0xe000> and then just calculate WAN address by adding +1 to that.
However, there might be another MAC address stored on flash for your device in <&factory 0xe006>.

Can you check that? If yes, I would also be interested in which of the two addresses should be "lan" and which "wan" then ...