Add support for Devolo Repeater ac
openwrt/openwrt pull request #16956
Opened 2024-11-14 17:30 UTC by hmmmonteiro

Add support for Devolo Repeater ac.

Based on existing netgear ex3700 and Edimax EW-7476RPC.

2025-01-01 02:47 UTC, Djfe commented
what is the actual model name of this device? (MT-Number)
Devolo gives each device their own MT:xxxx number

2025-01-01 13:23 UTC, hauke commented on target/linux/ramips/mt7620/base-files/etc/board.d/02_network
> +  devolo,acr|\
Please fix the whitespace problems. 
More files are affected.

2025-01-01 13:39 UTC, hauke commented on target/linux/ramips/dts/mt7620a_devolo_acr.dtsi
> +	};
Please convert the nvram format, see 3f8ed239a64ec63eeb883bd8b0b603f011d40f59 as an example.

2025-01-01 13:40 UTC, hauke commented on target/linux/ramips/dts/mt7620a_devolo_acr.dts
Why do you add this as a separate file? 

If you plan to use this only in one dts file, please integrate it into the main dts file.

2025-01-01 13:41 UTC, hauke commented
Please fix the problems shown by the Test Formalities, see https://github.com/openwrt/openwrt/actions/runs/12077042624/job/33729247280?pr=16956

2025-01-30 08:37 UTC, hmmmonteiro commented on target/linux/ramips/dts/mt7620a_devolo_acr.dtsi
> +	};
Hello hauke, i believe I've addressed the issues you reported, with the last commits. Please let me know if there's anything missing. 
Thanks.

2025-02-02 14:32 UTC, mali7618 approved these changes

2025-03-16 01:59 UTC, DragonBluep requested changes
As a good start, please squash all commits first.

2025-03-16 01:59 UTC, DragonBluep commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +		compatible = "mx25l6405d","jedec,spi-nor";
```suggestion
		compatible = "jedec,spi-nor";
```

2025-03-16 01:59 UTC, DragonBluep commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +
Keep only one newline between two nodes.

2025-03-16 01:59 UTC, DragonBluep commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +	phy-reset-duration = <30>;
I guess it won't work. `ethernet` is not a ethernet-phy dev.

2025-03-16 01:59 UTC, DragonBluep commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +	wifi@0,0 {
```suggestion
	wifi@0,0 {
		compatible = "mediatek,mt76";
```

2025-03-16 01:59 UTC, DragonBluep commented on target/linux/ramips/image/mt7620.mk
> +  DEVICE_PACKAGES := kmod-mt76x2 kmod-mt76x2e kmod-phy-realtek
```suggestion
  DEVICE_PACKAGES := kmod-mt76x2 kmod-phy-realtek
```

2025-03-19 11:48 UTC, DragonBluep reviewed
Please add installation instruction to the commit message.

2025-03-19 11:48 UTC, DragonBluep commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +/* This file is released into the public domain */
Please use a license instead. `// SPDX-License-Identifier: GPL-2.0-or-later OR MIT`

2025-03-19 11:48 UTC, DragonBluep commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +	status = "okay";
We don't use gpio1 group. This node can be removed.

2025-03-19 11:48 UTC, DragonBluep commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +			label = "LED 2";
The LED name should be in the format of "$color:$function".

2025-03-19 11:48 UTC, DragonBluep commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +	nvmem-cell-names = "eeprom", "mac-address";
It can be simplified to
```
	nvmem-cells = <&eeprom_factory_0>;
	nvmem-cell-names = "eeprom";
```
The offset factory@4 is the default value for this mac address.

2025-03-19 11:48 UTC, DragonBluep commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +		mediatek,mtd-eeprom = <&eeprom_factory_8000>;
```suggestion
```

2025-03-19 11:48 UTC, DragonBluep commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +
Only keep one empty line in the end.

2025-03-19 11:48 UTC, DragonBluep commented on target/linux/ramips/image/mt7620.mk
> +  DEVICE_MODEL := rac
Change it to `WiFi Repeater ac` to match the model name in device-tree.

2025-03-19 11:48 UTC, DragonBluep commented on target/linux/ramips/image/mt7620.mk
> +  SUPPORTED_DEVICES += devolo-rac
This line is unneeded because it is a new supported device.
```suggestion
```

2025-03-19 11:48 UTC, DragonBluep commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +	pinctrl-0 = <&rgmii1_pins &mdio_pins>;
This port config seems incorrect since this model only has one eth port. Try if this configuration works:
```
&ethernet {
	pinctrl-names = "default";
	pinctrl-0 = <&rgmii1_pins>, <&mdio_pins>;

	nvmem-cells = <&macaddr_factory_4 0>;
	nvmem-cell-names = "mac-address";

	mediatek,portmap = "llllw";

	port@5 {
		status = "okay";
		phy-handle = <&phy5>;
		phy-mode = "rgmii";
	};

	mdio-bus {
		status = "okay";

		phy5: ethernet-phy@5 {
			reg = <5>;
			phy-mode = "rgmii";
		};
	};
};
```
Try remove `gsw` node, too.

2025-03-23 01:34 UTC, hmmmonteiro commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +	pinctrl-0 = <&rgmii1_pins &mdio_pins>;
Didn't work. Tried a few definitions and ended up committing the "short" working version.

2025-03-31 02:03 UTC, DragonBluep commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +	pinctrl-0 = <&rgmii1_pins &mdio_pins>;
Please attach the bootlog.

2025-03-31 02:03 UTC, DragonBluep commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +	pinctrl-0 = <&rgmii1_pins &mdio_pins>;
Please attach the bootlog.

2025-03-31 09:30 UTC, hmmmonteiro commented on target/linux/ramips/dts/mt7620a_devolo_rac.dts
> +	pinctrl-0 = <&rgmii1_pins &mdio_pins>;
`[    0.000000] Linux version 6.6.83 (hm@FCT-PC0795) (mipsel-openwrt-linux-musl-gcc (OpenWrt GCC 13.3.0 r29070+2-8d1fe32c2c) 13.3.0, GNU ld (GNU Binutils) 2.42) #0 Sun Mar 23 17:55:01 2025
[    0.000000] Board has DDR2
[    0.000000] Analog PMU set to hw control
[    0.000000] Digital PMU set to hw control
[    0.000000] SoC Type: MediaTek MT7620A ver:2 eco:6
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019650 (MIPS 24KEc)
[    0.000000] MIPS: machine is devolo WiFi Repeater ac
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Kernel command line: console=ttyS0,57600 rootfstype=squashfs,jffs2
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.000000] Writing ErrCtl register=000247f0
[    0.000000] Readback ErrCtl register=000247f0
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 16240
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 55100K/65536K available (6218K kernel code, 612K rwdata, 1432K rodata, 1200K init, 231K bss, 10436K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 256
[    0.000000] CPU Clock: 580MHz
[    0.000000] clocksource: systick: mask: 0xffff max_cycles: 0xffff, max_idle_ns: 583261500 ns
[    0.000000] systick: enable autosleep mode
[    0.000000] systick: running - mult: 214748, shift: 32
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 6590553264 ns
[    0.000002] sched_clock: 32 bits at 290MHz, resolution 3ns, wraps every 7405115902ns
[    0.015548] Calibrating delay loop... 385.84 BogoMIPS (lpj=1929216)
[    0.087762] pid_max: default: 32768 minimum: 301
[    0.109619] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.124048] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.150824] RCU Tasks Trace: Setting shift to 0 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=1.
[    0.176660] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.196165] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.212950] pinctrl core: initialized pinctrl subsystem
[    0.227183] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.243438] /pinctrl: Fixed dependency cycle(s) with /pinctrl/pinctrl0
[    0.528182] PCI host bridge to bus 0000:00
[    0.536198] pci_bus 0000:00: root bus resource [mem 0x20000000-0x2fffffff]
[    0.549924] pci_bus 0000:00: root bus resource [io  0x10160000-0x1016ffff]
[    0.563540] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    0.579346] pci 0000:00:00.0: [1814:0801] type 01 class 0x060400
[    0.591246] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    0.603696] pci 0000:00:00.0: reg 0x14: [mem 0x20200000-0x2020ffff]
[    0.616238] pci 0000:00:00.0: supports D1
[    0.624109] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    0.638234] pci 0000:01:00.0: [14c3:7662] type 00 class 0x028000
[    0.650138] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff 64bit]
[    0.663601] pci 0000:01:00.0: reg 0x30: [mem 0x00000000-0x0000ffff pref]
[    0.677003] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold
[    0.689365] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    0.702421] pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 01
[    0.715577] pci 0000:00:00.0: BAR 0: no space for [mem size 0x80000000]
[    0.728705] pci 0000:00:00.0: BAR 0: failed to assign [mem size 0x80000000]
[    0.742553] pci 0000:00:00.0: BAR 8: assigned [mem 0x20000000-0x200fffff]
[    0.756050] pci 0000:00:00.0: BAR 9: assigned [mem 0x20100000-0x201fffff pref]
[    0.770416] pci 0000:00:00.0: BAR 1: assigned [mem 0x20200000-0x2020ffff]
[    0.783926] pci 0000:01:00.0: BAR 0: assigned [mem 0x20000000-0x200fffff 64bit]
[    0.798467] pci 0000:01:00.0: BAR 6: assigned [mem 0x20100000-0x2010ffff pref]
[    0.812819] pci 0000:00:00.0: PCI bridge to [bus 01]
[    0.822676] pci 0000:00:00.0:   bridge window [mem 0x20000000-0x200fffff]
[    0.836183] pci 0000:00:00.0:   bridge window [mem 0x20100000-0x201fffff pref]
[    0.852326] clocksource: Switched to clocksource systick
[    0.876659] NET: Registered PF_INET protocol family
[    0.886607] IP idents hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.901960] tcp_listen_portaddr_hash hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.918717] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.934054] TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.949293] TCP bind hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.963331] TCP: Hash tables configured (established 1024 bind 1024)
[    0.976828] MPTCP token hash table entries: 512 (order: 0, 6144 bytes, linear)
[    0.991463] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    1.004386] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    1.019088] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    1.030361] PCI: CLS 0 bytes, default 32
[    1.038389] rt-timer 10000100.timer: maximum frequency is 1220Hz
[    1.057854] workingset: timestamp_bits=14 max_order=14 bucket_order=0
[    1.072547] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    1.084045] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    1.110015] Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled
[    1.124540] printk: console [ttyS0] disabled
[    1.133616] 10000c00.uartlite: ttyS0 at MMIO 0x10000c00 (irq = 20, base_baud = 2500000) is a Palmchip BK-3103
[    1.153346] printk: console [ttyS0] enabled
[    1.169857] printk: bootconsole [early0] disabled
[    1.208785] spi spi0.0: force spi mode3
[    1.217146] spi-nor spi0.0: mx25l6405d (8192 Kbytes)
[    1.227229] 4 fixed-partitions partitions found on MTD device spi0.0
[    1.239971] OF: Bad cell count for /palmbus@10000000/spi@b00/flash@0/partitions
[    1.254580] OF: Bad cell count for /palmbus@10000000/spi@b00/flash@0/partitions
[    1.269457] Creating 4 MTD partitions on "spi0.0":
[    1.279047] 0x000000000000-0x000000030000 : "u-boot"
[    1.293086] 0x000000030000-0x000000040000 : "u-boot-env"
[    1.306484] 0x000000040000-0x000000050000 : "factory"
[    1.319386] OF: Bad cell count for /palmbus@10000000/spi@b00/flash@0/partitions
[    1.334414] 0x000000050000-0x000000800000 : "firmware"
[    1.348066] 2 uimage-fw partitions found on MTD device firmware
[    1.359966] Creating 2 MTD partitions on "firmware":
[    1.369866] 0x000000000000-0x00000027e122 : "kernel"
[    1.379768] mtd: partition "kernel" doesn't end on an erase/write block -- force read-only
[    1.398960] 0x00000027e122-0x0000007b0000 : "rootfs"
[    1.408954] mtd: partition "rootfs" doesn't start on an erase/write block boundary -- force read-only
[    1.429805] mtd: setting mtd5 (rootfs) as root device
[    1.440125] 1 squashfs-split partitions found on MTD device rootfs
[    1.452480] 0x000000650000-0x0000007b0000 : "rootfs_data"
[    1.498687] gsw: ephy base address: 8
[    1.507409] gsw: setting port4 to ephy mode
[    1.51606 [...]

2025-04-17 05:20 UTC, mali7618 approved these changes

2025-04-22 20:08 UTC, merged