ramips: add support for Netgear R6020
openwrt/openwrt pull request #1706
Opened 2019-01-01 18:47 UTC by crdotson

This patch adds support for the Netgear R6020, aka Netgear AC750.
The code is identical to the R6120 except for the identifier.

Hardware specification:
- SoC: MediaTek MT7628 (580 MHz)
- Flash: 16 MiB
- RAM: 64 MiB
- Wireless: 2.4Ghz(builtin) and 5Ghz (MT7612E)
- LAN speed: 10/100
- LAN ports: 4
- WAN speed: 10/100
- WAN ports: 1
- Serial baud rate of Bootloader and factory firmware: 57600

To flash use nmrpflash with the provided factory.img.

Signed-off-by: Chris Dotson <chris@dotson97.org>

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

2019-01-01 20:04 UTC, ynezz commented on target/linux/ramips/dts/R6020.dts
> +/dts-v1/;
From https://openwrt.org/submitting-patches#dts_checklist
> 1. Don't forget to add proper license, consider adding `SPDX-License-Identifier: GPL-2.0-or-later OR MIT`

2019-01-01 20:06 UTC, ynezz commented on target/linux/ramips/dts/R6020.dts
> +	gpio-keys-polled {
From https://openwrt.org/submitting-patches#dts_checklist

> 5. The name of a node should reflect the function of the device and not its model. Examples for generic node names can be found in Section 2.2.2 Generic Names Recommendation

Can you please change the node name to `keys` ?

2019-01-01 20:06 UTC, ynezz commented on target/linux/ramips/dts/R6020.dts
> +	gpio-leds {
From https://openwrt.org/submitting-patches#dts_checklist

> 5. The name of a node should reflect the function of the device and not its model. Examples for generic node names can be found in Section 2.2.2 Generic Names Recommendation

Can you please change the node name to `leds` ?

2019-01-01 20:31 UTC, ynezz commented on target/linux/ramips/image/mt76x8.mk
> +TARGET_DEVICES += netgear_r6020
And looking now at the DTS files for 6020 and 6120, the only difference I can see is in LED names and model names. So you need to create DTSI include file(`git grep dtsi` for examples) with common bits for both boards (everything but the LEDs) and then include this common DTSI file in DTS board file.

2019-01-02 04:53 UTC, dengqf6 commented
Are you sure that it uses the same 5GHz chip as R6120? MT7612E is ac 2x2, i.e. 867Mbps
Possibly MT7610E

2019-01-02 04:56 UTC, crdotson commented
How can I tell?  I’m running the build and it works although the 5ghz signal is pretty weak. Thanks!

2019-01-02 05:02 UTC, dengqf6 commented
By checking PCI ID or the content of factory partition

2019-03-21 10:58 UTC, ynezz commented on target/linux/ramips/base-files/etc/board.d/01_leds
> +	ucidef_set_led_wlan "wlan5g" "WiFi 5GHz" "$boardname:green:wlan5g" "phy1tpt"
@crdotson Drop the wlan2g/wlan5g lines and use `linux,default-trigger = "phy0tpt";` and `linux,default-trigger = "phy1tpt";` in your LED nodes instead. Configuration of LEDs in DTS is preferred. Example:

https://github.com/openwrt/openwrt/blob/e65f935de9e67ea07a251f114455f12e9555c5bf/target/linux/ath79/dts/ar9344_comfast_cf-e120a-v3.dts#L36-L40

2019-03-21 10:59 UTC, ynezz requested changes
@crdotson Are you going to address the requested changes and move forward with this PR?

2019-04-15 22:51 UTC, ynezz commented
Please re-open the PR once you find a time (or interest) to work on this.

2019-04-15 22:51 UTC, closed without merging

2019-04-17 17:59 UTC, crdotson commented
Very sorry, I have been slammed with my day job. I will re-open and make the requested changes. Thank you!