realtek: add support for Hasivo S1100W-8XGT-SE switch
openwrt/openwrt pull request #17137
Opened 2024-12-01 15:30 UTC by andrewjlamarche

This commit adds support for Hasivo S1100W-8XGT-SE switch.

Device specification
--------------------
SoC Type:	RTL9303
RAM:		Samsung K4B461646E-BYKO (512MB)
Flash:		Fudan FM25Q128A (16 MB)
Ethernet:	8x 10G via 2x RTL8264 PHY
LEDs:		2 LEDs, 1 power green, 1 system green
Button:		Reset
USB ports:	None
Bootloader:	Realtek U-Boot - U-Boot 2011.12.(3.6.6.55087) (Nov 13 2022 - 14:37:31)

Root access via serial
----------------------
1. ctrl+t
2. password: switchrtk
3. press 's' for shell

Root access via SSH
-------------------
1. ctrl+t
2. password: switchrtk
3. sys command sh
4. log in with your username+password
5. ctrl+t
6. password: switchrtk
7. press 's' for shell

Credit to https://forum.openwrt.org/t/hasivo-switches/151758/174 for rooting instructions.

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://openwrt.org/submitting-patches

Please remove this message before posting the pull request.

2025-04-02 20:29 UTC, andrewjlamarche commented
I was able to bring up the 10G PHYs with a small patch to the RTL8264B driver now included in OpenWrt. However, they only negotiate up to 5G and I'm seeing `received packet on lanX with own address as source address`.

I'm also not sure how to configure the PHY LEDs, I havent found documentation for the `realtek,rtl9300-leds` driver.

2025-04-04 22:33 UTC, janh commented
> I'm also not sure how to configure the PHY LEDs, I havent found documentation for the `realtek,rtl9300-leds` driver.

The LED sets just define the values for the `LED_SET*_*_CTRL` registers. Each 16-bit value in a set corresponds to one LED. A definition of the bits is available here: https://svanheule.net/realtek/longan/register/led_set0_0_ctrl

I guess for this switch you'll only need a single LED set, as all ports are identical and use the same configuration.

You could also try to read the register values using the original firmware. If you have access to the Realtek `diag` console, `register get 0xcc28 1` should return the value of the `LED_SET0_0_CTRL` register. Alternatively, `md.l bb00cc28` from U-Boot should give the same result (after `rtk network on` of course).

2025-04-05 00:51 UTC, andrewjlamarche commented
Excellent tip on the LED config! That worked.

So the only part now is getting the PHYs working. They're labeled `RTL8264`, no `B`, and the PHY ID is `0x001CCAF2`.
![](https://forum.openwrt.org/uploads/default/optimized/3X/7/f/7f9ed8479d93aab0c6b9014ad2bfd04d80f8e70b_2_1332x1000.jpeg)

The patch I used is attached, but it caused the issue mentioned above with 5G max negotiated rate and the source address problem. Any ideas for this one? I haven't found _any_  docs outside of https://github.com/plappermaul/realtek-doc/blob/main/RTL8261N.pdf.

Cheers!

[s1100w.patch](https://github.com/user-attachments/files/19612172/s1100w.patch)

2025-04-21 16:50 UTC, Neustradamus commented
To follow this PR :)

2025-04-25 17:15 UTC, philrosenthal commented
Would you mind writing up a short description of what is expected to work, known to not work, given the current state of this code, and how you would install this or roll back to factory firmware?

I have a couple of these switches, and would consider running/testing your code.

2025-04-25 18:17 UTC, andrewjlamarche commented
Hi. As if right now, I would not test this. The ethernet ports do not work at all with the current RTL8261N driver available in OpenWrt.

2025-05-20 02:28 UTC, andrewjlamarche commented
@svanheule @musashino205 would you mind taking a look at this PR? With a patch to the RTL8261n driver, I'm able to get ports 2-8 passing traffic locally (haven't tested outbound traffic yet) up to 5G. The phys don't report that they support 10G, likely something is missing in the driver. Port 1 always shows the link is up at 5gbit even with nothing plugged in. I have not been able to figure it out.

2025-05-20 16:45 UTC, andrewjlamarche commented
From the boot log:

```
...
[    1.624459] set sds port 0 to 0
[    1.634865] set sds port 8 to 3
...
```

But in my device tree I have 


```
phy0: ethernet-phy@0 {
    compatible = "ethernet-phy-ieee802.3-c45";
    rtl9300,smi-address = <0 0>;
    reg = <0>;
    sds = <2>;
};
```

Here's the relevant driver code:

```C
for_each_node_by_name(dn, "ethernet-phy") {
    u32 smi_addr[2];

    if (of_property_read_u32(dn, "reg", &pn))
        continue;

    if (pn >= RTMDIO_MAX_PORT) {
        pr_err("%s: illegal port number %d\n", __func__, pn);
        return -ENODEV;
    }

    if (of_property_read_u32(dn, "sds", &bus_priv->sds_id[pn]))
        bus_priv->sds_id[pn] = -1;
    else
        pr_info("set sds port %d to %d\n", pn, bus_priv->sds_id[pn]);
```

So I'm not sure why it is being set to 0 instead of 2, but this is likely why lan1 (port0) is not working.

2025-05-20 17:53 UTC, andrewjlamarche commented
As of now, the only things needing fixing/work are:
* Using [this patch](https://github.com/user-attachments/files/19612172/s1100w.patch) seems to have 10G and 2.5G working, though 1G negotiates at 100M and no traffic passes. Did not test a true 100M/10M device.
* Fan/thermal zones need to be added.
* Install instructions will probably need to tweak bootcmd to also do `rtk network on` before booting.
* Testing full install and upgrade procedures.

2025-05-21 19:59 UTC, andrewjlamarche commented
Fan appears to operate independently via an STC8G1K08. So really the only thing needed is the RTL8264(non B) drivers to make the phys work correctly.

2025-06-09 18:56 UTC, andrewjlamarche commented
Depends: https://github.com/openwrt/openwrt/pull/19081

2025-06-12 03:17 UTC, BrainSlayer commented
you may consider adding support for factory firmware flashing using factory webgui.  its trivial. here a link to a original image. it seems you just need to add the typical uboot magic and version number into the uboot header 

https://drive.google.com/file/d/1M7oQT8akko9SwmwjgALAV3eIk--rKKgo/view

2025-06-12 03:24 UTC, BrainSlayer commented
consider also this. might look better https://github.com/mirror/dd-wrt/commit/326f299fee25c71ca8cf9c2ba9763511a7b7d7b5

2025-06-12 03:50 UTC, BrainSlayer commented
another one

````
Index: rtl9303_hasivo_s1100w-8xgt-se.dts
===================================================================
--- rtl9303_hasivo_s1100w-8xgt-se.dts   (revision 61751)
+++ rtl9303_hasivo_s1100w-8xgt-se.dts   (working copy)
@@ -8,7 +8,7 @@
 #include <dt-bindings/leds/common.h>

 / {
-       compatible = "hasivo,s1100w-8xgt-se", "realtek,rtl838x-soc";
+       compatible = "hasivo,s1100w-8xgt-se", "realtek,rtl930x-soc";
        model = "Hasivo S1100W-8XGT-SE";

        memory@0 {
````

2025-06-12 03:54 UTC, BrainSlayer commented
for the "remaining memory". it was no accident that i wrote "highmem" as description. its really mips highmem per definition since mips has a architecture based memory hole after first 256mb since pci space is  located at this address.

2025-06-12 04:02 UTC, andrewjlamarche commented
Thanks for the feedback! I'll see about working on a factory image soon.

2025-06-12 04:53 UTC, BrainSlayer commented
> Thanks for the feedback! I'll see about working on a factory image soon.

that would be nice. i have integrated your patches in my tree but i'm not able to test if "boota" now with the changes. its just made by guess out from the image i downloaded

2025-06-12 12:19 UTC, andrewjlamarche commented
I will actually have to investigate if a factory image is possible. I had to change the boot command for a specific reason and IIRC that was only possible via serial. I’ll check the default bootargs on the PoE one I have still running stock fw.

2025-06-16 23:50 UTC, andrewjlamarche commented
Also ping @aparcar @plappermaul

2025-06-17 06:31 UTC, plappermaul requested changes

2025-06-17 06:31 UTC, plappermaul commented on target/linux/realtek/dts/rtl9303_hasivo_s1100w-8xgt-se.dts
> +	};
Please align with @jonasjelonek regarding this notation.

2025-06-17 06:31 UTC, plappermaul commented on target/linux/realtek/dts/rtl9303_hasivo_s1100w-8xgt-se.dts
> +			sds = <3>;
This and the follow-up numberings looks strange. It says: Port number 8 (derived from reg) is on smi bus 0 with port number 1. Usually these numbers are aligned. Please check in uboot after "rtk network on" the SMI settings in registers [SMI_PORT...](https://www.svanheule.net/realtek/longan/register/smi_port0_5_addr_ctrl) with

switch# # md 0x1b00cb80

2025-06-17 06:31 UTC, plappermaul commented on target/linux/realtek/rtl930x/config-6.6
> +CONFIG_RTL8261N_PHY=y
Go over to 6.12

2025-06-17 06:31 UTC, plappermaul commented on target/linux/realtek/image/rtl930x.mk
> +TARGET_DEVICES += hasivo_s1100w-8xgt-se
rebase on current master (new models where added).

2025-06-17 13:08 UTC, andrewjlamarche commented on target/linux/realtek/dts/rtl9303_hasivo_s1100w-8xgt-se.dts
> +			sds = <3>;
Interestingly, `md 0x1b00cb80` hung. However, these values were chosen based on the vendor fw bootlog. Here's a snippet.

```
RTK Driver Module Initialize
  MAC probe (unit 0)
    Chip 9303 (found)
  MAC init (unit 0)
  SMI protocol probe (unit 0)
unit=0 port=0 smi=0 C45=1 C22=1
unit=0 port=24 smi=3 C45=1 C22=1
  PHY probe (unit 0)
PHY driver probed on unit 0 port 0
PHY driver probed on unit 0 port 8
PHY driver probed on unit 0 port 16
PHY driver probed on unit 0 port 20
PHY driver probed on unit 0 port 24
PHY driver probed on unit 0 port 25
PHY driver probed on unit 0 port 26
PHY driver probed on unit 0 port 27
```

2025-06-17 13:15 UTC, jonasjelonek commented on target/linux/realtek/dts/rtl9303_hasivo_s1100w-8xgt-se.dts
> +			sds = <3>;
You'd need to use `md 0xbb00cb80` which is a valid address within KSEG1 (uncached memory, e.g. for MMIO). `0x1b00cb80` is within MMU-backed virtual address space.

EDIT: FYI 0xA0000000-0xBFFFFFFF is mapped to physical 0x00000000-0x1FFFFFFF

2025-06-17 13:23 UTC, andrewjlamarche commented on target/linux/realtek/dts/rtl9303_hasivo_s1100w-8xgt-se.dts
> +			sds = <3>;
```
bb00cb80: 0a418820 16a484e6 2227b9ac 2f6a8e72    .A. ...."'../j.r               
bb00cb90: 0009ca30 00000000 00f00000 00000000    ...0............               
bb00cba0: 00000000 00000000 00000000 00000000    ................               
bb00cbb0: 001fa435 0107ffe0 0127ffe9 0167ffea    ...5.....'...g..               
bb00cbc0: 00000000 00000000 00000000 00000000    ................               
bb00cbd0: 00000000 00000000 00000000 00000000    ................               
bb00cbe0: 00000000 00000000 00000000 00000000    ................               
bb00cbf0: 00000000 00000000 00000000 00000000    ................               
bb00cc00: 01053659 aaaaaaaa 00aaaaaa 00000000    ..6Y............               
bb00cc10: 00000000 00000000 00000000 00000000    ................               
bb00cc20: 00000000 ffff0bff 02a0020b 00000000    ................               
bb00cc30: 00000000 00000000 00000000 0f110101    ................               
bb00cc40: 0f110101 0f110101 00000000 00000000    ................               
bb00cc50: 00000000 00000000 00000000 00000000    ................               
bb00cc60: 00000000 00000000 00000000 00000000    ................               
bb00cc70: 00000000 00000000 00000000 00000000    ................
```

2025-06-17 15:51 UTC, andrewjlamarche commented on target/linux/realtek/dts/rtl9303_hasivo_s1100w-8xgt-se.dts
> +			sds = <3>;
Also https://forum.openwrt.org/t/hasivo-switches/151758/193?u=andrewjlamarche

I can't remember where I pulled that info from, but that's precisely how I derived the dts here.

2025-07-06 10:36 UTC, aparcar commented
build realtek/rtl930x/hasivo_s1100w-8xgt-se

2025-07-06 14:33 UTC, andrewjlamarche commented
```
root@switch:~# ubus call system board
{
	"kernel": "6.12.33",
	"hostname": "switch",
	"system": "RTL9303",
	"model": "Hasivo S1100W-8XGT-SE",
	"board_name": "hasivo,s1100w-8xgt-se",
	"rootfs_type": "squashfs",
	"release": {
		"distribution": "OpenWrt",
		"version": "SNAPSHOT",
		"firmware_url": "https://downloads.openwrt.org/",
		"revision": "r30109-697a89e445",
		"target": "realtek/rtl930x",
		"description": "OpenWrt SNAPSHOT r30109-697a89e445",
		"builddate": "1750166270"
	}
}
root@switch:~# uptime
 10:33:08 up 18 days, 22:56,  load average: 0.02, 0.01, 0.00
```

Rock stable here still.

2025-07-06 16:53 UTC, aparcar commented
@jonasjelonek do you have this device and can test it?

2025-07-06 17:45 UTC, jonasjelonek commented
> @jonasjelonek do you have this device and can test it?

No, I don't have that one :(

2025-07-06 21:35 UTC, andrewjlamarche commented
@aparcar do you need additional “proof it works”?

2025-07-07 09:15 UTC, aparcar commented
> @aparcar do you need additional “proof it works”?

@andrewjlamarche yes, ideally at least one person is able to reproduce your outcome (i.e. a running router)

Generally I'm not familiar with these parts of OpenWrt so I rely on people like @jonasjelonek @plappermaul and many more to share their opinions. I don't want to slow down the process but try to make sure everyone is happy with the results.

2025-07-07 10:00 UTC, jonasjelonek approved these changes
From my perspective this is fine. As with the TP-Link TL-ST1008F for which I added support, there don't seem to be any visible users apart from @andrewjlamarche which could verify it's working. As long as no one complains this can be merged IMO. 

Content-wise this PR looks good to me, just relies on #19081 but this also seems close to ready-to-be-merged (not an expert on that one though).

2025-07-07 12:43 UTC, BrainSlayer commented
> From my perspective this is fine. As with the TP-Link TL-ST1008F for which I added support, there don't seem to be any visible users apart from @andrewjlamarche which could verify it's working. As long as no one complains this can be merged IMO.
> 
> Content-wise this PR looks good to me, just relies on #19081 but this also seems close to ready-to-be-merged (not an expert on that one though).

thats what i just wanted to put in there. this PR here will not work unless the phy fix is merged 
however. you can do the phy fix in this PR here too. then i will approve it. the phy fix is anyway based on fixed i made in my ddwrt tree. i hate delays

2025-07-09 06:30 UTC, plappermaul approved these changes
Ok for me. If there was one thing to complain then it would be the fact that you did not use the new rt-loader for better compressed images. See https://git.openwrt.org/?p=openwrt%2Fopenwrt.git&a=search&h=HEAD&st=commit&s=rt-loader

2025-07-09 06:30 UTC, plappermaul commented on target/linux/realtek/dts/rtl9303_hasivo_s1100w-8xgt-se.dts
> +			sds = <3>;
Indeed seems sane. The 5 bit fields give:

```
27 -> 19 10011
26 -> 18 10010
25 -> 17 10001
24 -> 16 10000

23 -> 23 10111
22 -> 22 10110
21 -> 21 10101
20 -> 3  00011
19 -> 19 10011
18 -> 18 10010


17 -> 17 10001
16 -> 2  00010
15 -> 15 01111
14 -> 14 01110
13 -> 13 01101
12 -> 12 01100

11 -> 11 01011
10 -> 10 01010
9  -> 9  01001
8  -> 1  00001
7  -> 7  00111
6  -> 6  00110

5  -> 5  00101
4  -> 4  00100
3  -> 3  00011
2  -> 2  00010
1  -> 1  00001
0  -> 0  00000 
```

Can you add a dump from [polling sel](https://www.svanheule.net/realtek/longan/register/smi_port0_15_polling_sel) too? 

`md 0xbb00ca08`

2025-07-09 13:01 UTC, andrewjlamarche commented
```
RTL9300# # md 0xbb00ca08                                                        
bb00ca08: 55550000 00ffaaaa 00000000 00000259    UU.............Y               
bb00ca18: 001fa434 00000194 00000194 00000194    ...4............               
bb00ca28: 00000194 00000194 00000194 00000194    ................               
bb00ca38: 00000194 00000194 00000194 00000194    ................               
bb00ca48: 00000194 00000194 00000194 00000194    ................               
bb00ca58: 00000194 00000194 00000194 00000194    ................               
bb00ca68: 00000194 00000194 00000194 00000194    ................               
bb00ca78: 00000194 00000194 00000194 00000194    ................               
bb00ca88: 00000194 00000194 00000000 00000000    ................               
bb00ca98: 00000000 00000000 00000000 00000000    ................               
bb00caa8: 00000000 00000000 00000000 00000000    ................               
bb00cab8: 00000000 00000000 00000000 00000000    ................               
bb00cac8: 00000000 00000000 00000000 00000000    ................               
bb00cad8: 00000000 00000000 00000000 00000000    ................               
bb00cae8: 00000000 00000000 00000000 00000000    ................               
bb00caf8: 00000000 00000000 00000000 00000000    ................
```

2025-07-09 14:59 UTC, andrewjlamarche commented
> Ok for me. If there was one thing to complain then it would be the fact that you did not use the new rt-loader for better compressed images. See https://git.openwrt.org/?p=openwrt%2Fopenwrt.git&a=search&h=HEAD&st=commit&s=rt-loader

It turns out that the bootloader actually supports lzma by default. I switched to it.

2025-07-13 09:02 UTC, CharlesVelazquez commented
On a scale of 1 to 10, how likely do you think this will naturally work on the poe version of this switch? I have a Hasivo S1100W**P**-8XGT-SE and was contemplating on giving this a try, I'd like to think that the POE version shouldn't differ significantly. But then again, could be my luck this makes the poe parts go crazy during operation.

2025-07-13 09:35 UTC, jonasjelonek commented
@CharlesVelazquez I guess it will just work, except for some PoE functionality probably. I read the STH review [here](https://www.servethehome.com/finally-a-cheap-8-port-10gbase-t-managed-poe-switch-the-hasivo-s1100wp-8xgt-se/) and it looks like both are essentially the same, the PoE variant just having a bigger power supply and an additional PoE board. But the main board is the same.

Not sure if PoE even needs a DTS change and it might already work with the realtek-poe package. But that depends on the actual chip that's on this PoE board.

2025-07-13 15:21 UTC, andrewjlamarche commented
You can always tftpboot the initramfs and see if it works. I have the PoE variant too but haven’t booted this image on it. I’d love to get PoE working, but I don’t think the realtek-poe package would work. I think they use the HS104 chips. 

https://forum.openwrt.org/t/hasivo-switches/151758/27?u=andrewjlamarche

@CharlesVelazquez perhaps you could open yours and take some high-res photos of the PoE chips? Mine is in a closet rack that takes about 2 hours to remove it and then put it back. I think there are 4 screws around the top. One is hidden behind the QA/warranty sticker.

2025-07-15 10:13 UTC, bevanweiss commented
> You can always tftpboot the initramfs and see if it works. I have the PoE variant too but haven’t booted this image on it. I’d love to get PoE working, but I don’t think the realtek-poe package would work. I think they use the HS104 chips.
> 
> https://forum.openwrt.org/t/hasivo-switches/151758/27?u=andrewjlamarche
> 
> @CharlesVelazquez perhaps you could open yours and take some high-res photos of the PoE chips? Mine is in a closet rack that takes about 2 hours to remove it and then put it back. I think there are 4 screws around the top. One is hidden behind the QA/warranty sticker.

There's some information on the HS104 chips here;
https://svanheule.net/switches/software/poe_management#hasivo

And some additional information, inc high res pictures of switch PCBs and chips here:
https://svanheule.net/switches/s1100wp-8gt_se

2025-07-22 18:06 UTC, andrewjlamarche commented
ping @aparcar

2025-07-27 16:36 UTC, hauke commented on target/linux/realtek/dts/rtl9303_hasivo_s1100w-8xgt-se.dts
> +			label = "green:system";
please remove the label when you already have `color` and `function`.

2025-07-27 16:51 UTC, merged

2026-03-18 03:50 UTC, ekartashov commented
I have written a guide on how to flash OpenWrt on this S1100W-8XGT-SE switch, and I think it can definetly be helpful to people because of some details that I missed myself during the procedure :smiley: 

[**Flashing OpenWrt on Hasivo S1100W-8XGT-SE**](https://github.com/ekartashov/hasivo-s1100w-openwrt)

2026-03-18 04:48 UTC, bevanweiss commented
> I have written a guide on how to flash OpenWrt on this S1100W-8XGT-SE switch, and I think it can definetly be helpful to people because of some details that I missed myself during the procedure 😃
> 
> [**Flashing OpenWrt on Hasivo S1100W-8XGT-SE**](https://github.com/ekartashov/hasivo-s1100w-openwrt)

Why go the complicated way of creating a cable to connect to the console port, when you can just buy an incredibly cheap Cisco-compatible rollover cable
https://www.aliexpress.com/item/1005005643854732.html
No chance of a wiring mistake, no need to discuss TX/RX.. just works.

2026-03-18 11:16 UTC, ekartashov commented
@bevanweiss,

Fair, I actually considered the rollover cable, but since I had no prior experience with these cables and everything suggest that this connector could be essentially an internal debug connection, I wasn't confident the engineers followed any particular pinout convention like the Cisco-compatible one. They might have just wired it however was convenient for their test bench or manufacturing pipeline, which could happen I guess.

Since I didn't want to wait 2+ weeks for AliExpress shipping just to potentially discover the wiring was non-standard and have to rewire it anyway and also to get support for RS485 protocol directly (that specific module did have MAX485 onboard), so I went the DIY route.

Turned out to be a bit of overthinking on my part, but the rollover cable is the way to go if you are sure that the pinout that the README.md has is the Cisco-compatible one (I didn't check the Cisco pinout, i just tested the continuity with my multimeter with the cable plugged in and the traces on the PCB).

I will correct it after checking to prevent extra confusion.