mediatek: filogic: Add support for OpenWRT One mikroBUS spidev spi2 with device tree overlay
openwrt/openwrt pull request #17399
Opened 2024-12-27 18:24 UTC by markbirss

This PR is a redo of a previous closed https://github.com/openwrt/openwrt/pull/17244

Use: running Meshtastic (packages are being merged already)

Reason: Change to device-tree overlay

Device: OpenWRT One specifically for the mikroBUS

Purpose: Adds device tree overlay for mikroBUS spidev spi2

Enables V1 libgpiod compatibility in kernel and adds a device tree overlay

CONFIG_GPIO_CDEV_V1 since libgpiod stil uses v1 libgpiod
https://github.com/openwrt/packages/issues/23548#issuecomment-1975082663

Compiled Test: OpenWRT One/master

2024-12-28 08:59 UTC, john-tho commented
> Enables V1 libgpiod compatibility in kernel and adds a device tree overlay
> 
> CONFIG_GPIO_CDEV_V1 since libgpiod stil uses v1 libgpiod [openwrt/packages#23548 (comment)](https://github.com/openwrt/packages/issues/23548#issuecomment-1975082663)

I'm not sure that is still accurate (in Openwrt packages branches master and openwrt-24.10):
Openwrt libgpiod package is now 2.1.3: https://github.com/openwrt/packages/blob/ca9c3d1baea38f0e5cedae7b74cfe8ef15a3ec83/libs/libgpiod/Makefile#L10-L11
and the Kconfig `CONFIG_GPIO_CDEV_V1=y` was removed with the Openwrt libgpiod 2.1.1 bump: https://github.com/openwrt/packages/commit/716eb3e7d311c7bbf930e6fff3eabad42d825ee3#diff-6118a8187647a204cc7e7dd7379f7a3ecb6e2220b1b2c9c12c76dee70e3eecc5L48

2024-12-28 09:27 UTC, markbirss commented
> > Enables V1 libgpiod compatibility in kernel and adds a device tree overlay
> > CONFIG_GPIO_CDEV_V1 since libgpiod stil uses v1 libgpiod [openwrt/packages#23548 (comment)](https://github.com/openwrt/packages/issues/23548#issuecomment-1975082663)
> 
> I'm not sure that is still accurate (in Openwrt packages branches master and openwrt-24.10): Openwrt libgpiod package is now 2.1.3: https://github.com/openwrt/packages/blob/ca9c3d1baea38f0e5cedae7b74cfe8ef15a3ec83/libs/libgpiod/Makefile#L10-L11 and the Kconfig `CONFIG_GPIO_CDEV_V1=y` was removed with the Openwrt libgpiod 2.1.1 bump: [openwrt/packages@716eb3e#diff-6118a8187647a204cc7e7dd7379f7a3ecb6e2220b1b2c9c12c76dee70e3eecc5L48](https://github.com/openwrt/packages/commit/716eb3e7d311c7bbf930e6fff3eabad42d825ee3#diff-6118a8187647a204cc7e7dd7379f7a3ecb6e2220b1b2c9c12c76dee70e3eecc5L48)

Oh ok, thank you for this. I will have a closer look and update my pr, just want to test it

2025-01-20 11:33 UTC, markbirss commented
any developers, kindly review my PR ?

2025-01-22 11:20 UTC, danpawlik commented
I think you should squash commits into one or/and check `Test Formalities` result.

2025-01-23 15:11 UTC, the2masters requested changes
The same comments I added for bpi-r4 apply here.

2025-01-23 15:11 UTC, the2masters commented on target/linux/mediatek/dts/mt7981b-openwrt-one-mikrobus-spidev.dtso
> +        status = "okay";
not required

2025-01-23 15:11 UTC, the2masters commented on target/linux/mediatek/dts/mt7981b-openwrt-one-mikrobus-spidev.dtso
> +                target-path = "/soc/spi@1100b000";
target = <&spi1>;

2025-01-23 15:11 UTC, the2masters commented on target/linux/mediatek/dts/mt7981b-openwrt-one-mikrobus-spidev.dtso
> +                        compatible = "linux,spidev";
maybe silabs,si3210 to get autoload? There are 3 devices in tree which use this hack: D-Link DWR-512 B, GL.iNet GL-B2200, GL.iNet GL-S1300

2025-01-23 15:11 UTC, the2masters commented on target/linux/mediatek/dts/mt7981b-openwrt-one-mikrobus-spidev.dtso
> +                        status = "okay";
not required

2025-01-24 06:19 UTC, markbirss commented on target/linux/mediatek/dts/mt7981b-openwrt-one-mikrobus-spidev.dtso
> +                target-path = "/soc/spi@1100b000";
Will do, this might be spi2

2025-01-24 11:49 UTC, markbirss commented on target/linux/mediatek/dts/mt7981b-openwrt-one-mikrobus-spidev.dtso
> +        status = "okay";
updated, thank you

2025-01-24 11:50 UTC, markbirss commented on target/linux/mediatek/dts/mt7981b-openwrt-one-mikrobus-spidev.dtso
> +                        status = "okay";
updated, thank you

2025-01-24 11:52 UTC, markbirss commented
@the2masters 

Thank you for your assistance for the auto creation of the spidev.

Kindly review the changes

2025-01-24 13:09 UTC, the2masters approved these changes
I cannot test this one, as I don't own an openwrt-one (yet). It looks correct and I tested a similar patch on bpi-r4 (mt7988). I don't know if the spi-max-frequency is correct.

Can you change the headline of the PR to spi1? In the schematic of openwrt-one the spi bus of the mikroBUS connector is called spi1.

2025-01-24 13:19 UTC, markbirss commented
> I cannot test this one, as I don't own an openwrt-one (yet). It looks correct and I tested a similar patch on bpi-r4 (mt7988). I don't know if the spi-max-frequency is correct.
> 
> Can you change the headline of the PR to spi1? In the schematic of openwrt-one the spi bus of the mikroBUS connector is called spi1.


you see the spi devices that are created dont actually match the schematic after booting up...

spidev is created on spidev2.0

tested works fine

```
root@OpenWrt:~# cat /tmp/sysinfo/model 
OpenWrt One
root@OpenWrt:~# dmesg | grep spidev
[    4.176804] FIT:          flat_dt sub-image 0x0059f000..0x0059f1b2 "fdt-mt7981b-openwrt-one-mikrobus-spidev" (ARM64 OpenWrt openwrt_one device tree overlay mt7981b-openwrt-one-mikrobus-spidev) 
root@OpenWrt:~# ls /dev/spidev2.0 
/dev/spidev2.0
root@OpenWrt:~# dmesg | grep spi
[    0.911800] spi-nor spi0.0: w25q128 (16384 Kbytes)
[    0.916917] 4 fixed-partitions partitions found on MTD device spi0.0
[    0.923329] Creating 4 MTD partitions on "spi0.0":
[    0.954220] spi-nand spi1.1: calibration result: 0x3
[    0.959294] spi-nand spi1.1: Winbond SPI NAND was found.
[    0.964618] spi-nand spi1.1: 256 MiB, block size: 128 KiB, page size: 2048, OOB size: 128
[    0.973319] 2 fixed-partitions partitions found on MTD device spi1.1
[    0.979963] Creating 2 MTD partitions on "spi1.1":
[    4.176804] FIT:          flat_dt sub-image 0x0059f000..0x0059f1b2 "fdt-mt7981b-openwrt-one-mikrobus-spidev" (ARM64 OpenWrt openwrt_one device tree overlay mt7981b-openwrt-one-mikrobus-spidev) 
root@OpenWrt:~# 
```

2025-01-24 16:21 UTC, the2masters commented
from your log spi2 (NOR) is detected as spi0.0, spi0 (NAND) is spi1.0 and spi1 is spidev-2.0. If you look at target/linux/mediatek/files-6.6/arch/arm64/boot/dts/mediatek/mt7981.dtsi you will see the spi entries are in this order (spi2, spi0, spi1). The order was correct (spi0, spi1, spi2) until faa7b7dd0a1a663a8583ba48d40c50508690c1d6, in this commit the order was changed to follow kernel rules.

> Order of Nodes[¶](https://www.kernel.org/doc/html/next/devicetree/bindings/dts-coding-style.html#order-of-nodes)
    Nodes on any bus, thus using unit addresses for children, shall be ordered by unit address in ascending order. Alternatively for some subarchitectures, nodes of the same type can be grouped together, e.g. all I2C controllers one after another even if this breaks unit address ordering.

@rmilecki: From the cited text of the dts coding style we can order the spi busses in native order (spi0, spi1, spi2), ignoring the unit address. Would you accept a revert of a part of faa7b7dd0a1a663a8583ba48d40c50508690c1d6 to bring the spi busses back to their correct names? So spi1 from openwrt-one schematic is spi1 in kernel? This would make tinkering with the openwrt-one easier.

2025-01-24 16:34 UTC, KanjiMonster commented
> from your log spi2 (NOR) is detected as spi0.0, spi0 (NAND) is spi1.0 and spi1 is spidev-2.0. If you look at target/linux/mediatek/files-6.6/arch/arm64/boot/dts/mediatek/mt7981.dtsi you will see the spi entries are in this order (spi2, spi0, spi1). The order was correct (spi0, spi1, spi2) until [faa7b7d](https://github.com/openwrt/openwrt/commit/faa7b7dd0a1a663a8583ba48d40c50508690c1d6), in this commit the order was changed to follow kernel rules.
> 
> > Order of Nodes[¶](https://www.kernel.org/doc/html/next/devicetree/bindings/dts-coding-style.html#order-of-nodes)
> > Nodes on any bus, thus using unit addresses for children, shall be ordered by unit address in ascending order. Alternatively for some subarchitectures, nodes of the same type can be grouped together, e.g. all I2C controllers one after another even if this breaks unit address ordering.
> 
> @rmilecki: From the cited text of the dts coding style we can order the spi busses in native order (spi0, spi1, spi2), ignoring the unit address. Would you accept a revert of a part of [faa7b7d](https://github.com/openwrt/openwrt/commit/faa7b7dd0a1a663a8583ba48d40c50508690c1d6) to bring the spi busses back to their correct names? So spi1 from openwrt-one schematic and dts is spi1 in kernel? This would make tinkering with the openwrt-one easier.

SPI supports parsing aliases for static id assignment. S no need to reorder nodes, just use appropriate aliases.

2025-01-24 16:42 UTC, the2masters commented
Like this (untested)? Looks weird :-)
```
diff --git a/target/linux/mediatek/dts/mt7981b-openwrt-one.dts b/target/linux/mediatek/dts/mt7981b-openwrt-one.dts
index 584b482179..8408e31104 100644
--- a/target/linux/mediatek/dts/mt7981b-openwrt-one.dts
+++ b/target/linux/mediatek/dts/mt7981b-openwrt-one.dts
@@ -15,6 +15,9 @@
                led-running = &led_status_green;
                led-upgrade = &led_status_green;
                serial0 = &uart0;
+               spi0‌ = &spi0;
+               spi1 = &spi1;
+               spi2 = &spi2;
        };
 
        chosen {
```

2025-04-17 15:48 UTC, claib commented
> This PR is a redo of a previous closed #17244
> 
> Use: running Meshtastic (packages are being merged already)
> 
> Reason: Change to device-tree overlay
> 
> Device: OpenWRT One specifically for the mikroBUS
> 
> Purpose: Adds device tree overlay for mikroBUS spidev spi2
> 
> Compiled Test: OpenWRT One/master

Hi :-)
got a mikroe LTE Module, can i make a gsm router with ?

2025-06-04 17:50 UTC, TheLexus commented
@markbirss Thanks for your PR, I did the same a few hours ago until I found your PR.... :) My assumption was to simply use the MikroBus but it seems it was not really included somehow... Unfortunately it seems also that it has no priority and so we will not get the 5 reviews anytime soon..... So I will compile the image by myself. My question is, did you need todo anything beside applying the patch? Did you installed something else beside maybe the spi-dev kmod? And did you used any of the other pins. I would need at least one simple gpio pin for my project (add an oled display, for the DC pin). Thank you and best wishes down to the other side of the earth.

2025-06-04 19:02 UTC, KanjiMonster commented
> we will not get the 5 reviews anytime soon.....

Ignore that number, that is just there to prevent (accidental) merging via github UI. All it needs is a single maintainer agreeing and pushing it to the main git.

2025-06-04 20:29 UTC, TheLexus commented
Is there any way to give support from a regular user… some way to push it f.e.?

2025-06-18 15:23 UTC, TheLexus commented
Compiled 24.10.1 Tag with patch applied, works like it should. spidev gets exposed in user space. So can confirm the patch works as intended.

2025-10-28 10:58 UTC, shtrophic commented
I'm curious - would this patch enable the usage of any kind of mikrobus board with the One?

2026-01-20 07:02 UTC, closed without merging