ath79: add support for TP-Link TL-WR941N v7 Chinese version
openwrt/openwrt pull request #1755
Opened 2019-01-20 16:03 UTC by 981213

Specification:
- SoC: Qualcomm Atheros QCA9558
- Flash: 4 MB
- RAM: 64 MB
- Ethernet: Atheros AR8236 with 5 FE ports

Flash instruction:
  Upload the generated factory firmware on web interface.

Signed-off-by: Chuanhong Guo <gch981213@gmail.com>

** This PR depends on #1704 **
The U-boot for this device enables switch mdio master, which makes PHYs inaccessible through CPU mdio and current PHY probing isn't possible because no PHY ID could be read. A mdio-device probing is required.

2019-01-21 16:41 UTC, adrianschmutzler commented
I don't see anything grammatically incorrect in "TP-Link TL-WR941N v7 Chinese version".
If you want to make it shorter, one could think about the ISO 3166 country codes and use CN for China/Chinese, for example. In addition, one could abbreviate "version" with "ver." or "vers.", which looks odd in my opinion, or get rid of it completely: "TP-Link TL-WR941N v7 (CN)".

I personally favor the latter one, which would also works readily for (EU), (US), (DE), etc.

2019-03-21 11:34 UTC, ynezz requested changes
This PR depends on #1739

2019-03-21 12:37 UTC, 981213 commented
Oops. It depends on #1739, not #1704
I never noticed that I typed the wrong PR ID...

2019-03-23 13:45 UTC, ynezz commented
I've just merged this to my https://git.openwrt.org/?p=openwrt/staging/ynezz.git;a=shortlog;h=refs/heads/staging tree, will try to build test it, then push to master once complete. Thanks!

2019-03-23 13:45 UTC, closed without merging