mvebu: fixes commit a7e68927d0
openwrt/openwrt pull request #2123
Opened 2019-06-13 17:53 UTC by gamanakis

err_free_stats was accidentally removed from 403-net-mvneta-convert-to-phylink.patch
leading to compilation errors.

Compile-tested on: mvebu
Runtime-tested on: mvebu

Signed-off-by: George Amanakis <gamanakis@gmail.com>

2019-06-13 18:02 UTC, ptpt52 requested changes

2019-06-13 18:02 UTC, ptpt52 commented on target/linux/mvebu/patches-4.14/403-net-mvneta-convert-to-phylink.patch
> ++err_free_stats:
change it by
`goto err_free_stats;` to `goto err_netdev;`
should be more proper

see https://github.com/x-wrt/x-wrt/commit/c7fca6ea64838d11c084ff736e7dc3e06e352129

2019-06-13 18:06 UTC, ptpt52 commented on target/linux/mvebu/patches-4.14/403-net-mvneta-convert-to-phylink.patch
> ++err_free_stats:
err_free_stats label was drop by upstream kernel
we may use label `err_netdev` instead

2019-06-15 10:16 UTC, diizzyy commented
Works fine on my WRT3200ACM as far as I can tell :-)

2019-06-16 17:07 UTC, hauke commented
thank you for the patch it was applied to master

2019-06-16 17:07 UTC, closed without merging

2019-06-17 19:36 UTC, wvdakker commented
Can this also be backported to 18.06?