at91: split up DEVICE_TITLE
openwrt/openwrt pull request #2221
Opened 2019-07-10 21:41 UTC by mwarning

Splits up DEVICE_TITLE into DEVICE_VENDOR, DEVICE_MODEL and DEVICE_VARIANT.

2019-07-11 12:24 UTC, dangowrt requested changes
Please fill correct manufacturer of the 'Ethernut 5' (see comment)

2019-07-11 12:24 UTC, dangowrt commented on target/linux/at91/image/sam9x.mk
> +  DEVICE_VENDOR := Ethernut
Should be 'egnite' according to http://www.ethernut.de/en/imprint.html

2019-07-11 12:24 UTC, dangowrt commented on target/linux/at91/image/sam9x.mk
> +  DEVICE_MODEL := 5
Should be 'Ethernut 5'

2019-07-12 10:58 UTC, adrianschmutzler commented
Despite me not being familiar with target, this LGTM now.

2019-08-02 20:49 UTC, lynxis commented
merged. Thank you!

2019-08-02 20:49 UTC, closed without merging