ipq806x: split up DEVICE_TITLE
openwrt/openwrt pull request #2222
Opened 2019-07-10 21:52 UTC by mwarning

Splits up DEVICE_TITLE into DEVICE_VENDOR, DEVICE_MODEL and DEVICE_VARIANT.

2019-07-11 13:25 UTC, adrianschmutzler commented on target/linux/ipq806x/image/Makefile
> +	DEVICE_MODEL := Nighthawk X4 R7500
If there is a v2 below, this should have VARIANT v1.

2019-07-11 13:26 UTC, adrianschmutzler commented on target/linux/ipq806x/image/Makefile
> +	DEVICE_VARIANT := (legacy)
Brackets or not ...?
Despite, if that's variant "legacy", we need to also provide a variant for the "standard" one.

2019-07-11 13:28 UTC, adschm requested changes
Looks okay despite concerning the two comments.

2019-07-17 17:04 UTC, adschm approved these changes

2019-07-18 09:12 UTC, adrianschmutzler commented
@mwarning Had a look at my C2600 and it says Ver.1.1.
If you still want, you could also add "v1" to both TP-Link here ...

2019-07-18 12:16 UTC, adschm approved these changes

2019-08-02 20:49 UTC, lynxis commented
merged. Thank you!

2019-08-02 20:49 UTC, closed without merging