gemini: split up DEVICE_TITLE
openwrt/openwrt pull request #2224
Opened 2019-07-10 22:10 UTC by mwarning

Splits up DEVICE_TITLE into DEVICE_VENDOR, DEVICE_MODEL and DEVICE_VARIANT.

2019-07-11 12:58 UTC, dangowrt requested changes
Two minor knits, apart from that looks good.

2019-07-11 12:58 UTC, dangowrt commented on target/linux/gemini/image/Makefile
> +	DEVICE_VARIANT :=
Don't add empty fields

2019-07-11 12:58 UTC, dangowrt commented on target/linux/gemini/image/Makefile
> +	DEVICE_VARIANT := 1-Bay Network Storage Enclosure
This belongs to MODEL, it's not that there are multiple variants of that device.

2019-07-11 13:37 UTC, adschm approved these changes
Looks good now.

2019-08-02 20:50 UTC, lynxis commented
merged. Thank you!

2019-08-02 20:50 UTC, closed without merging