ramips: add support for onboard sdcard reader
openwrt/openwrt pull request #2411
Opened 2019-09-14 15:26 UTC by novski

The Linkit Smart 7688 has a SD-Card reader that does not work with the official build of openwrt 18.06. Adding  kmod-sdhci-mt7620 makes it working.

Signed-off-by: Ivan Hörler <i.hoerler@me.com>

2019-09-14 20:17 UTC, adrianschmutzler commented
Hi, thanks for implementing my suggestions. However, please do not open a new PR when doing changes, but rebase your commits in the existing branch in the future, so discussion etc. is kept.

For this PR, I would like you to address the following minor issues:
- You are changing only Linkit Smart 7688, but your commit title does not express that. Maybe choose something more specific like
"ramips: add SD-Card support to Linkit Smart 7688"
- In the commit description, please remove the reference to 18.06. Your commit will be applied to master, and then might be backported to older stable branches, so the reference to 18.06 is wrong in this case. Just state that the SD-Card reader is not working ATM.

2019-09-15 11:10 UTC, dangowrt requested changes
Please change the title of the commit (not the PR, that doesn't matter) as suggested by Adrian:
"ramips: add SD-Card support to Linkit Smart 7688"

2019-09-15 11:54 UTC, novski commented
I'm not able to find a solution how to change a commit Titile without Changeing the PR. 
Can you give me help here?
I have my local repo with a branch i push to github there i click on the PR buton. 
Do i have to change the Title local, in my github account or on the PR?

2019-09-15 12:03 UTC, dangowrt commented
Use `git commit  -a` to edit the commit title and then use `git push -f novski mt76x8-sdcard` to push the modified commit onto the branch you are referencing in the PR.

2019-09-15 12:13 UTC, novski commented
Did that now work? 
I was not aware that a push to my GitHub account would update the PR to openWRT GitHub account automatically. 
Thanks for learning me that!

2019-09-15 13:13 UTC, dangowrt commented
Yes, that worked, but you only added "mt76x8, " to the title, which is not compliant with our formatting guidelines. Please use
"ramips: add SD-Card support to Linkit Smart 7688"
as suggested by Adrian.

2019-09-15 18:15 UTC, novski commented
Ok. Slowly i'm having fun with `git comment --amend`. What a learning today. :-D

2019-09-15 18:33 UTC, dangowrt approved these changes
Looks good now!

2019-09-15 18:45 UTC, closed without merging