ath79: allow gmac configuration from DT
openwrt/openwrt pull request #2441
Opened 2019-09-23 20:03 UTC by j-d-r

Here are two patches:

- first: add extra registers and masks for GMAC of SoCs qca956x.
Values are taken from [CAF](https://source.codeaurora.org/quic/qsdk/oss/boot/u-boot-1.1.4/tree/include/956x.h).
- second: import values from device tree

Regards

2019-09-23 22:27 UTC, juppin commented
As long as no one uses it, this is almost useless...

2019-10-07 18:20 UTC, CodeFetch commented
@juppin It's good for completeness sake and if someone needs it at some point it's already there.

2019-10-07 18:24 UTC, CodeFetch approved these changes
What is CAF U-Boot? Can you give a link for reference?

2019-10-07 21:39 UTC, j-d-r commented
Feel free to do whatever you want of these two commits.

I'm using some of theses settings in my support for TP-Link EAP 245v1 https://github.com/j-d-r/openwrt/commit/c59e1665caae99f4a18f1328c2accac4524aca2e as TP-Link uses them in their GPL code (Linux 3.3.8)

CAF stands for code aurora forum. Qualcomm publishes here their open source code.

U-Boot 1.1.4 for AP152 - QCA956x reference board - is published here. Header https://source.codeaurora.org/quic/qsdk/oss/boot/u-boot-1.1.4/tree/include/956x.h contains most registers definitions.

2019-10-07 22:24 UTC, blocktrron commented
@j-d-r Have you already sent the patch you are adding here to linux-mips?

2019-10-08 06:24 UTC, j-d-r commented
@blocktrron No I didn't, kernel patch is only some #define.

2019-11-06 17:23 UTC, adrianschmutzler commented
@j-d-r "some" is an understatement

2019-11-06 21:35 UTC, CodeFetch requested changes

2019-11-06 21:35 UTC, CodeFetch commented on target/linux/ath79/patches-4.14/920-qca956x-add-more-registers.patch
> ++#define QCA956X_PLL_CPU_PLL_DITHER2_REG			0x44
Indentation issues. I think this should be sent upstream, too.

2019-11-06 21:38 UTC, CodeFetch commented on target/linux/ath79/patches-4.19/920-qca956x-add-more-registers.patch
> +Values are taken from U-Boot 1.1.4 of CAF.
What is CAF?

2020-05-07 16:52 UTC, adrianschmutzler commented
@blocktrron @981213 Would one of you provide a verdict on these changes?

From the comments, it looks to me like we don't need them right now, so no reason to care for now?

2020-05-07 18:02 UTC, blocktrron commented
Dragonfly as well as Jet platforms do not offer MII interfaces other than SGMII to my knowledge. So all settings except for the MII mux (ge0-sgmii) seem to be superfluous to me.

However (in case this multiplexer exists) and it's configured incorrectly, we should configure it for this platform static to ge0, as the QCA9563 only has one MAC. But as this is not an issue (as far as I'm concerned about this PR).

I'm for closing here. If we need any of those knobs we can add them later. I'm not to fond about dead code in a driver we are currently maintaining ourselves.

2020-05-07 18:02 UTC, closed without merging