firmware-utils/hcsmakeimage: fix possible memory leake and resource leak
openwrt/openwrt pull request #2686
Opened 2020-01-11 22:01 UTC by draane

Add missing call to `free` for variable `filebuffer`.
Add missing calls to `fclose` for variables `fd` and `fd_out`.

2020-01-14 16:18 UTC, jow- requested changes
I think you also need a further `free(filebuffer)` in line 197.

2020-01-14 16:26 UTC, draane commented
Yes, you are right. 

> I think you also need a further `free(filebuffer)` in line 197.

Yes you are right. I just fixed it

2020-06-23 18:08 UTC, adrianschmutzler commented
@jow- Can you have another look here?

2020-07-08 12:31 UTC, ynezz commented
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ynezz.git

2020-07-08 12:31 UTC, closed without merging