x86: Support Aquantia 10 Gigabit Ethernet Cards
openwrt/openwrt pull request #3086
Opened 2020-06-07 15:20 UTC by aidanharris

I've built an X86 gateway running OpenWrt with an ASUS XG-C100C PCI-E (actually `Aquantia Corp. AQC107 NBase-T/IEEE 802.3bz Ethernet Controller [AQtion] (rev 02)`).

I based this off of 7e0e5110bc90a8d6e709b9a070eb2aa82d46f15d so the dependencies may not be 100% correct. I'm really pleased with the result so far and would like to thank all of the OpenWrt developers working on this great project.

2020-06-07 16:59 UTC, adrianschmutzler commented
This PR has formal issues, please check https://openwrt.org/submitting-patches

2020-06-07 17:28 UTC, aidanharris commented
@adrianschmutzler I know there's issues with it. I need help with knowing if the general approach is correct and can fix up the commit message later.

2020-06-08 09:52 UTC, bobafetthotmail commented
I see you added  @TARGET_x86

Does this card actually need a x86 system to work?

2020-06-08 17:25 UTC, aidanharris commented
@bobafetthotmail 

```
config AQTION
	tristate "aQuantia AQtion(tm) Support"
	depends on PCI
	depends on X86_64 || ARM64 || COMPILE_TEST
```

What's the correct way of expressing X86_64 or ARM64?

2020-06-08 19:21 UTC, bobafetthotmail commented
That's weird, but ok.

This is the right way of writing that if you want to limit for OpenWrt targets/subtargets.
`DEPENDS:=@TARGET_x86_generic||TARGET_x86_64` see here 
https://github.com/openwrt/openwrt/blob/34e22653ac18b6ac7fd368ca47625f665808067f/package/kernel/linux/modules/virt.mk#L21

Imho you should use TARGET_x86_64 instead of TARGET_x86 as the first will make sure it is only available to 64bit x86, like the driver wants.

but ARM64 isn't an OpenWrt target, and afaik there are 4-5 ARM64bit targets around in layerscape, sunxi and mvebu targets. Look for the subtargets that have `CONFIG_ARM64=y` in the kernel **config-4.19** or **config-5.4** files

So maybe TARGET_sunxi_cortexa53 and TARGET_layerscape_armv8_64b and TARGET_mvebu_cortexa72 and TARGET_mvebu_cortexa53 should be the right ones to catch all ARM64 devices.

I have not seen these tags used in the build system, but in the example above is clearly using them for x86 subtargets.

IMHO the only thing you should really do here is use "TARGET_x86_64" instead of TARGET_x86, so you exclude 32bit x86 hardware too (and check that if you try to build a x86 generic/legacy/Geode firmware you can't select this package from the make menuconfig interface.

As for the support in the ARM64 devices I'd say it's probably not worth the effort to add and maintain a list of the ARM 64bit targets, most are not physically able to mount this card anyway.

2020-06-08 21:42 UTC, adrianschmutzler commented
> DEPENDS:=@TARGET_x86_generic||TARGET_x86_64

Actually, that looks wrong to me. I would have expected:
DEPENDS:=@(TARGET_x86_generic||TARGET_x86_64)

But I may easily be mistaken here ...

2020-06-08 21:51 UTC, s-2 commented
Please also add this to `ipq807x`, which is ARM64.

I will soon need the driver to add support for EnGenius EWS377AP that is based on ipq8074, using `AQC112C` attached via PCI-E for the only (2.5GBASE-T) Ethernet port available on that device.

Everything compiled without errors so far.

2020-06-17 14:58 UTC, wulfy23 commented
kmod-lib-crc-itu-t ?

2020-06-18 21:57 UTC, hauke requested changes

2020-06-18 21:57 UTC, hauke commented on package/kernel/linux/modules/netdevices.mk
> +  KCONFIG:=CONFIG_AQUANTIA_PHY \
Why do you select here CONFIG_AQUANTIA_PHY?

2020-06-18 21:57 UTC, hauke commented on package/kernel/linux/modules/netdevices.mk
> +  AUTOLOAD:=$(call AutoLoad,35,atlantic)
please use
```
 AUTOLOAD:=$(call AutoProbe,atlantic)
``` 
same for the phy

2020-06-18 21:57 UTC, hauke commented on package/kernel/linux/modules/netdevices.mk
> +  DEPENDS:=@PCI_SUPPORT +kmod-i2c-core +kmod-i2c-algo-bit +kmod-ptp +kmod-hwmon-core +LINUX_5_4:kmod-libphy
why does this need PCI, I2C and ptp?

2020-06-18 21:57 UTC, hauke commented on package/kernel/linux/modules/netdevices.mk
> +define KernelPackage/aquantia
please name this ```phy-aquantia```

2020-06-18 22:00 UTC, hauke commented
You can use 
```
DEPENDS:=@(x86_64||aarch64)
```

2020-07-15 19:27 UTC, adrianschmutzler commented
There has been no response for almost one month, and the initial commit has never been updated, so let's close this now.

2020-07-15 19:27 UTC, closed without merging

2021-03-29 02:42 UTC, aenertia commented
This is still broken in the 21.02 tagged branch and master.

https://bugs.openwrt.org/index.php?do=details&task_id=3710
Hardware which uses the atlantic.ko module is increasingly commonly deployed both in server, enthusiast and OEM embedded appliances (ipq80xx is a common pairing) as well as NBaseT SFP+ modules (rebadged by several vendors i.e Mikrotik) to supply NBaseT 10Gbit functionality. It has not been working in the last 2 openwrt releases and should be fixed before 21.02 goes out the door.

2021-09-20 13:48 UTC, Neustradamus commented
@aidanharris: Have you progressed on it?