lantiq: switch to 5.4
openwrt/openwrt pull request #3111
Opened 2020-06-15 06:14 UTC by olek210

Runtime tested on BT Home Hub 5A and D-Link DWR-966.

Signed-off-by: Aleksander Jan Bajkowski <A.Bajkowski@stud.elka.pw.edu.pl>

2020-06-15 20:50 UTC, dangowrt requested changes

2020-06-15 20:50 UTC, dangowrt commented on target/linux/lantiq/Makefile
>  KERNEL_TESTING_PATCHVER:=5.4
as `KERNEL_PATCHVER` is set to the same as `KERNEL_TESTING_PATCHVER` you can as well remove the `KERNEL_TESTING_PATCHVER` line.

2020-06-16 22:10 UTC, dangowrt approved these changes

2020-06-16 22:51 UTC, adrianschmutzler commented
Thanks, merged.

2020-06-16 22:51 UTC, closed without merging