tools/firmware-utils: refactor tp-link safeloader metadata partitions
openwrt/openwrt pull request #3332
Opened 2020-08-22 21:32 UTC by svanheule

In an attempt to bring a bit more structure to the tplink-safeloader image builder, I have started to refactor some of the code. Since this potentially touches a lot of code, I'm filing this as a draft PR, to check if this worth pursuing.

Currently, the changes are still split up, but e.g. the patches that touch the meta-partition padding can be merged. It's possible that the meta-partition padding values could be dropped altogether, but I don't have any devices where the stock upgrade images contain these padded partitions. I've noticed with my EAP-devices that the extra padding doesn't matter, since the amount of useful data is actually read from the meta-partition header.

To check whether the patches don't produce any (unintended) changes to the generated factory images, I've used a script that compares the (mock) output for all supported boards with a reference image built from master (ignoring the image's MD5 checksum).
After "tools/firmware-utils: safeloader extra-para is meta partition":
```
ARCHER-A7-V5 differs in 2 bytes
ARCHER-C7-V4 differs in 2 bytes
ARCHER-C7-V5 differs in 2 bytes
```
After "tools/firmware-utils: use same trailing data for all safeloader parts"
```
C2600 differs in 1 bytes
ARCHER-A7-V5 differs in 2 bytes
ARCHER-C5-V2 differs in 1 bytes
ARCHER-C7-V4 differs in 2 bytes
ARCHER-C7-V5 differs in 2 bytes
ARCHERC9 differs in 1 bytes
TLWA850REV2 differs in 1 bytes
TLWA855REV1 differs in 1 bytes
TLWR1043NDV4 differs in 1 bytes
TL-WR902AC-V1 differs in 1 bytes
TLWR942NV1 differs in 1 bytes
RE200-V2 differs in 1 bytes
RE220-V2 differs in 1 bytes
RE305-V1 differs in 1 bytes
RE350-V1 differs in 1 bytes
RE350K-V1 differs in 1 bytes
RE355 differs in 1 bytes
RE450 differs in 1 bytes
RE450-V2 differs in 1 bytes
RE450-V3 differs in 1 bytes
RE650-V1 differs in 1 bytes
```

The 2-byte changes come from the extra-para partition, while the 1-byte changes are caused by using the same padding value throughout the image.

PKG_RELEASE bumps will be added to the patches once I've got the number and order worked out.

2020-09-20 18:03 UTC, svanheule commented
I've reworked the changes into two patches. A first focussing on the metadata partition generation, and a second on the padding of these metadata partitions. I haven't really been able to do more, and since this has been here for a while, I'll just leave it at these two patches for now.

2020-10-04 18:09 UTC, svanheule commented
@adschm Would you be able to review these patches? I can also send them to the mailing list if you prefer that.

2020-10-04 19:30 UTC, adschm commented
I prefer GitHub, but I can't review these (as goes for functional changes to tplink-safeloader in general, unless trivial).

2020-10-04 20:19 UTC, svanheule commented
No problem. Let me ping a few more people here then, before trying the mailing list with the long patches.

@NeoRaider @jow- @lynxis You seem to have commited/authored some of the previous functional changes to tplink-safeloader. Anyone willing to review?

2020-10-07 09:24 UTC, lynxis commented
I'll take a look later.

2020-10-08 18:40 UTC, svanheule commented
Rebased onto master to also include TL-WPA8630P-V2.1-EU in "firmware-utils: tplink-safeloader: refactor meta-partition padding"

2020-11-13 09:43 UTC, svanheule commented
Rebased commits to account for 65f3e7ce1f4a (PKG_RELEASE bump) and 33b76d66d1af (added TP-Link device).

2020-12-03 00:12 UTC, lynxis requested changes
Hi @svanheule,

only small nitpicks for coding style. But in general it looks good.
Thanks for the contributions.

Best,
lynxis

2020-12-03 00:12 UTC, lynxis commented on tools/firmware-utils/src/tplink-safeloader.c
> +) {
can you move the ')' on the same line of the arguments.
The file already mixes different styles, but let's not introduce another style ;).

2020-12-03 00:12 UTC, lynxis commented on tools/firmware-utils/src/tplink-safeloader.c
> +) {
```
    enum partition_trail_value pad_value)
{
```

2020-12-03 00:12 UTC, lynxis commented on tools/firmware-utils/src/tplink-safeloader.c
> +) {
same

2020-12-03 00:12 UTC, lynxis commented on tools/firmware-utils/src/tplink-safeloader.c
> +) {
same

2020-12-03 00:13 UTC, lynxis commented
It would be also great if you could rebase it as your patch for the EAP changed the same file.

2020-12-03 09:12 UTC, svanheule commented
I've rebased for the added EAP devices, also dropping the partition padding there like for the ones that were already present.

The function definition line breaks have been reformatted. I've also reformatted some function calls, so a line break is only present if the next argument would exceed 80 characters.

2020-12-07 01:01 UTC, closed without merging

2020-12-07 01:02 UTC, lynxis commented
merged. thanks