base-files: fix alias more to properly detect /usr/bin/more
openwrt/openwrt pull request #3637
Opened 2020-11-27 11:13 UTC by zhanhb

more is installed to `/usr/bin` rather than `/bin`.

https://github.com/openwrt/openwrt/blob/9762cf107bdbd709717b8adbba6f987c9935c74f/package/utils/util-linux/Makefile#L690

2020-11-27 11:47 UTC, adschm commented
Please bump PKG_RELEASE.

2020-11-27 13:36 UTC, zhanhb commented
Done

2020-11-28 20:00 UTC, aparcar requested changes

2020-11-28 20:00 UTC, aparcar commented on package/base-files/files/etc/shinit
> +[ -x /bin/more -o -x /usr/bin/more ] || alias more=less
```
               ^-- SC2166: Prefer [ p ] || [ q ] as [ p -o q ] is not well defined.
```

2020-11-28 20:00 UTC, aparcar commented on package/base-files/files/etc/shinit
> +[ -x /bin/more -o -x /usr/bin/more ] || alias more=less
Or do we have a policy on thi?

2020-11-28 22:52 UTC, aparcar approved these changes

2020-11-29 01:13 UTC, aparcar commented
Merged, thanks!

2020-11-29 01:13 UTC, closed without merging