apm821xx: WNDR4700 additional user space on "ecos" partition
openwrt/openwrt pull request #3671
Opened 2020-12-10 23:56 UTC by WiktorS

This change allows to use "ecos" partition as extroot (or even rootfs_data)
Detailed description in commit message.

Identical solution was provided by @chunkeey on the forum some time ago, as a script to modify DTS in the image.

I think it would be nice to have this feature as a standard for WNDR4700, without it there is almost no space to install any additional services.

Side effect of this change is that if "ecos" partition is not formatted with ubifs kernel will print an error message at boot time:
`UBI error: cannot attach mtd9`

2020-12-11 00:16 UTC, adschm commented
Hi, commit title is too long, commit message needs to be wrapped.

2020-12-11 21:29 UTC, WiktorS commented
Commit message reformatted

2021-01-26 09:17 UTC, neheb approved these changes

2021-05-16 22:10 UTC, adschm commented
@chunkeey You seem committed to apm821xx, would you have a look here? I don't think anybody else will ...

2021-05-17 16:05 UTC, chunkeey commented
> I don't think anybody else will ...

you don't either?

@adschm 9ba09653ade1fa20d0d777390d522fb179c1088e

I have no problem with others committing patches to apm821xx. The sad thing I had to learn is that because I'm was reviewing and pushing patches, I ended up being the sole person that would even look at these. In case of apm821xx it's probably not so bad, because there isn't any more HW and most of the driver support is upstream, but ipqXXXX seems to have been been hurt by this.

2021-05-17 21:04 UTC, adschm commented
> > I don't think anybody else will ...
> 
> you don't either?
> 

Unfortunately my skills are limited, so I was not calling because of laziness, but just because I'm not really capable of reviewing the patch, and it has been lying around for months already. Which of course is sadly also true for many ipqxxxx patches as you mentioned...

2021-05-18 18:56 UTC, chunkeey commented
> Unfortunately my skills are limited, so I was not calling because of laziness, but just because I'm not really capable of reviewing the patch, and it has been lying around for months already. Which of course is sadly also true for many ipqxxxx patches as you mentioned...

What I'm frightened about is this sentence that is included in this github conversation (not in the commit though):

"Identical solution was provided by @chunkeey on the forum some time ago, as a script to modify DTS in the image."

Since my skills are limited as well. This got me really thinking, because in some ways this makes it sound like a "solution"
can only be coming from me (if so, where is the attribution in the commit)... which is definitely not true. Case in point is
1941ac06f0d78074e6f3239eac81936f2d09f40f which is something I clearly missed.

2021-05-25 19:51 UTC, CodeFetch commented
@s-2 Haven't you had a case with non-continuous partitions, too? How did you solve this without extroot?

2021-05-25 20:18 UTC, CodeFetch commented
As UBI runs on top of MTD I think mtd-concat is the way to go...
`The Linux kernel treats “raw/host-managed” flash memory (NOR and NAND alike) as an MTD (Memory Technology Device).`
`Unsorted Block Images (UBI) is an erase block management layer in the Linux kernel for raw NAND flash memory chips. It is layer on top of the MTD layer. UBI is used by UBIFS.`

2021-05-26 16:38 UTC, s-2 commented
> Unsorted Block Images (UBI) is an erase block management layer in the Linux kernel for raw NAND flash memory chips.

Though it technically would not harm NOR chips, it feels a bit weird though (like formatting a mechanical harddrive to JFFS / exFAT), especially the mixing of two different underlying hardware technologies, with a "boundary" at some arbitrary position within the raw file system.
I think this should be some sort of overlay filesystem, assuming the size of NOR flash is relevant for OpenWrt usage in the first place (though it seems the main issue here is backwards-compatibility with a device that is already supported).

2021-05-27 07:18 UTC, CodeFetch commented
@s-2 This is not about mixing NOR and NAND. It think you looked wrong. Both partitions are on NAND flash. UBIFS runs on top of MTD. Therefore it should be no problem to use use mtd-concat here...

2021-05-30 01:04 UTC, CodeFetch commented
@WiktorS Please see https://git.openwrt.org/?p=openwrt/staging/adrian.git;a=blob;f=target/linux/ath79/dts/qca9533_qca_ap143-16m.dts;h=31e61de175c36647fe9f29a29141e38f721d4444;hb=a29a1f3c2748a52f6d27646b6e64958b37e85eaa
for how to use mtd-concat...

2021-05-30 01:05 UTC, CodeFetch requested changes
Use mtd-concat, please.

2026-07-06 07:01 UTC, jonasjelonek commented
addressed by #24098, closing this.

2026-07-06 07:01 UTC, closed without merging