iperf3: add uci server handling
openwrt/openwrt pull request #3788
Opened 2021-01-14 17:35 UTC by feckert

@pprindeville
This P/R adds the possibility that iperf3 can be configured via the uci as server and also as client.
I also added a shell wrapper to send the output from Iperf3 to the ubus.
This is needed for the LuCI [feature](https://github.com/openwrt/luci/pull/4651).

2021-01-14 18:37 UTC, pprindeville requested changes
Minor changes...

2021-01-14 18:37 UTC, pprindeville commented on package/network/utils/iperf3/files/etc/config/iperf3
> +#	option enabled '1'
Just set `enabled` to `0` and uncomment everything.

2021-01-14 18:37 UTC, pprindeville commented on package/network/utils/iperf3/files/etc/init.d/iperf3
> +	[ -n "$server" ] || {
You use `if`/`then` everywhere else... might as well be consistent.

2021-01-14 18:37 UTC, pprindeville commented on package/network/utils/iperf3/files/etc/init.d/iperf3
> +extra_command "client" "<cfg> Start a client"
Newline after?

2021-01-14 18:37 UTC, pprindeville commented on package/network/utils/iperf3/files/usr/libexec/iperf3-ubus-redirect
> +	for sig ; do
`sig`? Should it be `$@`?

2021-01-14 18:37 UTC, pprindeville commented on package/network/utils/iperf3/files/usr/libexec/iperf3-ubus-redirect
> +	kill -${1} ${2} 2>/dev/null
Drop the braces but add quotes...

2021-01-14 18:37 UTC, pprindeville commented on package/network/utils/iperf3/files/usr/libexec/iperf3-ubus-redirect
> +main $@
Quotes around `$@`.

2021-01-15 05:13 UTC, aparcar commented
Could iper3 be moved to packages.git?

2021-01-15 09:58 UTC, feckert commented
@aparcar I have also already thought of this

2021-01-15 10:00 UTC, aparcar commented
@feckert what is your conclusion?

2021-01-15 10:18 UTC, feckert commented
@aparcar I would move it to the package feed.

2021-01-15 20:56 UTC, pprindeville requested changes
More minor changes but looking better.

2021-01-15 20:56 UTC, pprindeville commented on package/network/utils/iperf3/files/etc/init.d/iperf3
> +	config_get_bool reverse "$cfg" reverse '0'
Not quotes around the value since it's numeric

2021-01-15 20:56 UTC, pprindeville commented on package/network/utils/iperf3/files/usr/libexec/iperf3-ubus-redirect
> +	kill "-${1}" "$2" 2>/dev/null
Don't need curlies around `$1`.

2021-01-15 20:57 UTC, pprindeville commented on package/network/utils/iperf3/files/etc/init.d/iperf3
> +	config_get_bool udp "$cfg" udp '1'
Ditto

2021-01-15 20:59 UTC, pprindeville commented
> Could iperf3 be moved to packages.git?

It's not clear to me why it's considered a "core" package.

2021-01-18 07:42 UTC, feckert commented
I am closing the P/R now and will reopen it when the package has been moved.

2021-01-18 07:42 UTC, closed without merging