rockchip: sync ROCK Pi 4 with DTS "manufacturer,model"
openwrt/openwrt pull request #3812
Opened 2021-01-25 19:06 UTC by mj22226

This fix  sysupgrade warning:
"`upgrade: Device radxa,rockpi4 not supported by this image.....`"

2021-01-25 19:13 UTC, blocktrron requested changes

2021-01-25 19:13 UTC, blocktrron commented on target/linux/rockchip/image/armv8.mk
> +  SUPPORTED_DEVICES:=radxa,rockpi4
spacing around `:=`

2021-01-25 19:26 UTC, mj22226 commented on target/linux/rockchip/image/armv8.mk
> +  SUPPORTED_DEVICES:=radxa,rockpi4
fixed

2021-01-27 20:05 UTC, adschm commented
Thanks, will be merged with updated commit title/message.

2021-01-27 20:05 UTC, closed without merging