lldpd: cflags to reduce size
openwrt/openwrt pull request #3823
Opened 2021-01-30 11:37 UTC by lucize

enable flto cflags to reduce package size

Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>
Maintainer: @stintel 

size differences and tested on:

mips
new 114 461
old 129 991

kirkwood
new 127 603
old 139 291

mvebu
new 126 134
old 138 730

x86_64
new 130 050
old 144 171

2021-02-28 23:32 UTC, hauke commented on package/network/services/lldpd/patches/001-disable_libcap.patch
> -+AC_SUBST([libcap_CFLAGS])
I would prefer if you do these changes in the ```configure.ac``` and then add this to the package Makefile to recreate the the ```configure``` file.
```PKG_FIXUP:=autoreconf```

2021-03-04 18:56 UTC, stintel commented
Also: don't bump and make unrelated other changes in a single commit, this makes bisecting impossible. So please address Hauke's comment, and split the PR in 2 commits. Ideally, the patch to disable libcap should be submitted upstream. The current one was previously accepted by another developer without me noticing in time, but now that changes are required, please upstream first.

2021-03-04 18:57 UTC, stintel requested changes
Also: don't bump and make unrelated other changes in a single commit, this makes bisecting impossible. So please address Hauke's comment, and split the PR in 2 commits. Ideally, the patch to disable libcap should be submitted upstream. The current one was previously accepted by another developer without me noticing in time, but now that changes are required, please upstream first.

2021-03-04 20:38 UTC, lucize commented
didn't had time to test the autoreconf, I'll approach upstream about libcap, but -flto can be very useful on 4MB devices

2021-03-10 09:54 UTC, stintel commented
Another option is to move libcap from the packages feed to OpenWrt base and add the libcap dependency. I actually prefer this, as it would allow the monitor process to drop its privileges instead of running as root, which improves security. This will not help 4MB devices, but honestly I prefer security over keep supporting almost unsupportable devices.

2021-03-10 09:59 UTC, lucize commented
yes, let's do that and if upstreamed we'll add option not to link against libcap

2021-03-10 10:16 UTC, stintel commented
> Another option is to move libcap from the packages feed to OpenWrt base

@p-wassi any objections?

2021-03-10 10:33 UTC, stintel commented
Prepared it here: https://git.openwrt.org/?p=openwrt/staging/stintel.git;a=shortlog;h=refs/heads/libcap

2021-03-16 12:37 UTC, hauke commented
Adding libcap to the main repository is a good idea.

2021-03-16 12:45 UTC, stintel commented
> Adding libcap to the main repository is a good idea.

@ynezz seems to disagree, see http://lists.openwrt.org/pipermail/openwrt-devel/2021-March/034286.html
I prefer we continue the discussion there.

2021-04-05 17:01 UTC, closed without merging