Add support for Linksys E5600
openwrt/openwrt pull request #3874
Opened 2021-02-16 11:43 UTC by aashishkul

ramips: add support for Linksys E5600

This submission relied heavily on the work of
Santiago Rodriguez-Papa and DavideFioravanti for their work on Linksys EA7300 v1 and v2.

Specifications:

*  SoC:            MediaTek  MT7621A            (880  MHz  2c/4t)
*  RAM:            Unknown         (128M  DDR3-1600)
*  Flash:          Winbond W29N01HVSIN          (128M  NAND)
*  Eth:            MediaTek  MT7621A            (10/100/1000  Mbps  x5)
*  Radio:          MT7603E/MT7613E              (2.4  GHz  &  5  GHz)
                     4  antennae:  2 on PCB internal  and  2 PCB type mounted on casing
*  USB:            None
*  LEDs:
          Blue/ Amber    (x1  Power/ WPS)
          Blue/ Amber    (x1  Internet/ WPS)
          Blue   (x4,  Ethernet Link)
*  Buttons:
          Reset    (x1)
          WPS      (x1)

Installation:

Flash factory image through GUI.

This might fail due to the A/B nature of this device. When flashing, OEM
firmware writes over the non-booted partition. If booted from 'A',
flashing over 'B' won't work. To get around this, you should flash the
OEM image over itself. This will then boot the router from 'B' and
allow you to flash OpenWRT without problems.

Reverting to factory firmware:

Hard-reset the router three times to force it to boot from 'B.' This is
where the stock firmware resides. To remove any traces of OpenWRT from
your router simply flash the OEM image at this point.

2021-02-16 16:12 UTC, adschm requested changes

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/dts/mt7621_linksys_e5600.dts
> +		aliases {
Broken indent, missing empty line.

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/dts/mt7621_linksys_e5600.dts
> +		wan_a {
wan_amber and wan_blue

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/dts/mt7621_linksys_e5600.dts
> +		};
This should be order by something, either node names or GPIO (last I'd prefer).

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/dts/mt7621_linksys_e5600.dts
> +
drop empty line.

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/dts/mt7621_linksys_e5600.dts
> +		partition@1f80000 {
Please have empty lines between all nodes here.

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/dts/mt7621_linksys_e5600.dts
> +
remove second empty line.

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/dts/mt7621_linksys_e5600.dts
> +		groups = "i2c", "uart2", "uart3", "jtag", "wdt";
i2c and wdt don't seem needed?

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/dts/mt7621_linksys_e5600.dts
> +		port@1 {
Please add empty lines between nodes.

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/dts/mt7621_linksys_e5600.dts
> +
drop empty line at EOF

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/image/mt7621.mk
> +define Device/linksys_e5600
Alphabetic sorting.

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/image/mt7621.mk
> +  DEVICE_VENDOR := Linksys
Please order this in a more reasonable way.

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/image/mt7621.mk
> +  uboot-envtools
Hanging indent with one tab.

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/image/mt7621.mk
> +  append-ubi | check-size | linksys-image type=$$$$(LINKSYS_HWNAME)
Hanging indent ...

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/mt7621/base-files/etc/board.d/01_leds
> -	ucidef_set_led_netdev "wan" "wan link" "green:wan" "wan" "link"
What the ...?

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/mt7621/base-files/etc/board.d/02_network
> +	linksys,e5600)
alphabetic sorting?

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/mt7621/base-files/etc/hotplug.d/ieee80211/10_fix_wifi_mac
> +	linksys,e5600)
Alphabetic sorting ...

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/mt7621/base-files/etc/init.d/bootcount
> +	linksys,e5600)
Sorting

2021-02-16 16:12 UTC, adschm commented on target/linux/ramips/mt7621/base-files/lib/upgrade/platform.sh
> +	linksys,e5600|\
Sorting.

2021-02-16 16:14 UTC, adschm commented
This has formal issues as well, please have another careful look at https://openwrt.org/submitting-patches

Note the difference between commit message (important) and PR comments (less important).

2021-03-01 06:37 UTC, aashishkul commented
Considering that there are few changes which unintentionally modified code for unrelated device, I will prepare a new pull request which would be much cleaner. Further, after doing testing for many times, I have also improved the support. So, I am closing this one and will create another one with all the comments in this pull request addressed in new pull request

2021-03-01 06:37 UTC, closed without merging

2021-03-01 21:55 UTC, adschm commented
No, please push your changes to this Pull Request, so we do not lose all the discussion made here, and have to do the same discussions again.
https://openwrt.org/docs/guide-developer/working-with-github-pr#reopen_closed_pr

2021-03-02 05:22 UTC, aashishkul commented
Reopening

2021-03-02 05:27 UTC, aashishkul commented
Actually, I deleted my fork and recreated a new branch with all the changes mentioned in the review. and submitted a new PR at following location: https://github.com/openwrt/openwrt/pull/3958.
Sorry for the inconvenience but as repository is now deleted, I think, this PR cannot be opened.

2021-03-02 20:02 UTC, adschm commented
> Actually, I deleted my fork and recreated a new branch with all the changes mentioned in the review. and submitted a new PR at following location: #3958.
> Sorry for the inconvenience but as repository is now deleted, I think, this PR cannot be opened.

It can.
https://openwrt.org/docs/guide-developer/working-with-github-pr#reopen_closed_pr

But let's do all the same work again in your new PR ...