A couple fixes for modules built with kernel 5.10
openwrt/openwrt pull request #3998
Opened 2021-03-17 18:44 UTC by jmarcet

Built and run tested on master x86-64.

2021-03-18 18:21 UTC, abajk commented on package/kernel/linux/modules/usb.mk
> +  DEPENDS:=+LINUX_5_10:kmod-libphy
This fixes kmod-usb-net-smsc95xx. You should change commit title.

2021-03-18 18:24 UTC, abajk requested changes

2021-03-18 18:24 UTC, abajk commented on package/kernel/linux/modules/usb.mk
> +  DEPENDS:=+LINUX_5_10:kmod-libphy
This fixes kmod-usb-net-smsc95xx. You should change commit title.

This commit is similar to the one in my [PR.](https://github.com/openwrt/openwrt/pull/4002) I missed this PR due to incorrect commit title.

2021-03-19 07:57 UTC, guidosarducci commented
@jmarcet @abajk I've also been working a few days on a branch with several fixes following up after #3989 , including two similar to yours: https://github.com/openwrt/openwrt/pull/3989#issuecomment-801331066. You both should have been notified since  you're mentioned in that PR.

I'm writing the PR for the new branch now. If you could have a look, and we come to consensus on the various fixes, let's coordinate what goes in which PR.

2021-03-19 14:56 UTC, hauke commented
Similar changes were pushed to master, see a374b8f190518a74dcc99d6bf3cf53adb7511963 and ad11fc8c236fca5283ed500d87504543f2768312. Please check if your changes are still needed and rebase on top of these changes.

2021-06-06 18:26 UTC, adschm commented
@jmarcet Ping.

2021-08-24 12:56 UTC, adschm commented
Closed due to inactivity.

2021-08-24 12:56 UTC, closed without merging