Add Hooolink HL-MF908v3, also known as CHANEVE MF909
openwrt/openwrt pull request #4070
Opened 2021-04-11 22:40 UTC by rozhuk-im

Specifications:

    MediaTek MT7628AN ver:1 eco:2 (575 MHz)
    128 MB RAM
    16 MB Flash
    802.11bgn 2T2R
    2x internal, non-detachable antenna
    1x 10/100 Mbps Ethernet
    1x USB 2.0 (Type-A)
    1x LTE CAT4 up to 150 mb/s modem @ mini PCI (USB, QMI)
    4 leds
    1 button
    UART header on PCB (57600 8n1)
    Breed bootloader
    ~8000 mAh battery (~16 hours uptime without traffic)

Features:

    upgrade from stock fw via web gui
    all leds avaible
    all buttons work
    LTE modem power on by default

Installation:
Apply sysupgrade image via http web-gui

Signed-off-by: Rozhuk Ivan rozhuk.im@gmail.com

2021-04-12 12:24 UTC, mrkiko commented
Hello! And sincerely thank you for your contribution!

May I ask you to describe a recovery procedure for this device via the breed bootloader, including it in the commit message?
Furthermore, please do let the title refer to the target you're working on, ramips in this case.
You may also be asked ot report MAC addresses arrangement: what's the MAC address found on the device label?

Thanks again!!

2021-04-12 12:53 UTC, rozhuk-im commented
Vendor F/W and bootlog: http://www.netlab.linkpc.net/download/software/openwrt/HL-MF909v3/orig/

I use this method: https://ltehacks.com/viewtopic.php?t=779 but instead of pressing reset - press key on serial console.

There was no mac on labels outside device. Inside was label with: 78:a2:5a:55:4b:d8 but in webui device show a bit different mac (last 2 octets not match).

2021-04-12 13:04 UTC, rozhuk-im commented
Stock: https://aliexpress.ru/item/1005001370973658.html

2021-04-12 17:30 UTC, mrkiko commented
Thanks!! Very nice description!!

2021-04-12 18:11 UTC, rozhuk-im commented
```
groups = "i2c", "gpio", "uart1", "refclk", "wdt", "pwm0";
```
I'm not sure is refclk, wdt and pwm0 required.

```
[    0.434222] Serial: 8250/16550 driver, 3 ports, IRQ sharing disabled
[    0.448124] printk: console [ttyS0] disabled
[    0.456573] 10000c00.uartlite: ttyS0 at MMIO 0x10000c00 (irq = 28, base_baud = 2500000) is a 16550A
[    0.474378] printk: console [ttyS0] enabled
[    0.490869] printk: bootconsole [early0] disabled
[    0.509843] rt2880-pinmux pinctrl: pin io45 already requested by pinctrl; cannot claim for 10000d00.uart1
[    0.528855] rt2880-pinmux pinctrl: pin-45 (10000d00.uart1) status -22
[    0.541626] rt2880-pinmux pinctrl: could not request pin 45 (io45) from group uart1  on device rt2880-pinmux
[    0.561104] of_serial 10000d00.uart1: Error applying setting, reverse things back
[    0.575956] of_serial: probe of 10000d00.uart1 failed with error -22
[    0.589813] spi-mt7621 10000b00.spi: sys_freq: 191666666
[    0.607889] spi-nor spi0.0: mx25l12805d (16384 Kbytes)
```

2021-04-20 00:10 UTC, rozhuk-im commented
Diff that I make with ```dtc -I fs -O dts /sys/firmware/devicetree/base```

```
 / {
 	compatible = "wrtnode,wrtnode2p\0wrtnode,wrtnode2\0mediatek,mt7628an-soc";
-	model = "WM628";
+	model = "WRTnode2P";
 	#address-cells = <0x01>;
 	#size-cells = <0x01>;
 
@@ -57,7 +54,6 @@
 
 	wmac@10300000 {
 		compatible = "mediatek,mt7628-wmac";
-		ralink,mtd-eeprom = <0x12 0x04>;
 		status = "okay";
 		interrupt-parent = <0x03>;
 		interrupts = <0x06>;
@@ -84,32 +80,17 @@
 	leds {
 		compatible = "gpio-leds";
 
-		4g_led1 {
-			gpios = <0x14 0x00 0x01>;
-			label = "wrtnode:blue:4g_led1";
+		indicator {
+			gpios = <0x14 0x09 0x01>;
+			label = "wrtnode:blue:indicator";
 		};
-
-		wlan {
-			gpios = <0x13 0x0c 0x01>;
-			label = "wrtnode:blue:wlan";
-		};
-
-		4g_led2 {
-			gpios = <0x14 0x02 0x01>;
-			label = "wrtnode:blue:4g_led2";
-		};
-
-		4g {
-			gpios = <0x13 0x05 0x00>;
-			label = "wrtnode:blue:4g";
-		};
 	};
 
 	aliases {
-		led-boot = "/leds/wlan";
-		led-running = "/leds/wlan";
-		led-upgrade = "/leds/wlan";
-		led-failsafe = "/leds/wlan";
+		led-boot = "/leds/indicator";
+		led-running = "/leds/indicator";
+		led-upgrade = "/leds/indicator";
+		led-failsafe = "/leds/indicator";
 		serial0 = "/palmbus@10000000/uartlite@c00";
 	};
 
@@ -122,7 +103,7 @@
 		poll-interval = <0x14>;
 
 		reset {
-			gpios = <0x13 0x0e 0x01>;
+			gpios = <0x13 0x05 0x01>;
 			label = "reset";
 			linux,code = <0x198>;
 		};
@@ -146,13 +127,13 @@
 
 	ethernet@10100000 {
 		compatible = "ralink,rt5350-eth";
-		mac-address = [78 a2 5a 55 47 c6];
+		mac-address = [78 a2 5a 55 47 c4];
 		resets = <0x01 0x15 0x01 0x17>;
 		mediatek,switch = <0x11>;
 		interrupt-parent = <0x03>;
 		interrupts = <0x05>;
 		reg = <0x10100000 0x10000>;
-		mtd-mac-address = <0x12 0x2e>;
+		mtd-mac-address = <0x12 0x04>;
 		reset-names = "fe\0esw";
 	};
 
@@ -237,10 +218,10 @@
 			bank@1 {
 				compatible = "mtk,mt7621-gpio-bank";
 				gpio-controller;
-				phandle = <0x13>;
+				phandle = <0x14>;
 				reg = <0x01>;
 				#gpio-cells = <0x02>;
-				linux,phandle = <0x13>;
+				linux,phandle = <0x14>;
 			};
 
 			bank@2 {
@@ -253,10 +234,10 @@
 			bank@0 {
 				compatible = "mtk,mt7621-gpio-bank";
 				gpio-controller;
-				phandle = <0x14>;
+				phandle = <0x13>;
 				reg = <0x00>;
 				#gpio-cells = <0x02>;
-				linux,phandle = <0x14>;
+				linux,phandle = <0x13>;
 			};
 		};
 
@@ -417,6 +398,7 @@
 	esw@10110000 {
 		compatible = "mediatek,mt7628-esw\0ralink,rt3050-esw";
 		resets = <0x01 0x17>;
+		mediatek,portmap = <0x3e>;
 		interrupt-parent = <0x02>;
 		interrupts = <0x11>;
 		phandle = <0x11>;
@@ -477,13 +459,6 @@
 			#address-cells = <0x03>;
 			#size-cells = <0x02>;
 			reg = <0x00 0x00 0x00 0x00 0x00>;
-
-			wifi@0,0 {
-				compatible = "mediatek,mt76";
-				reg = <0x00 0x00 0x00 0x00 0x00>;
-				mediatek,mtd-eeprom = <0x12 0x8000>;
-				ieee80211-freq-limit = <0x4c4b40 0x5b8d80>;
-			};
 		};
 	};
```

```wifi@0,0 ``` - looks wrong in original F/W.
Also with ```WRTnode2P``` serial port have no input, but no serial in diff. Anyway, in this PR serial is work.

2021-04-25 21:20 UTC, adschm requested changes
Please shorten your commit title (maybe just put the second name in brackets after the first) and add the <> brackets for your e-mail address in Signed-off-by.

2021-04-25 21:20 UTC, adschm commented on target/linux/ramips/dts/mt7628an_hooolink_hl-mf908-v3.dts
> +#include "mt7628an.dtsi"
Missing SPDX license identifier

2021-04-25 21:20 UTC, adschm commented on target/linux/ramips/dts/mt7628an_hooolink_hl-mf908-v3.dts
> +	model = "HL-MF908v3";
What happened to Hooolink?
Please a space before "v3"

2021-04-25 21:20 UTC, adschm commented on target/linux/ramips/dts/mt7628an_hooolink_hl-mf908-v3.dts
> +	};
IIRC this is default (set in the dtsi).

2021-04-25 21:20 UTC, adschm commented on target/linux/ramips/dts/mt7628an_hooolink_hl-mf908-v3.dts
> +		};
Please sort these nodes by something ...

2021-04-25 21:20 UTC, adschm commented on target/linux/ramips/dts/mt7628an_hooolink_hl-mf908-v3.dts
> +		spi-max-frequency = <10000000>;
This can probably go faster.

2021-04-25 21:20 UTC, adschm commented on target/linux/ramips/dts/mt7628an_hooolink_hl-mf908-v3.dts
> +		partitions: partitions {
The label is not required in a DTS file.

2021-04-25 21:20 UTC, adschm commented on target/linux/ramips/dts/mt7628an_hooolink_hl-mf908-v3.dts
> +	mtd-mac-address = <&factory 0x2e>;
Are you sure? What's the vendor MAC address assignment for this device?

https://openwrt.org/docs/guide-developer/device-support-policies#mac_addresses

2021-04-25 21:20 UTC, adschm commented on target/linux/ramips/dts/mt7628an_hooolink_hl-mf908-v3.dts
> +	ralink,mtd-eeprom = <&factory 0x04>;
This should be set in the DTSI ...

2021-04-25 21:20 UTC, adschm commented on target/linux/ramips/dts/mt7628an_hooolink_hl-mf908-v3.dts
> +		groups = "i2c", "gpio", "uart1", "refclk", "wdt", "pwm0";
These need to be set correctly.

2021-04-25 21:20 UTC, adschm commented on target/linux/ramips/image/mt76x8.mk
> +  SUPPORTED_DEVICES += hl-mf908-v3
This line can be dropped (or is this needed for vendor firmware?)

2021-04-25 21:20 UTC, adschm commented on target/linux/ramips/mt76x8/base-files/etc/board.d/01_leds
> +hooolink,hl-mf908-v3|\
This can be dropped since you have the trigger in DTS.

2021-08-22 19:31 UTC, adschm commented
This appears to be abandoned. Please ping for reopening if you want to continue working on this.
Please do _not_ push to the remote branch before the PR has been reopened.

2021-08-22 19:31 UTC, closed without merging