kernel: add kmod-leds-uleds
openwrt/openwrt pull request #4147
Opened 2021-05-05 14:13 UTC by ktgeek

The allows userspace LEDs to be created and controlled. This can be useful
for testing triggers and can also be used to implement virtual LEDs.

Signed-off-by: Keith T. Garner <kgarner@kgarner.com>

2021-05-05 14:25 UTC, aparcar commented
Looks good to me.

2021-05-06 17:18 UTC, chunkeey commented
@aparcar yes? Have you tested it?

Of course, userspace drivers need some userspace tools to be useful. But then, OpenWrt has had supported for other userspace drivers or testing drivers (FUSE (this is a big one), iio, spidev, userspace thermal/speed govenor, mac80211's hwsim). So it would fit right in!

So, if it works. Why not? :+1:

2021-05-08 13:23 UTC, ktgeek commented
> Of course, userspace drivers need some userspace tools to be useful. But then, OpenWrt has had supported for other userspace drivers or testing drivers (FUSE (this is a big one), iio, spidev, userspace thermal/speed govenor, mac80211's hwsim). So it would fit right in!

I have a ["blinking lights" project](https://github.com/ktgeek/blinkstick-users) that is [almost ready](https://github.com/ktgeek/ktg-openwrt-packages/tree/master/bluld) to be submitted to misc packages. I've been using both of these for over a year at home, my thought was might as well make me easier for others to consume.

2021-05-11 11:21 UTC, aparcar requested changes

2021-05-11 11:21 UTC, aparcar commented on package/kernel/linux/modules/leds.mk
> + The options enables support for userspace LEDs.
```suggestion
 The option enables support for userspace LEDs.
```

2021-05-11 17:57 UTC, ktgeek commented on package/kernel/linux/modules/leds.mk
> + The options enables support for userspace LEDs.
Thanks for that. 🤦

2021-05-12 08:50 UTC, aparcar commented
Merged, thanks.

2021-05-12 08:50 UTC, closed without merging