ath79: add support for GL.iNet GL-XE300
openwrt/openwrt pull request #4245
Opened 2021-06-08 17:01 UTC by johnfzc

The GL-XE300 is a 4G LTE router based on the Qualcomm QCA9531 SoC.

Specifications:
 - Qualcomm QCA9531 @ 650 MHz
 - 128 MB of RAM
 - 16 MB of SPI NOR FLASH
 - 128 MB NAND FLASH (Not supported in this commit)
 - 2x 10/100 Mbps Ethernet
 - 2.4GHz 802.11b/g/n
 - 1x USB 2.0 (vbus driven by GPIO)
 - 5x LED, driven by GPIO
 - 1x button (reset)
 - 1x mini pci-e slot (vcc driven by GPIO)

Flash instructions:

Use the uboot recovery console (hold reset while powering on for five seconds)
to flash the firmware, sysupgrade from the vendor software will not install
stock OpenWrt correctly.

Based on vendor commit:

https://github.com/gl-inet/openwrt/commit/60553d7269df7442c8b6f18e4d10f3a58ed4b7ac

Signed-off-by: John Marrett <johnf@zioncluster.ca>

2021-06-09 20:38 UTC, adschm commented
Please check #4246 and apply everything here as well ...

2021-06-09 20:38 UTC, adschm commented
And, relevant in both cases: Why do we need a DTSI for a single device?

2021-06-09 20:53 UTC, johnfzc commented
> And, relevant in both cases: Why do we need a DTSI for a single device?

The DTSI was used in the GL.iNet source because there are variants with different add on and integrated components that can leverage them. Future improvements within OpenWrt could make use of these templates.

With this context in mind please confirm if you would prefer that I integrate the DTSI contents into the DTS files.

Once you let me know I will make the changes requested, confirm that I can still build and install the firmware and update both PRs.

2021-06-11 18:57 UTC, johnfzc commented
I will complete addressing feedback on #4246, once it's complete I will apply all learnings from those corrections on this PR as well which should clean up the outstanding items.

2021-06-20 17:17 UTC, adschm requested changes
This plus all the comments from the other PR.
Testing would have helped here as well.

2021-06-20 17:17 UTC, adschm commented on target/linux/ath79/dts/qca9531_glinet_gl-xe300.dtsi
> +
Drop 2nd empty line.

2021-06-20 17:17 UTC, adschm commented on target/linux/ath79/dts/qca9531_glinet_gl-xe300.dtsi
> +};
This node can be dropped.

2021-06-20 17:17 UTC, adschm commented on target/linux/ath79/dts/qca9531_glinet_gl-xe300.dtsi
> +
drop empty line.

2021-06-20 17:17 UTC, adschm commented on target/linux/ath79/dts/qca9531_glinet_gl-xe300.dtsi
> +		NAND_partitions: partitions {
lower case please.

2021-09-11 12:40 UTC, johnfzc commented
Another PR for this router, #4465 has made more progress than this request. I'm closing it now but will leave the branch present in my openwrt repo for future reference for some time. Don't hesitate to send me a message if you have any questions about my efforts here.

2021-09-11 12:40 UTC, closed without merging