add Pisen_WPR003N
openwrt/openwrt pull request #4347
Opened 2021-07-07 11:38 UTC by libinanshu

Specifications:
- QCA9341 SoC, 16 MB nor flash, 64 MB DDR2 RAM
- wifi 2.4Ghz 300Mbps
- 1x Ethernet LAN 10/100, 1x Ethernet WAN 10/100
- 1x PWR  LED
- 1x USB
- Reset buttons

2021-07-09 14:04 UTC, DragonBluep requested changes
Please signoff your commit and force push it again. Maybe your commit message can be more detailed. Just use
```
git commit --amend --signoff
git push ---force-with-lease origin master
```
Thank you!

2021-07-09 16:06 UTC, csharper2005 commented
It would be better to rename commit title according to naming convention. for example, ramips: add support for D-Link DAP-1325-A1. Please add flash instruction.

2021-07-09 16:08 UTC, csharper2005 commented on target/linux/ath79/dts/ar9341_pisen_wpr003n.dts
> +				reg = <0x000000 0x020000>;
Unnecessary zeros can be deleted.

2021-07-10 22:21 UTC, adschm commented
https://openwrt.org/docs/guide-developer/frequent-pr-mistakes#do_not_multi-post_or_re-post_prs

2021-07-15 11:02 UTC, closed without merging