mediatek: mt7623: import patch to fix msi warning
openwrt/openwrt pull request #4406
Opened 2021-07-28 21:29 UTC by PolynomialDivision

The Mediatek host bridge cannot handle Message Signaled Interrupts
(MSIs). The core PCI code is not aware that MSI is not available.
This results in warnings of the form:

WARNING: CPU: 2 PID: 112 at include/linux/msi.h:219
  pci_msi_setup_msi_irqs.constprop.8+0x64/0x6c
Modules linked in: ahci(+) libahci libata sd_mod scsi_mod
  gpio_button_hotplug
CPU: 2 PID: 112 Comm: kmodloader Not tainted 5.10.52 #0
Hardware name: Mediatek Cortex-A7 (Device Tree)

Use the 'no_msi' attribute to signal missing MSI suuport to the core PCI.

The patches are imported from the work of:
- Frank Wunderlich <frank-w@public-files.de>
- Thomas Gleixner <tglx@linutronix.de>
- Marc Zyngier <maz@kernel.org>

It was suggested by Frank Wunderlich in the banana-pi forum:
http://forum.banana-pi.org/t/banana-pi-bpi-r2-updated-openwrt-image/12421/21

2021-07-28 21:47 UTC, PolynomialDivision commented
@dangowrt

2021-07-29 00:51 UTC, mans0n commented
I have not build-tested this, but I used upstream patches and it did fix the msi warning.
torvalds/linux@94e89b145371
torvalds/linux@9ec37efb8783
torvalds/linux@645e9c38383d
I think this PR will work as well.

2021-07-29 01:33 UTC, dangowrt commented
@PolynomialDivision can you change the PR to import the upstream patches into `target/linux/generic/backport-5.10` instead? so it becomes obvious when to drop when we update the kernel.

2021-07-29 07:42 UTC, PolynomialDivision commented
> @PolynomialDivision can you change the PR to import the upstream patches into `target/linux/generic/backport-5.10` instead? so it becomes obvious when to drop when we update the kernel.

Changed PR and used the metioned patches from @mans0n.

2021-07-29 12:04 UTC, dangowrt requested changes
As they are applied upstream already, please move the patches to `target/linux/generic/backport-5.10` and prefix them with the kernel version in which they were applied (like the other patches in that folder)

2021-07-29 12:55 UTC, PolynomialDivision commented
@dangowrt Changed that, however I was only able to compile-test and not runtest again.

2021-07-29 12:58 UTC, dangowrt commented on target/linux/generic/backport-5.10/020-v5.14-0001-make-pci_host_common_probe-declare-its-reliance-on-msi-domains.patch
> +--- a/drivers/pci/controller/pci-host-common.c
Please run `make target/linux/{clean,refresh}` to strip patches according to our style rules.

2021-07-29 13:02 UTC, dangowrt requested changes
Files should be named as stated below:
```
820-v5.14-make-pci_host_common_probe-declare-its-reliance-on-msi-domains.patch 
821-v5.14-let-pci-host-bridges-declar-their-reliance-on-msi-domains.patch
822-v5.14-advertise-lack-of-built-in-msi-handling.patch
```
And refresh patches after renaming (see comment)

2021-07-29 13:04 UTC, mans0n commented
BTW they are actually v5.13 ;)

2021-07-29 13:09 UTC, PolynomialDivision commented
I committed now also the refreshed patches. Is that fine?

2021-07-29 13:16 UTC, dangowrt approved these changes
Looks perfect now. Maybe mention the refresh in the commit message, so people looking at diffstat understand what's happening.

2021-07-29 13:28 UTC, PolynomialDivision commented
Nice. Thanks. Next time I will directly enforce that rules. ;) Should I maybe also move the SPI patch to backports-5.10?

2021-07-29 14:17 UTC, dangowrt commented
Applied, thanks! So need to move the SPI fix as it doesn't touch any generic things while no_msi can be useful for other platforms as well (e.g. QCA Dakota IPQ4xxx, if I remember correctly).

2021-07-29 14:17 UTC, closed without merging