treewide: use SPDX identifier
openwrt/openwrt pull request #4661
Opened 2021-10-10 00:37 UTC by PolynomialDivision

Switch to SPDX license identifier to allow machines to check license.

In the review process, especially openwrt/packages, we often have to comment that people should use SPDX and not the legacy "This is free software, licensed under the ...". I guess people use already existing Makefiles as reference for adding new packages. We should update all Makefiles so people will not use not up-to-date Makefiles.

2021-10-10 07:57 UTC, aparcar requested changes

2021-10-10 07:57 UTC, aparcar commented on package/boot/arm-trusted-firmware-mvebu/Makefile
> +# SPDX-License-Identifier: GPL-2.0-or-later
Twice?

2021-10-10 13:00 UTC, mans0n commented
Right...we don't even have `/LICENSE` file anymore.

2021-10-10 18:57 UTC, PolynomialDivision commented on package/boot/arm-trusted-firmware-mvebu/Makefile
> +# SPDX-License-Identifier: GPL-2.0-or-later
That was a mistake. Removed it. :)

2021-10-10 21:06 UTC, aparcar commented
What tool did you use for this? `reuse`?

2021-10-10 21:13 UTC, PolynomialDivision commented
> What tool did you use for this? `reuse`?

I used no tool... xD Just basic copy + paste.

2021-10-10 21:15 UTC, aparcar commented
@PolynomialDivision this might improve your time https://github.com/fsfe/reuse-tool

2021-10-10 21:37 UTC, aparcar commented
Actually please this tool to `lint` your changes. Also this is a bit of a massive change, I'd prefer to make this happen in smaller chunks. We could start with all the stuff in `./include`.

2021-10-11 02:22 UTC, neheb commented
why or-later and not only?

2021-10-12 10:30 UTC, f00b4r0 commented
> > > I am unsure. We can also use `only`.
> 
> > 
> 
> > OpenWrt uses [GPL-2.0-only](https://github.com/openwrt/openwrt/blob/master/COPYING#L3) by default, we _should_ use it unless explicitly specified otherwise.
> 
> 
> 
> Thanks! :) That is a good argument.

It's not just a good argument. It's about respecting licensing and copyright. In particular your change would effectively relicense all the files that explicitly say "licensed under GPL version 2."

This is exactly why I personally believe it's a very bad idea to _replace_ license boilerplate with SPDX. Especially when the change is done by hand, which is very error-prone. The SPDX tag should only be _added_, that's far less invasive.

2021-10-12 13:11 UTC, PolynomialDivision commented
> It's not just a good argument. It's about respecting licensing and copyright.

Yeah, sorry. I did not want to disrespect any licensing and copyright. I was just unsure if `GPL-2.0-only` or `GPL-2.0-or-later`. Obviously I chosed the wrong one. I did this also by hand since sometimes the header look different and I wanted to unify them. Also one package is licensed by `apache`. I was just bored and wanted to do something useful while watching a movie. ;)

2021-10-24 06:43 UTC, closed without merging

2023-03-16 13:32 UTC, BKPepe commented
How did the discussion end up, if I may to ask? Because we have opened pull request to the packages repository and it would be good to know the result, if we want to proceed further with that PR.

2023-03-16 18:43 UTC, aparcar commented
The PR looks empty, que pasa?

2023-03-18 10:30 UTC, BKPepe commented
Because it was badly rebased and no longer restored. The old commit can be found here: https://github.com/openwrt/openwrt/commit/c78a5bc49b5067471710ab972a362770bb8e9169

2023-10-23 10:35 UTC, aparcar commented
@PolynomialDivision now that you got commit access, could you please give this another go and merge it :)?

2024-10-18 11:42 UTC, BKPepe commented
@PolynomialDivision 👀 Kind reminder, please. This is blocking also https://github.com/openwrt/packages/pull/18875