kernel: Update net-ethernet-mtk_eth_soc-add-flow-offloading-support.patch to include ipv6 support
openwrt/openwrt pull request #4918
Opened 2022-01-04 15:28 UTC by db260179

Original commit https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=f07fe36f22fcf3f3da4e0440dfc5c39516e2cb55
added flow offloading support but was missing ipv6 support.

This commit updates the existing patch to include ipv6 support aswell

Signed-off-by: David Bentham <db260179@gmail.com>

2022-01-04 15:32 UTC, db260179 commented
Has been confirmed to be working in https://forum.openwrt.org/t/mt7621-21-02-master-feedback-firmware-image-test-ipv6-offload-and-disabled-flow-control/115697/25 thread

2022-01-04 17:57 UTC, dangowrt commented
Please do not re-write backported patches as that will increase the maintainance burden. In this case, the patch you are editing has already been accepted to upstream Linux, so we have to make another patch on top, which (ideally) you should also submit upstream via the [Linux netdev mailing list](https://www.kernel.org/doc/html/latest/networking/netdev-FAQ.html).

2022-01-04 18:44 UTC, db260179 commented
> Please do not re-write backported patches as that will increase the maintainance burden. In this case, the patch you are editing has already been accepted to upstream Linux, so we have to make another patch on top, which (ideally) you should also submit upstream via the [Linux netdev mailing list](https://www.kernel.org/doc/html/latest/networking/netdev-FAQ.html).

Ok, wasn't sure. thanks for confirming. will change to a separate patch.

2022-01-05 09:40 UTC, nbd168 commented
Please remove the FLOW_ACT_MANGLE_HDR_TYPE_IP6 related code. The hardware does not support IPv6 NAT, only routing.

2022-01-05 11:15 UTC, db260179 commented
> Please remove the FLOW_ACT_MANGLE_HDR_TYPE_IP6 related code. The hardware does not support IPv6 NAT, only routing.

Doesn't mt7621 soc support IPV6 NAT support? or is just the mt7530 switch that applies here?

2022-01-05 11:28 UTC, nbd168 commented
The hardware offload is done by the PPE in the SoC (not the MT7530 switch). All supported SoCs only support IPv6 routing, no NAT. The offload related data structure also doesn't have space for the modified addresses.

2022-01-05 13:18 UTC, nbd168 commented
Looks good to me

2022-01-05 13:18 UTC, nbd168 commented
Except that the patch is in the 'backports-5.10' folder when it hasn't even been submitted to Linux upstream yet.

2022-01-05 13:33 UTC, db260179 commented
> Except that the patch is in the 'backports-5.10' folder when it hasn't even been submitted to Linux upstream yet.

Should this be moved to 'pending-5.10' folder?
Please advise the best way to get added?

Thanks

2022-01-06 11:16 UTC, rsalvaterra commented
> Should this be moved to 'pending-5.10' folder? Please advise the best way to get added?

If it's the exact same patch you'll be sending upstream, yes, it should be in the `pending-5.10` directory. However, the commit message could use some love. How about this?

"Add the missing IPv6 flow offloading support for routing only, as HW NAT is done by the PPE and it doesn't support mangling."

Tip: commit messages are supposed to be written in imperative form.

2022-02-10 12:12 UTC, eduardo010174 commented
It's ready for merge? Why it's not merged?

2022-02-12 23:46 UTC, vbujoreanu commented
Are there any plans to merge this? It seems pretty useful.

2022-02-13 00:07 UTC, dangowrt requested changes
Please line-wrap the commit message body at 72 characters (currently 125 chars which is too much). It would also be better to split it into two sentences, such as:
```
net: ethernet: mtk_eth_soc: add ipv6 flow offload support 

Add the missing IPv6 flow offloading support for routing only.
Hardware flow offloading is done by the packet processing engine (PPE)
of the Ethernet MAC and as it doesn't support mangling of IPv6 packets,
IPv6 NAT cannot be supported.

Signed-off-by: ...
```

2022-02-13 10:10 UTC, db260179 commented
> Please line-wrap the commit message body at 72 characters (currently 125 chars which is too much). It would also be better to split it into two sentences, such as:
> 
> ```
> net: ethernet: mtk_eth_soc: add ipv6 flow offload support 
> 
> Add the missing IPv6 flow offloading support for routing only.
> Hardware flow offloading is done by the packet processing engine (PPE)
> of the Ethernet MAC and as it doesn't support mangling of IPv6 packets,
> IPv6 NAT cannot be supported.
> 
> Signed-off-by: ...
> ```
Updated commit message as per request.

2022-02-13 12:32 UTC, dangowrt approved these changes

2022-02-13 13:38 UTC, eduardo010174 approved these changes

2022-02-14 08:38 UTC, vbujoreanu approved these changes

2022-02-17 13:46 UTC, rsalvaterra commented
So far, I haven't seen this patch hitting the linux-netdev mailing list. I'd really like to see this applied upstream before being backported to OpenWrt (bonus points if it's eligible for cc: stable, but I'm not keeping my hopes up, since it can be considered a new feature). This is my personal policy regarding kernel patches, but other devs may disagree, of course. Thoughts, @dangowrt, @nbd168?

2022-02-19 14:36 UTC, nbd168 commented
Applied, thanks. I will take care of upstreaming this, as I'm already working on other PPE/offload related things.

2022-02-19 14:36 UTC, closed without merging

2022-02-25 22:35 UTC, Mushoz commented
I am still experiencing packet loss with hardware flow offload enabled with a recent build that has this patch included (OpenWrt SNAPSHOT r18944-aae7af4219). I am experiencing this with PPPoE enabled though, not sure if that has anything to do with it? Using a mt7622 device.

2024-05-03 14:09 UTC, xupefei commented
> I am still experiencing packet loss with hardware flow offload enabled with a recent build that has this patch included (OpenWrt SNAPSHOT r18944-aae7af4219). I am experiencing this with PPPoE enabled though, not sure if that has anything to do with it? Using a mt7622 device.

This patch has been merged to upstream (Linux kernel) but only in version 5.19 and up: https://github.com/torvalds/linux/commit/817b2fdf166766b462a034a8cc87d0b53c0054ec. However OpenWrt 23 is on kernel 5.15.
The upcoming OpenWrt 24 (which will be on 6.1 or 6.6 kernels) will have this feature.