mediatek mt7622: fix 300mhz typo in dts
openwrt/openwrt pull request #4923
Opened 2022-01-06 00:40 UTC by Jip-Hop

Since https://github.com/openwrt/openwrt/pull/4440 has been closed, this is another attempt to merge just the fix by @selanf for the 300mhz typo in dts. As mentioned by @dangowrt on the [OpenWRT forum](https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/1229) there is no benefit in leaving 30mhz as the lowest frequency.

2022-01-06 01:02 UTC, dangowrt commented
Please write a more elaborate commit description and also add that to the patch file itself, so it becomes ready for submission to upstream Linux. Take a look at existing commits doing similar things here to get an idea what the commit title and description of the patch file should look like: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/arch/arm64/boot/dts/mediatek

2022-01-06 09:38 UTC, Jip-Hop commented
Thanks for the pointers! 🙂 

My aim was to preserve the commit by @selanf from august. I can't chage his commit message. What I could do is add another commit with proper discription in the commit message and patch file. Or I could branch off from master, fix the typo, add description and make a new pull request with just one commit, but then the commit by @selanf won't be preserved...

Please let me know what would be the way forward.

2022-01-06 18:19 UTC, 123testing1237 commented
So many protocols for something so simple, just accept it.

@hauke @aparcar @BKPepe @dangowrt @stintel

2022-01-06 18:21 UTC, 123testing1237 commented
So many protocols for something so simple, just accept it or you who know how to send a commind, fix it.

@hauke @aparcar @BKPepe @dangowrt @stintel

2022-01-06 18:22 UTC, stintel commented
> Thanks for the pointers! slightly_smiling_face
> 
> My aim was to preserve the commit by @selanf from august. I can't chage his commit message. What I could do is add another commit with proper discription in the commit message and patch file. Or I could branch off from master, fix the typo, add description and make a new pull request with just one commit, but then the commit by @selanf won't be preserved...
> 
> Please let me know what would be the way forward.

You *can* change the commit message. When you do, add a SoB line for yourself, preceded by a line [what you changed], e.g. https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=ef1a64caf40e589a5c13cfc68032b3f95d02b715

2022-01-07 15:30 UTC, OpenWrtDEVnoobs approved these changes

2022-01-07 15:32 UTC, OpenWrtDEVnoobs commented
@dangowrt Can't you create and submit the commit?

2022-01-07 15:33 UTC, BKPepe commented
No, because of your nickname on GitHub. 😈😈

2022-01-07 15:39 UTC, OpenWrtDEVnoobs commented
The truth hurts.

2022-01-07 15:48 UTC, stintel requested changes
As previously requested: improve the commit message and lose the merge commit.

2022-01-08 06:50 UTC, oldium commented
Just a note - #4932 is identical and has a better commit message already. There are many prefixes in the commit title, though, but the description is definitely better.

2022-01-08 10:16 UTC, Jip-Hop commented
I should be able to apply the requested changes tomorrow 🙂

2022-01-09 12:37 UTC, stintel requested changes

2022-01-09 12:37 UTC, stintel commented on target/linux/mediatek/patches-5.10/721-dts-mt7622-mediatek-fix-300mhz.patch
> +As mentioned @dangowrt on the OpenWRT forum there is no benefit in
Please spell OpenWrt correctly.

2022-01-09 12:38 UTC, Jip-Hop commented
I applied the requested changes. Hopefully I did it right :)

Used the description from pull request https://github.com/openwrt/openwrt/pull/4932.

2022-01-09 12:39 UTC, stintel commented
Also use line breaks in the commit message. See https://openwrt.org/submitting-patches#submission_guidelines

2022-01-09 12:45 UTC, stintel commented
LGTM. I'll let @dangowrt have the final say as he requested the changes.

2022-01-09 12:48 UTC, stintel approved these changes

2022-01-09 14:53 UTC, dangowrt commented
Cherry picked to https://github.com/openwrt/openwrt/commit/693958497a8cd55aa2eaba602ac5ab72d23fc1a8

2022-01-09 14:53 UTC, closed without merging