ar71xx: add support for LigoWawe LigoDLB Propeller 5
openwrt/openwrt pull request #593
Opened 2018-01-02 22:00 UTC by robimarko

LigoDLB Propeller 5 is 5 GHz AP based on Qualcomm AR9342 rev 2.
https://www.ligowave.com/products/ligodlb-propeller-5
Specifications:

560/450/225/40 MHz (CPU/DDR/AHB/REF)
64MB of RAM
16 MB of FLASH (8 MB usable because of dual image)
1x 10/100 Mbps Ethernet with 24V POE IN
6x LED, 1x button
UART header on PCB
JTAG header on PCB

Currently not working:

Update from oficial web interface
LigoWawe uses they custom app to flash images and therefore flashing LEDE images does not work.

Flash instruction:

Set PC to fixed ip address 192.168.2.254
Download lede-ar71xx-generic-dlb-5-squashfs-sysupgrade.bin and rename it to fwupdate.bin
Start a tftp server with the file fwupdate.bin in its root directory
Turn off the router
Press and hold Reset button
Turn on router with the reset button pressed and wait 6 or more seconds
LED-s will start flashing and after it is done device should boot into LEDE.

Device specifics:
Bootloader has Netconsole built it,you can access it by holding reset button while powering on for at least 3 seconds and less than 6 seconds.
It can be usefull for recovery as serial pads are on PCB and device is not meant to be opened at all.

8 MB of 16 MB of SPI flash is usable.
That is due to LigoWawe using dual firmware bootloader.
So if after 3 boots boot counter is not reset bootloader will boot the other firmware image.
Due to that at boot boot counter for used firmware image is reset to 0.

Signed-off-by: Robert Marko robimarko@gmail.com

2018-01-30 11:06 UTC, robimarko commented
@pepe2k Any chance on merging this?
It has been open since October

2018-02-07 22:18 UTC, pepe2k requested changes
Hi @robimarko,

Please, see my comments inline, below.

Also, please read our [submitting patches rules](https://lede-project.org/submitting-patches), make sure your pull request follows them (hints: "commit description must have less than 75 characters per line" and your SoB line is wrong) and rebase the code on current master.

Cheers,
Piotr

2018-02-07 22:18 UTC, pepe2k commented on target/linux/ar71xx/files/arch/mips/ath79/mach-ligodlb-5.c
> +	ath79_register_mdio(0, 0x0);
Why do you register both mdio buses?

2018-02-07 22:18 UTC, pepe2k commented on target/linux/ar71xx/files/arch/mips/ath79/machtypes.h
> +	ATH79_MACH_LIGODLB_5,			/* LigoDLB Propeller 5 */
Please, keep alphabetical order.

2018-02-07 22:18 UTC, pepe2k commented on target/linux/ar71xx/image/generic.mk
> +  endef
You have a mistake here (indentation).

2018-02-07 22:18 UTC, pepe2k commented on target/linux/ar71xx/mikrotik/config-default
> +# CONFIG_ATH79_MACH_LIGODLB_5 is not set
Please, rebase your code on current master.

2018-02-07 22:18 UTC, pepe2k commented on target/linux/ar71xx/nand/config-default
> +# CONFIG_ATH79_MACH_LIGODLB_5 is not set
Please, rebase your code on current master.

2018-02-07 22:18 UTC, pepe2k commented on target/linux/ar71xx/base-files/lib/ar71xx.sh
> +	*"LigoDLB Propeller 5")
Please, keep alphabetical order.

2018-02-07 22:18 UTC, pepe2k commented on target/linux/ar71xx/files/arch/mips/ath79/mach-ligodlb-5.c
> +#include <linux/pci.h>
Please, drop unused/not required headers.

2018-02-07 22:18 UTC, pepe2k commented on target/linux/ar71xx/files/arch/mips/ath79/mach-ligodlb-5.c
> +	u8 *wifi_mac = (u8 *) KSEG1ADDR(0x1fff1002);
This is not required, that's the regular MAC offset, you can call `ath79_register_wmac(ee, NULL);`.

2018-02-07 22:59 UTC, robimarko commented
@pepe2k Your comments have been addressed.
I apologize for obvious mistakes.
This was my first attempt at supporting devices and since then I have gotten better and a couple of a couple of my PRs adding support for other devices have been merged.

Thanks

2018-02-14 13:18 UTC, pepe2k commented
> > @pepe2k Your comments have been addressed.

Thanks but at least my first comment about your changes in `target/linux/ar71xx/base-files/etc/board.d/01_leds ` hasn't been addressed.

Cheers,
Piotr

2018-02-14 13:30 UTC, pepe2k commented
> Sorry,but I have no idea how to properly configure it.
> Do you have a example that has properly configured RSSI leds?

Have a look for example at N5Q or fritz300e.

Cheers,
Piotr

2018-02-14 16:18 UTC, robimarko commented
Thanks,it should be correct now.
Also,conflict in 01_leds should be resolved

2018-07-30 14:11 UTC, blogic commented
@robimarko sorry but  the patch lost traction and no longer applies. If you would still like to see it getting merged, please rebase push and then reopen the patch.

2018-07-30 14:11 UTC, closed without merging

2018-07-30 14:32 UTC, robimarko commented
I can rebase it but I no longer have access to the device to test out.