ar71xx: add support for D-Link DAP-1533
openwrt/openwrt pull request #623
Opened 2018-01-07 08:03 UTC by Tarask1n

Access point D-Link DAP-1533:
- 4x 1Gbit port switch
- 1x 450Mbit 2.4/5GHz WiFi (3 internal antennas)
- 1x USB 2.0 port

It based on DB120 board:
- SoC Atheros AR7370 (AR9344 w/o WiFi) 
- 8 MiB flash
- 128 MiB ram 
- Ethernet switch AR8327N
- WiFi 2.4/5GHz AR9380

It could be easy converted to 1GBit router with Openwrt.
More detailed info I described there https://wiki.openwrt.org/toh/d-link/d-link_dap-1533_a1.

All works fine LED, buttons, Ethernet, WiFi, USB. But I've faced an issue. When I flashed an image to 16MiB flash the available space for software still left 3.7 Mb as an 8MiB flash. May be I've missed something in configuration.

Thanks in advance.

Signed-off-by: Taras Gavrylenko <gavrylenko.taras@gmail.com>

2018-01-07 09:09 UTC, heinzek requested changes
Hi @Tarask1n,

Please add commit message and add 'CONFIG_ATH79_MACH_DAP_1533_A1=y' to file 'target/linux/ar71xx/config-4.9'

2018-01-07 11:45 UTC, Tarask1n commented
Hi @heinzek,

I've done all changes that you requested, but compilation on project side was failed. On my side all Ok. Plaese see log:

```
Sun Jan  7 09:40:17 2018 kern.notice kernel: [    0.000000] Linux version 4.9.73 (taras@taras-ubuntu) (gcc version 5.5.0 (OpenWrt GCC 5.5.0 r5683-3c7eec6) ) #0 Sun Jan 7 07:40:14 2018
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.000000] MyLoader: sysp=a140869b, boardp=59b43936, parts=b9d7c247
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] bootconsole [early0] enabled
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] CPU0 revision is: 0001974c (MIPS 74Kc)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] SoC: Atheros AR9344 rev 2
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] Determined physical RAM map:
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000]  memory: 08000000 @ 00000000 (usable)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] Initrd not found or empty - disabling initrd
Sun Jan  7 09:40:17 2018 kern.warn kernel: [    0.000000] OF: fdt:No valid device tree found, continuing without
Sun Jan  7 09:40:17 2018 kern.warn kernel: [    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
Sun Jan  7 09:40:17 2018 kern.warn kernel: [    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] Zone ranges:
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] Movable zone start for each node
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] Early memory node ranges
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.000000] On node 0 totalpages: 32768
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.000000] free_area_init_node: node 0, pgdat 804827d4, node_mem_map 81000020
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.000000]   Normal zone: 256 pages used for memmap
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.000000]   Normal zone: 0 pages reserved
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.000000]   Normal zone: 32768 pages, LIFO batch:7
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.000000] pcpu-alloc: [0] 0
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 32512
Sun Jan  7 09:40:17 2018 kern.notice kernel: [    0.000000] Kernel command line:  board=DAP-1533-A1 mtdparts=spi0.0:128k(uboot)ro,64k(nvram)ro,7680k(firmware),192k(lang)ro,64k(mac)ro,64k(art)ro console=ttyS0,115200 rootfstype=squashfs noinitrd
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] Writing ErrCtl register=00000000
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] Readback ErrCtl register=00000000
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] Memory: 124744K/131072K available (3245K kernel code, 167K rwdata, 824K rodata, 300K init, 213K bss, 6328K reserved, 0K cma-reserved)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] NR_IRQS:51
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] Clocks: CPU:550.000MHz, DDR:400.000MHz, AHB:200.000MHz, Ref:40.000MHz
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 6950037990 ns
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.000010] sched_clock: 32 bits at 275MHz, resolution 3ns, wraps every 7809031678ns
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.008710] Calibrating delay loop... 274.02 BogoMIPS (lpj=1370112)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.081674] pid_max: default: 32768 minimum: 301
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.086934] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.094321] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.104842] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.115841] futex hash table entries: 256 (order: -1, 3072 bytes)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.123235] NET: Registered protocol family 16
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.129773] MIPS: machine is D-Link DAP-1533 rev. A1
Sun Jan  7 09:40:17 2018 kern.warn kernel: [    0.137319] registering PCI controller with io_map_base unset
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.401971] PCI host bridge to bus 0000:00
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.406604] pci_bus 0000:00: root bus resource [mem 0x10000000-0x13ffffff]
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.414270] pci_bus 0000:00: root bus resource [io  0x0000]
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.420494] pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.428058] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.436932] pci 0000:00:00.0: [168c:0030] type 00 class 0x028000
Sun Jan  7 09:40:17 2018 kern.err kernel: [    0.436943] pci 0000:00:00.0: invalid calibration data
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.442692] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x0001ffff 64bit]
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.442745] pci 0000:00:00.0: reg 0x30: [mem 0x00000000-0x0000ffff pref]
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.442823] pci 0000:00:00.0: supports D1
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.442833] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.443060] pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 00
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.443089] pci 0000:00:00.0: BAR 0: assigned [mem 0x10000000-0x1001ffff 64bit]
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.451290] pci 0000:00:00.0: BAR 6: assigned [mem 0x10020000-0x1002ffff pref]
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.459352] pci 0000:00:00.0: using irq 40 for pin 1
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.465632] clocksource: Switched to clocksource MIPS
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.472382] NET: Registered protocol family 2
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.478125] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.485963] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.493059] TCP: Hash tables configured (established 1024 bind 1024)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.500250] UDP hash table entries: 256 (order: 0, 4096 bytes)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.506811] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
Sun Jan  7 09:40:17 2018 kern.info kernel: [    0.514066] NET: Registered protocol family 1
Sun Jan  7 09:40:17 2018 kern.debug kernel: [    0.519021] PCI: CLS 0 bytes, default 32
Sun Jan  7 09:40 [...]

2018-02-20 13:30 UTC, pepe2k requested changes
Hello @Tarask1n,

Your commit description (not Pull Request message) should contain hardware description and flashing instruction.

Also, please have a look at my comments inline, below.

Cheers,
Piotr

2018-02-20 13:30 UTC, pepe2k commented on target/linux/ar71xx/files/arch/mips/ath79/mach-dap-1533-a1.c
> +		.name		= "d-link:green:power",
Please, use "board:color:function" LED names (don't forget to update them in user space scripts).

2018-02-20 13:30 UTC, pepe2k commented on target/linux/ar71xx/files/arch/mips/ath79/mach-dap-1533-a1.c
> +		.desc		= "WPS button",
Please, align indentation (you have different one above).

2018-02-20 13:30 UTC, pepe2k commented on target/linux/ar71xx/files/arch/mips/ath79/mach-dap-1533-a1.c
> +static struct flash_platform_data dap1533a1_flash_data = {
This shouldn't be required, please drop it.

2018-02-20 13:30 UTC, pepe2k commented on target/linux/ar71xx/image/generic.mk
> +  SUPPORTED_DEVICES := dap-1533-a1
Your image doesn't use metadata, drop this line.

2018-02-20 13:30 UTC, pepe2k commented on target/linux/ar71xx/image/generic.mk
> +  IMAGE/sysupgrade.bin := append-kernel | pad-to 64k | append-rootfs | pad-rootfs | check-size $$$$(IMAGE_SIZE)
This is default recipe, drop this line please.

2018-02-20 13:30 UTC, pepe2k commented on target/linux/ar71xx/files/arch/mips/ath79/mach-dap-1533-a1.c
> +	ath79_eth0_pll_data.pll_1000 = 0x06000000;
Are you sure about this value? Have you made some throughput tests to check if RGMII works correctly? Can you check what value sets vendor firmware/U-Boot?

2018-07-18 15:47 UTC, mkresin commented
Please reopen the PR if you had the time to address the requested changes.

2018-07-18 15:47 UTC, closed without merging