mvebu: add support for MACCHIATObin (cortex-a72)
openwrt/openwrt pull request #822
Opened 2018-03-26 13:23 UTC by damirsamardzic

Add initial support for Marvell MACCHIATObin, cortex-a72 based Marvell
ARMADA 8040 Community board. Comes in two forms: Single Shot and Double
Shot.

Specifications:
- Quad core Cortex-A72 (up to 2GHz)
- DDR4 DIMM slot with optional ECC and single/dual chip select support
- Dual 10GbE (1/2.5/10GbE) via copper or SFP
  2.5GbE (1/2.5GbE) via SFP
  1GbE via copper
- SPI Flash
- 3 X SATA 3.0 connectors
- MicroSD connector
- eMMC
- PCI x4 3.0 slot
- USB 2.0 Headers (Internal)
- USB 3.0 connector
- Console port (UART) over microUSB connector
- 20-pin Connector for CPU JTAG debugger
- 2 X UART Headers
- 12V input via DC Jack
- ATX type power connector
- Form Factor: Mini-ITX (170 mm x 170 mm)

More details at http://macchiatobin.net

Booting from micro SD card:
 1. reset U-Boot environment:
      env default -a
      saveenv

 2. prepare U-Boot with boot script:
      setenv bootcmd "load mmc 1:1 0x4d00000 boot.scr; source 0x4d00000"
      saveenv

    or manually:
      setenv fdt_name armada-8040-mcbin.dtb
      setenv image_name Image
      setenv bootcmd 'mmc dev 1; ext4load mmc 1:1 $kernel_addr $image_name;ext4load mmc 1:1 $fdt_addr $fdt_name;setenv   bootargs $console root=/dev/mmcblk1p2 rw rootwait; booti $kernel_addr - $fdt_addr'
      saveenv

Signed-off-by: Damir Samardzic <damir.samardzic@sartura.hr>

2018-03-28 18:18 UTC, tmn505 requested changes
Otherwise looks good.
Are the SFP ports working?

2018-03-28 18:18 UTC, tmn505 commented on target/linux/mvebu/cortexa72/config-default
> +CONFIG_ARMADA_37XX_CLK=y
You can drop this symbol,

2018-03-28 18:18 UTC, tmn505 commented on target/linux/mvebu/cortexa72/config-default
> +CONFIG_ARM_ARMADA_37XX_CPUFREQ=y
this also,

2018-03-28 18:18 UTC, tmn505 commented on target/linux/mvebu/cortexa72/config-default
> +CONFIG_PCI_AARDVARK=y
this can be marked as not set,

2018-03-28 18:18 UTC, tmn505 commented on target/linux/mvebu/cortexa72/config-default
> +CONFIG_PINCTRL_ARMADA_37XX=y
this can be dropped,

2018-03-28 18:18 UTC, tmn505 commented on target/linux/mvebu/cortexa72/config-default
> +CONFIG_SPI_ARMADA_3700=y
and this one.
I'm wondering if `I2C_MUX_PCA954x` shouldn't be enabled => https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/arch/arm64/boot/dts/marvell/armada-8040-mcbin.dts?h=v4.14.30#n140.

2018-03-28 18:18 UTC, tmn505 commented on target/linux/mvebu/image/cortex-a72.mk
> +  DEVICE_PACKAGES := e2fsprogs ethtool mkf2fs kmod-fs-vfat kmod-usb2 kmod-usb3 kmod-usb-storage kmod-mmc mmc-utils pciutils
Remove packages from community repository `mmc-utils`, `pciutils`. The USB drivers are built in the kernel, should be safe to remove them.

2018-03-30 05:41 UTC, damirsamardzic commented
Thanks for the review, I have tested with proposed changes, looks OK.
SFP ports don't work in this PR.

2018-03-30 10:35 UTC, hauke commented
Please squash this together into one commit

2018-03-30 12:49 UTC, tmn505 approved these changes
Now it's all good.

2018-03-31 14:37 UTC, hauke commented
Thank you for the patches, it was applied to master.

2018-03-31 14:37 UTC, closed without merging