ramips: add support for Ravpower WD03
openwrt/openwrt pull request #872
Opened 2018-04-15 21:17 UTC by badzz

The RavPower WD03 is a battery powered SD card reader and a USB port.

Specifications:
MediaTek MT7620N
Battery 6000mah
802.11bg
1x 10/100 Mbps Ethernet
1x USB 2.0 (Type-A)
Ram : 32 Mb
8 MB Flash
Sd Card reader

I had to change the hotplug script as inserting an SD card triggers a button event (which is useful to mount it automatically) but make openwrt enter failsafe mode.

Signed-off-by: badzz <mbadaire@gmail.com>

Thanks for your contribution to OpenWrt!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://lede-project.org/submitting-patches

Please remove this message before posting the pull request.

2018-04-18 06:41 UTC, mkresin commented
> I had to change the hotplug script as inserting an SD card triggers a button event (which is useful to mount it automatically) but make openwrt enter failsafe mode.

It is intentional that any button triggers the failsafe during **preinit**.

It even allows you to use the sd-card trick to enter our failsafe system. Is the issue you're fixing related to the fact that the button event is send if a sd-card is present during boot (not inserted during boot)?.

2018-04-18 06:58 UTC, mkresin requested changes
Please use ```git commit --amend``` to add changes to your commit. Use ```git push --force``` to overwrite your github repository/branch. The PR will afterwards update automatically. Please don't close this PR and open a new one.

2018-04-18 06:58 UTC, mkresin commented on target/linux/ramips/base-files/lib/ramips.sh
> +        *"WD-03")
Drop the WD-03 from this file and use the board compatible string from the dts as userspace boardname, as all recently added boards are do.

2018-04-18 06:58 UTC, mkresin commented on target/linux/ramips/dts/WD03.dts
> +
Please include <[dt-bindings/gpio/gpio.h](http://lxr.free-electrons.com/source/include/dt-bindings/gpio/gpio.h?v=4.4)> here as well and keep alphabetical order.

Use the GPIO_ACTIVE_LOW and GPIO_ACTIVE_HIGH macros afterwards in stead of 1 and 0 in the gpio parameters.

Check the recent [ramips board additions](https://github.com/lede-project/source/commits/master/target/linux/ramips) for examples.

2018-04-18 06:58 UTC, mkresin commented on target/linux/ramips/dts/WD03.dts
> +	compatible = "WD03", "ralink,mt7620a-soc";
it has to be `compatible = "<manufacture>,<boardname>", "ralink,mt7620a-soc";` check the other dts files for examples

2018-04-18 06:58 UTC, mkresin commented on target/linux/ramips/dts/WD03.dts
> +	model = "WD03";
We should mention the manufacture here as well.

2018-04-18 06:58 UTC, mkresin commented on target/linux/ramips/dts/WD03.dts
> +&gpio0 {
can be dropped, no `gpio0` pin is used in the dts.

2018-04-18 06:58 UTC, mkresin commented on target/linux/ramips/dts/WD03.dts
> +&gpio1 {
can be dropped, no `gpio1` pin is used in the dts.

2018-04-18 06:58 UTC, mkresin commented on target/linux/ramips/dts/WD03.dts
> +		partition@0 {
please mark the bootloader partition as read-only as well.

2018-04-18 06:58 UTC, mkresin commented on target/linux/ramips/dts/WD03.dts
> +			reg = <0xff0000 0x10000>;
copy paste leftover? I don't see any reference to this partition and it is at offset 15,93MB of the 8 MB flash chip.

2018-04-18 06:58 UTC, mkresin commented on target/linux/ramips/dts/WD03.dts
> +			ralink,group = "wled","ephy","i2c";
`ralink,group = "wled", "ephy"; ` only. none of the pins from i2c group are used as GPIOs in your dts.

2018-04-18 06:59 UTC, mkresin commented
Your commit message misses an installation guide as it is required according to https://openwrt.org/submitting-patches. Have a look at the [recent additions](https://git.openwrt.org/?p=openwrt/openwrt.git&a=search&h=HEAD&st=commit&s=add+support+for) for some examples.

2018-04-18 08:31 UTC, badzz commented
@mkresin  : hotplug preinit. Yes I wanted to be able to start the "router" without having an SD Card. If no sd card it systematically jump in failsafe. It is not very convenient IMHO.

2018-04-18 09:17 UTC, mkresin commented
@badzz IMHO you should remove the "button" as it isn't really a button. It is just a GPIO which shows a state and not a button setting a state.

2018-04-18 12:11 UTC, badzz commented
@mkresin : I thought of this but it is very convenient to do the auto mount in the hotplug button script when the sd card is inserted. Is there an another way to have a script being run when this event happens ?
PS: I am doing the other modifications requested

2018-04-18 12:41 UTC, badzz commented
Applied modification requested - I had this changes ready for a long time and did not see that things changed since. 
Thanks

2018-04-18 13:15 UTC, mkresin commented
> I thought of this but it is very convenient to do the auto mount in the hotplug button script when the sd card is inserted.

Isn't their anything logged in dmesg or logread at the time the card is inserted? If so, it isn't different to automounting usb flash drives.

If not, it might be that card detection isn't implemented [in the driver](https://github.com/openwrt/openwrt/tree/master/target/linux/ramips/files-4.14/drivers/mmc/host/mtk-mmc). Furthermore, it looks like your board doesn't use the "default" card detect pin (GPIO#50). Could be that just the support for custom card detect pins is missing.

2018-04-18 15:13 UTC, badzz commented
@mkresin: No .. nothing is loggued unfortunately *sigh*
How does it work with the default card detect ? you get an another hotplug type of events ? (eg: block events)

2018-04-19 15:54 UTC, badzz commented
@mkresin : Should I remove the hotplug script modification for now to have this merged and I will come back with something better for the SD card detection ?
In the meantime, people will have an image to use and I will warn that you need a sdcard in the slot to make it boot.
Is that ok with you ? 
Thanks

2018-04-19 19:06 UTC, mkresin commented
Yes, please remove the hotplug script modification and the sdcard button.

Furthermore, please test you PR. I'm quite sure you can not select your image in menuconfig due to:

2018-04-19 19:07 UTC, mkresin requested changes

2018-04-19 19:07 UTC, mkresin commented on target/linux/ramips/image/mt7620.mk
> +define Device/wd03
need to be `define Device/ravpower_wd03`.

2018-04-20 07:47 UTC, badzz commented
I made the modifications but kept the button for now. It makes it very difficult to use if we do not have an event when the card is inserted.
The hotplug script modificiation has been reverted, the mk the file fixed and tested the image, it works fine.

2018-04-20 11:46 UTC, mkresin commented
I found some more issues.

First of all, we need your full (real)name in Signed-off-by. Some applies to the [commits from line](https://github.com/openwrt/openwrt/pull/872.patch).

At the moment I'm kind of surprised that the sd-card works at all as it isn't enabled in your dts. The following is missing:

```
&sdhci {
       status = "okay";
       cd-gpios = <&gpio2 2 GPIO_ACTIVE_HIGH>;
};
```

2018-04-20 15:56 UTC, mkresin commented
I had a brief look [at the driver](https://github.com/openwrt/openwrt/blob/master/target/linux/ramips/files-4.14/drivers/mmc/host/mtk-mmc/sd.c) and it seem to me polling is supported. You can enable polling by using the `mediatek,cd-poll` devicetree property:

```
&sdhci {
       status = "okay";
       mediatek,cd-poll;
};
```

Let me know if detection works with the change. Still not as good as adding support for the gpio card detect but better than having nothing.

2018-04-20 21:52 UTC, mkresin commented
> Nonetheless, sd card does not work on my builds and it still work on my lede config...
When I load ohci, it doesn't recognize anything.

I'm not sure if I got you right. Are you saying it worked with an old LEDE version but doesn't work with current OpenWrt (which is in fact LEDE + ongoing development).

If yes, the whole card detect + block event was kind of a meta discussion, right?

How should we proceed? Disable sdcard support and mention it as not working in the commit message? Or do you prefer to close this PR for now and come back if you managed to get it working?

2018-04-20 22:27 UTC, closed without merging

2018-04-29 20:50 UTC, badzz commented
USB issue was strange, I rebased to most current master and everything works now
#912 created