uboot-imx: bump to 2018.03 which fixes the build issues with fdt64_t redefinitions
openwrt/openwrt pull request #904
Opened 2018-04-27 12:19 UTC by v-vid

* change mx6qsabresd to mx6qsabres to match defconfig name
* merge wanboard profiles since there is only one defconfig for target device
* remove unnecessary patches

Signed-off-by: Vladimir Vid <vladimir.vid@sartura.hr>

2018-04-30 09:14 UTC, lperkov commented
Ack from me.

2018-05-05 06:28 UTC, blogic commented
the patches are unnecessary as they are already upstream ?

2018-05-07 10:12 UTC, v-vid commented
All changes contained in the removed patches are mainlined except these two:

* 102-compiler_gcc-prevent-redefining-attributes.patch - removes some warning messages for the FreeBSD during the compile time.
* 110-wandboard-owrt-env.patch - conflicts with the updated wandboard.h and we should target mainline approach for booting the device

The following were breaking during compile and were removed since they don't actually affect any functionality. Build for all u-boot targets was successfully tested afterwards.

2018-05-07 20:01 UTC, tmn505 commented
Works fine on CuBoxTV (I4P TV-300-D).

2018-06-09 18:44 UTC, hauke commented
This does not compile for me I ma getting this error message:
```
In file included from include/common.h:48:0,
                 from common/image-fit.c:18:
common/image-fit.c: In function 'fit_get_debug':
common/image-fit.c:115:40: warning: implicit declaration of function 'fit_get_name'; did you mean 'eth_get_name'? [-Wimplicit-function-declaration]
        prop_name, (ulong)fit, noffset, fit_get_name(fit, noffset, NULL),
                                        ^
include/log.h:135:26: note: in definition of macro 'debug_cond'
    printf(pr_fmt(fmt), ##args); \
                          ^~~~
common/image-fit.c:114:2: note: in expansion of macro 'debug'
  debug("Can't get '%s' property from FIT 0x%08lx, node: offset %d, name %s (%s)\n",
  ^~~~~
common/image-fit.c:116:8: warning: implicit declaration of function 'fdt_strerror'; did you mean 'flash_perror'? [-Wimplicit-function-declaration]
        fdt_strerror(err));
        ^
include/log.h:135:26: note: in definition of macro 'debug_cond'
    printf(pr_fmt(fmt), ##args); \
                          ^~~~
common/image-fit.c:114:2: note: in expansion of macro 'debug'
  debug("Can't get '%s' property from FIT 0x%08lx, node: offset %d, name %s (%s)\n",
  ^~~~~
In file included from include/linux/bug.h:7:0,
                 from include/common.h:26,
                 from common/image-fit.c:18:
common/image-fit.c:114:8: warning: format '%s' expects argument of type 'char *', but argument 5 has type 'int' [-Wformat=]
  debug("Can't get '%s' property from FIT 0x%08lx, node: offset %d, name %s (%s)\n",
        ^
include/linux/printk.h:37:21: note: in definition of macro 'pr_fmt'
 #define pr_fmt(fmt) fmt
                     ^~~
include/log.h:142:2: note: in expansion of macro 'debug_cond'
  debug_cond(_DEBUG, fmt, ##args)
  ^~~~~~~~~~
common/image-fit.c:114:2: note: in expansion of macro 'debug'
  debug("Can't get '%s' property from FIT 0x%08lx, node: offset %d, name %s (%s)\n",
  ^~~~~
common/image-fit.c:114:8: warning: format '%s' expects argument of type 'char *', but argument 6 has type 'int' [-Wformat=]
  debug("Can't get '%s' property from FIT 0x%08lx, node: offset %d, name %s (%s)\n",
        ^
include/linux/printk.h:37:21: note: in definition of macro 'pr_fmt'
 #define pr_fmt(fmt) fmt
                     ^~~
include/log.h:142:2: note: in expansion of macro 'debug_cond'
  debug_cond(_DEBUG, fmt, ##args)
  ^~~~~~~~~~
common/image-fit.c:114:2: note: in expansion of macro 'debug'
  debug("Can't get '%s' property from FIT 0x%08lx, node: offset %d, name %s (%s)\n",
  ^~~~~
common/image-fit.c: In function 'fit_get_subimage_count':
common/image-fit.c:135:13: warning: implicit declaration of function 'fdt_next_node' [-Wimplicit-function-declaration]
   noffset = fdt_next_node(fit, images_noffset, &ndepth);
             ^~~~~~~~~~~~~
common/image-fit.c: In function 'fit_print_contents':
common/image-fit.c:176:8: warning: implicit declaration of function 'fit_get_desc'; did you mean 'fit_get_debug'? [-Wimplicit-function-declaration]
  ret = fit_get_desc(fit, 0, &desc);
        ^~~~~~~~~~~~
        fit_get_debug
common/image-fit.c:184:9: warning: implicit declaration of function 'fit_get_timestamp'; did you mean 'fit_get_debug'? [-Wimplicit-function-declaration]
   ret = fit_get_timestamp(fit, 0, &timestamp);
         ^~~~~~~~~~~~~~~~~
         fit_get_debug
common/image-fit.c:193:19: warning: implicit declaration of function 'fdt_path_offset' [-Wimplicit-function-declaration]
  images_noffset = fdt_path_offset(fit, FIT_IMAGES_PATH);
                   ^~~~~~~~~~~~~~~
common/image-fit.c:195:48: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'int' [-Wformat=]
   printf("Can't find images parent node '%s' (%s)\n",
                                               ~^
                                               %d
          FIT_IMAGES_PATH, fdt_strerror(images_noffset));
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common/image-fit.c:210:26: warning: format '%s' expects argument of type 'char *', but argument 4 has type 'int' [-Wformat=]
    printf("%s Image %u (%s)\n", p, count++,
                         ~^
                         %d
           fit_get_name(fit, noffset, NULL));
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common/image-fit.c:213:4: warning: implicit declaration of function 'fit_image_print'; did you mean 'fit_image_load'? [-Wimplicit-function-declaration]
    fit_image_print(fit, noffset, p);
    ^~~~~~~~~~~~~~~
    fit_image_load
In file included from include/linux/bug.h:7:0,
                 from include/common.h:26,
                 from common/image-fit.c:18:
common/image-fit.c:220:9: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'int' [-Wformat=]
   debug("Can't get configurations parent node '%s' (%s)\n",
         ^
include/linux/printk.h:37:21: note: in definition of macro 'pr_fmt'
 #define pr_fmt(fmt) fmt
                     ^~~
include/log.h:142:2: note: in expansion of macro 'debug_cond'
  debug_cond(_DEBUG, fmt, ##args)
  ^~~~~~~~~~
common/image-fit.c:220:3: note: in expansion of macro 'debug'
   debug("Can't get configurations parent node '%s' (%s)\n",
   ^~~~~
common/image-fit.c:226:18: warning: implicit declaration of function 'fdt_getprop'; did you mean 'fdt_getprop_u32'? [-Wimplicit-function-declaration]
  uname = (char *)fdt_getprop(fit, noffset, FIT_DEFAULT_PROP, NULL);
                  ^~~~~~~~~~~
                  fdt_getprop_u32
common/image-fit.c:240:34: warning: format '%s' expects argument of type 'char *', but argument 4 has type 'int' [-Wformat=]
    printf("%s Configuration %u (%s)\n", p, count++,
                                 ~^
                                 %d
           fit_get_name(fit, noffset, NULL));
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common/image-fit.c:243:4: warning: implicit declaration of function 'fit_conf_print' [-Wimplicit-function-declaration]
    fit_conf_print(fit, noffset, p);
    ^~~~~~~~~~~~~~
In file included from include/linux/bug.h:7:0,
                 from include/common.h:26,
                 from common/image-fit.c:18:
common/image-fit.c: In function 'fit_image_print_data':
common/image-fit.c:273:8: warning: format '%s' expects argument of type 'char *', but argument 4 has type 'int' [-Wformat=]
  debug("%s  %s node:    '%s'\n", p, type,
        ^
include/linux/printk.h:37:21: note: in definition of macro 'pr_fmt'
 #define pr_fmt(fmt) fmt
                     ^~~
include/log.h:142:2: note: in expansion of macro 'debug_cond'
  debug_cond(_DEBUG, fmt, ##args)
  ^~~~~~~~~~
common/image-fit.c:273:2: note: in expansion of macro 'debug'
  debug("%s  %s node:    '%s'\n", p, type,
  ^~~~~
common/image-fit.c:276:6: warning: implicit declaration of function 'fit_image_hash_get_algo'; did you mean 'fit_image_print_data'? [-Wimplicit-function-declaration]
  if (fit_image_hash_get_algo(fit, noffset, &algo)) {
      ^~~~~~~~~~~~~~~~~~~~~~~
      fit_image_print_data
common/image-fit.c:281:10: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  keyname = fdt_getprop(fit, noffset, "key-name-hint", NULL);
          ^
common/image-fit.c:282:57: warning: comparison between pointer and integer
  required = fdt_getprop(fit, noffset, "required", NULL) != NULL;
                                                         ^~
common/image-fit.c:289:8: warning: implicit declaration of function 'fit_image_hash_get_value'; did you mean 'fit_image_print_data'? [-Wimplicit-function-declaration]
  ret = fit_image_hash_get_value(fit, noffset, &value,
        ^~~~~~~~~~~~~~~~~~~~~~~~
        fit_image_print_data
common/image-fit.c: In function 'fit_image_print_verification_data':
common/image-fit.c:335:7: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  name = fit_get_name(fit, noffset, NULL);
       ^
common/image-fit.c: At top level:
common/image-fit.c:359:6: warning: conflicting types for 'fit_image_print'
 void fit_imag [...]

2018-06-19 15:14 UTC, v-vid commented
Hi @hauke 
I'm not entirely sure what was changed to broke the build, but second commit (https://github.com/openwrt/openwrt/pull/904/commits/4c3c40ad1ae97f9f0182772d490432151dec761e) resolves 2 newly introduced issues:

1. FIT related options are moved from wandboard.h to wanboard_defconfig to resolve declaration issues
2. u-boot.imx is now explicitly defined in Build/Compile section, otherwise all target will fail with "Cannot find u-boot.imx"

If somebody could test this as well and provide feedback, it would be much appreciated.

2018-06-24 11:17 UTC, hauke requested changes
Please merge these two commits into one as these changes are all needed to make this build.
Was this was not even build tested in the beginning, what tests have you done in addition?

2018-06-24 11:17 UTC, hauke commented on package/boot/uboot-imx6/Makefile
> +endef
Instead of manually defining the compile set please just define that you want to have the u-boot.imx image like this:
UBOOT_MAKE_FLAGS += u-boot.imx

2018-06-24 11:17 UTC, hauke commented on package/boot/uboot-imx6/Makefile
> +PKG_HASH:=02922bdf0ee003fe25bfc32749ffdeab
Please use a SHA256 hash this looks too small.

2018-06-26 11:12 UTC, v-vid commented
Hi @hauke,

merged commits, added sha256 hash instead of md5 and replaced "Compile" section with UBOOT_MAKE_FLAGS. Re-tested everything again.
Yes, all targets were tested before submitting PR and @tmn505 also commented above that the build was fine.

2018-07-07 17:37 UTC, hauke commented
Thank you for the patch, it was applied to master.

2018-07-07 17:37 UTC, closed without merging