iptables: remove PROVIDES from legacy implementation
openwrt/openwrt pull request #9648
Opened 2022-04-05 12:20 UTC by feckert

It only makes sense that we only have one PROVIDES definition for the
iptables packages, because a  mix of nft and legacy iptables backend
is not recommended at the same time.

Since the firewall4 is now the default firewall in openwrt, the
iptables-nft/ip6tables-nft backend for iptables must installed,
if a package wants to use the iptables/ip6tables commands.

@champtar @bluewavenet @hnyman 
In order to get further, I have now set up this pullreqest, as suggested in https://github.com/openwrt/openwrt/issues/9540, only set the PROVIDE for the iptables-nft and ip6tables-nft packages

Fixes #9540

2022-04-05 13:03 UTC, bluewavenet commented
@feckert @hnyman @champtar @mans0n 
This also fixes:
https://github.com/openwrt/routing/issues/827

and makes redundant the PR:
https://github.com/openwrt/routing/pull/846

2022-04-05 13:20 UTC, champtar commented
This will prevent everyone from easily switching back to fw3. Wouldn't it be enough to make sure nft variant is the preferred one ?

2022-04-05 13:40 UTC, feckert commented
@bluewavenet 
> But do you actually need iptables-legacy to run fw3? Will it not work with iptables-nft? That is the point of iptables-nft, ie to support older packages that only understand the iptables api.

It is not recommended to mix iptables-nft and iptables-legacy commands.
If you must use old iptables commands you should use iptables-nft/ip6tables-nft for fw4 and iptables-legacy/ip6tables-legacy for fw3.

2022-04-05 14:05 UTC, bluewavenet commented
@feckert 

> It is not recommended to mix iptables-nft and iptables-legacy commands.

But they both have exactly the same commands so you should be able to use either (but not both at the same time).

It is currently possible to install both (incorrectly) and it is very bad to use a mix of iptables-legacy and iptables-nft commands as you end up with two separate "iptables tables" with very unpredictable results...

So my question is: Can you run fw3 with iptables-nft?
I _think_ the answer is yes (once this PR is merged).

2022-04-05 14:20 UTC, champtar commented
With iptables-legacy you had 1 table, doing ACCEPT was final
With nftables you have mutiple tables, doing ACCEPT continue the processing throught the remaining tables.
With fw3/iptables-legacy some software were inserting themselves early say in the INPUT chain, and doing an ACCEPT there, thus bypassing fw3 rules.
If you use fw3 + iptables-nft, previous example breaks.
if iptables-legacy doesn't provide iptables anymore, then people can't switch to fw3 + iptables-legacy without modifying the source and rebuilding themselves, that's a pretty high bar.

We just need to make sure ip(6)tables-nft is the default variant, haven't looked how to do it.
Also having both iptables-legacy and iptables-nft at the same time might allow to use iptables translate (not sure), in any cases I'm not a fan of conflicts.

2022-04-05 14:43 UTC, bluewavenet commented
@champtar 

> I'm not a fan of conflicts.

Indeed, neither am I

> With iptables-legacy you had 1 table, doing ACCEPT was final
> With nftables you have mutiple tables, doing ACCEPT continue the processing throught the remaining tables.
> With fw3/iptables-legacy some software were inserting themselves early say in the INPUT chain, and doing an ACCEPT there, thus bypassing fw3 rules.

Yes. The openNDS package (and its predecessor NoDogSplash) did this and it was made more useful by adding the option to either ACCEPT or RETURN on each openNDS rule. 

>  If you use fw3 + iptables-nft, previous example breaks.

then you can choose to uninstall iptables-nft and install iptables-legacy if it is an issue in a particular edge case.

> We just need to make sure ip(6)tables-nft is the default variant, haven't looked how to do it.

This is the intended purpose of this PR...

2022-04-05 18:27 UTC, cotequeiroz commented
If we want to keep the `PROVIDES` then I propose to get rid of the `IPTABLES_NFTABLES` option.  That dependency will not coexist the multiple `PROVIDES`.  The symbol is used to disable all nft packages with one click, but one can disable them individually, if desired.  It has no effect on the final binaries.  It will increase build time when you don't need the nft packages, but that usage shall be considered marginal anyway.

I still have to try this to be 100% certain, but I think we can rename the `*tables-nft` packages to just `*tables`, and have the `*tables-legacy` packages `PROVIDE` `*tables`.   Since [5936c4f libopkg: pkg_hash: prefer original packages to satisfy dependencies](https://git.openwrt.org/?p=project/opkg-lede.git;a=commitdiff;h=5936c4f9660248284e8a9b040ea3153d3ea888de), `opkg` installs the original package before searching for providers, so a dependency on just `iptables` will install the nft package, but do nothing if the legacy version is already installed.

2022-04-05 18:55 UTC, champtar commented
@cotequeiroz looking at the commit you linked, renaming ip(6)tables-nft to ip(6)tables seems to be the best course of action
@feckert do you want to update this PR ?
- rename ip(6)tables-nft to ip(6)tables
- have ip(6)tables PROVIDES ip(6)tables-nft
- bump PKG_RELEASE

2022-04-05 19:07 UTC, cotequeiroz commented
We should not forget about `arptables`, `ebtables`, and `nftables`.  Their alternatives have their own packages, but the issue is the same.

How about getting rid of `IPTABLES_NFTABLES`?

2022-04-05 19:21 UTC, bluewavenet commented
@champtar @feckert @cotequeiroz 
Yes, make sure iptables-nft and ip6tables-nft are the defaults.
ie

- remove PROVIDES from legacy implementation as in original PR commit
- rename ip6tables-nft to ip6tables
- have ip6tables PROVIDES ip6tables-nft
- bump PKG_RELEASE

2022-04-05 19:32 UTC, champtar commented
> @champtar @feckert @cotequeiroz Yes, make sure iptables-nft and ip6tables-nft are the defaults. ie
> 
>     * remove PROVIDES from legacy implementation as in original PR commit

No, already explained why in a previous message

2022-04-05 19:44 UTC, bluewavenet commented
@champtar 

>     * remove PROVIDES from legacy implementation as in original PR commit
> No, already explained why in a previous message

If it is not removed then iptables-legacy will still be the default, as explained by @feckert in the first comment.
ie

> Since the firewall4 is now the default firewall in openwrt, the
> iptables-nft/ip6tables-nft backend for iptables must installed,
> if a package wants to use the iptables/ip6tables commands.

2022-04-05 19:52 UTC, champtar commented
Have a look at @cotequeiroz message and the commit he linked

2022-04-05 20:04 UTC, cotequeiroz commented
If you don't handle `IPTABLES_NFTABLES`, you end up with a ton of recursive dependencies, such as:
```
tmp/.config-package.in:1061:error: recursive dependency detected!
tmp/.config-package.in:1061:   	symbol PACKAGE_qos-scripts depends on PACKAGE_qos-scripts
```
At least it is easy to see their cause:
```
	config PACKAGE_qos-scripts
		select PACKAGE_iptables if PACKAGE_iptables-legacy<PACKAGE_qos-scripts
		depends on !(PACKAGE_iptables-legacy<PACKAGE_qos-scripts) || IPTABLES_NFTABLES
		
```
This happens because there's a conditional dependency on `IPTABLES_NFTABLES` if `iptables-nft` is to be selected.  The logic is that we should select iptables-nft if iptables-legacy is not selected.  Then if we are to select iptables-nft, we must add its dependencies to our list.  The selection condition includes the value of the symbol being defined, generating a recursive dependency.

It is a bug or limitation of `scripts/package-metadata.pl`.  The proper check for that condition should be done at the package selection, and there should be a line selecting the alternative should `IPTABLES_NFTABLES` not be `y`:
```
	select PACKAGE_iptables if (PACKAGE_iptables-legacy<PACKAGE_qos-scripts) && IPTABLES_NFTABLES
	select PACKAGE_iptables-legacy if !IPTABLES_NFTABLES
```
Notice that the selection of one package or the other depend on the value of `PACKAGE_qos-scripts`.

`IPV6` is thrown into a senseless depends line for a reason that I don't fully understand.
```
	depends on !(PACKAGE_iptables-legacy<PACKAGE_qos-scripts && IPV6) || IPV6
```
But here, the condition is always true, because if IPV6 is false, then the first part is always true; if not, the || condition will result in true as well.

2022-04-05 20:08 UTC, bluewavenet commented
@champtar 
Do you mean:
> Since [5936c4f libopkg: pkg_hash: prefer original packages to satisfy dependencies](https://git.openwrt.org/?p=project/opkg-lede.git;a=commitdiff;h=5936c4f9660248284e8a9b040ea3153d3ea888de), opkg installs the original package before searching for providers, so a dependency on just iptables will install the nft package, but do nothing if the legacy version is already installed.

On a device flashed with current snapshot, as expected, iptables is not installed by default.
If I do `opkg install iptables` I get iptables-legacy.
So the above quote by @cotequeiroz  is unfortunately not what actually happens

2022-04-05 20:11 UTC, cotequeiroz commented
Right now, there's no package named `iptables`.  It ends up in a "provider" list composed of `iptables-nft` and `iptables-legacy`.  opkg will pick one of them, which is not the one we want.  If we rename the package, then `iptables` will match an actual package, and the provider list won't be searched.

2022-04-05 20:11 UTC, champtar commented
Because we haven't renamed iptables-nft to iptables yet ...

2022-04-05 20:15 UTC, bluewavenet commented
@cotequeiroz 

> It is a bug or limitation of scripts/package-metadata.pl.

Now we are getting to the core of the problem.....

2022-04-05 20:20 UTC, bluewavenet commented
> Because we haven't renamed iptables-nft to iptables yet ...

That would fix it nicely

2022-04-06 13:14 UTC, feckert commented
@champtar @bluewavenet @cotequeiroz I have update the pullrequest with the suggested changes.

2022-04-06 13:27 UTC, champtar commented
You forgot to bump PKG_RELEASE, else LGTM

2022-04-06 13:34 UTC, bluewavenet commented
Looks good.
@cotequeiroz are you able to build and test?

2022-04-06 14:09 UTC, cotequeiroz requested changes
The `Package/*tables-nft/install` definitions need to be renamed as well.  Otherwise, LGTM.

2022-04-06 14:45 UTC, feckert commented
@cotequeiroz Damn, I overlooked that -> done
@champtar bumped PKG_RELEASE as requested

2022-04-07 13:15 UTC, cotequeiroz approved these changes
Reviewed-by: Eneas U de Queiroz <cotequeiroz@gmail.com>

2022-04-08 06:21 UTC, feckert commented
@cotequeiroz would be nice if we get this into openwrt-22.03 before rc0

2022-04-08 12:15 UTC, cotequeiroz commented
I don't have write access, so I can only agree. 😉

2022-04-08 12:32 UTC, cotequeiroz commented
@aparcar, since you have conducted the migration to fw4, would you please take a look at this?

2022-04-13 08:42 UTC, jow- commented
I don't think the renaming is required, if at all then it only adds confusion. The removal of  `IPTABLES_NFTABLES` makes sense. If the objective of the rename was to prefer `*-nft` oder `*-legacy` then use `DEFAULT_VARIANT:=1` on the `*-nft` package definitions.

2022-04-13 08:54 UTC, bluewavenet commented
@jow- 
Whatever is the best way, we need the default to be iptables-nft and not iptables-legacy, along with preventing both being installed together.

2022-04-14 07:02 UTC, feckert commented
> I don't think the renaming is required, if at all then it only adds confusion. The removal of `IPTABLES_NFTABLES` makes sense. If the objective of the rename was to prefer `*-nft` over `*-legacy` then use `DEFAULT_VARIANT:=1` on the `*-nft` package definitions.

@jow- I have now tried it out as you said. In my system, the mwan3 is the only one that has a dependency on [iptables](https://github.com/openwrt/packages/blob/master/net/mwan3/Makefile#L27) and [ip6tables](https://github.com/openwrt/packages/blob/master/net/mwan3/Makefile#L28).
If I add this change and regenerate my .config, then always iptables-legacy and ip6tables-legacy are enabled and not iptables-nft or ip6tables-nft!

Is it possible that the DEFAULT_VARIANT only works if I also define a build VARIANT?
https://github.com/openwrt/openwrt/blob/ec6293febc244d187e71a6e54f44920be679cde4/include/package-dumpinfo.mk#L27-L30

2022-04-25 20:24 UTC, pprindeville commented
Blocking PR #18262 on merge...

2022-05-24 13:36 UTC, feckert commented
@cotequeiroz @jow- frendly ping!
Any progress on this. It is still a problem vor me.

2022-05-26 15:00 UTC, cotequeiroz commented
There's not much else I can do here.  I can run-test this again--when able--and report the results.

2022-05-26 17:42 UTC, cotequeiroz commented
I've tested this in its current state.  If I install a dependent package, it pulls up `iptables-nft`.  However, if I try to install `iptables` directly, `iptables-legacy` is chosen: 😞

```
# opkg install sqm-scripts
Installing sqm-scripts (1.5.1-4) to root...
Downloading http://192.168.1.1/packages/aarch64_cortex-a53/packages/sqm-scripts_1.5.1-4_all.ipk
Installing iptables-nft (1.8.7-7) to root...
Downloading http://192.168.1.1/targets/mediatek/mt7622/packages/iptables-nft_1.8.7-7_aarch64_cortex-a53.ipk
Installing iptables-mod-ipopt (1.8.7-7) to root...
Downloading http://192.168.1.1/targets/mediatek/mt7622/packages/iptables-mod-ipopt_1.8.7-7_aarch64_cortex-a53.ipk
Configuring iptables-nft.
Configuring iptables-mod-ipopt.
Configuring sqm-scripts.
```

```
# opkg install iptables
Installing iptables-legacy (1.8.7-7) to root...
Downloading http://192.168.1.1/targets/mediatek/mt7622/packages/iptables-legacy_1.8.7-7_aarch64_cortex-a53.ipk
Configuring iptables-legacy.
```

2022-05-27 06:25 UTC, feckert commented
@cotequeiroz The fact that iptable-nft is installed with an iptables [dependency](https://github.com/openwrt/packages/blob/68fb9c62a5f4421650aabb33c53466709afc46d6/net/sqm-scripts/Makefile#L27) is good so far.
That is what I want to achieve.
Unfortunately, I don't understand why it installs iptables-legacy when `opkg install iptables` is executed!

Actually, this should install iptables-nft because I defined `DEFAULT_VARIANT:=1` in my commit!
https://github.com/openwrt/openwrt/blob/0a48d333246a146445ee1a01157bca61814cca11/package/network/utils/iptables/Makefile#L138
https://github.com/openwrt/openwrt/blob/0a48d333246a146445ee1a01157bca61814cca11/package/network/utils/iptables/Makefile#L506

I need to check this again as I have only tried the dependency way.

Perhaps someone else from the core team can explain to us why this is so?
@adschm @nbd168

2022-05-27 11:08 UTC, hnyman commented
> I don't understand why it installs iptables-legacy when opkg install iptables is executed!
>
> Actually, this should install iptables-nft because I defined DEFAULT_VARIANT:=1 in my commit!

I think that when the Makefile defines so many packages, it is unclear which packages the DEFAULT_VARIANT concerns. 

There is nothing to tie iptables-nft and iptables-legacy as being alternative variants, similarly regarding ip6tables-nft and ip6tables-legacy. I think that all packages defined in the Makefile are handled equally, and the last one with DEFAULT_VARIANT wins. That one is ip6tables-nft.

There is nothing to tie iptables-nft and iptables-legacy regarding being variants of each other, and neither is DEFAULT_VARIANT (as ip6tables-nft is). As neither is DEFAULT_VARIANT, the first one found providing is selected and can be iptasbles-legacy.

(Note: this is just a guess, I haven't yet checked the .packagedata in tmp/. )

2022-05-27 14:44 UTC, cotequeiroz commented
Defining `DEFAULT_VARIANT:=1` will affect selection during `make menuconfig`, apparently.  The package information passed to `opkg` does not contain that information:
```
# opkg update
# zcat /tmp/opkg-lists/openwrt_core | grep -EA13 'Package: iptables-(nft|legacy)$'
Package: iptables-legacy
Version: 1.8.7-7
Depends: libc, xtables-legacy
Provides: iptables
Alternatives: 200:/usr/sbin/iptables:/usr/sbin/xtables-legacy-multi, 200:/usr/sbin/iptables-restore:/usr/sbin/xtables-legacy-multi, 200:/usr/sbin/iptables-save:/usr/sbin/xtables-legacy-multi
License: GPL-2.0
Section: net
CPE-ID: cpe:/a:netfilter_core_team:iptables
Architecture: aarch64_cortex-a53
Installed-Size: 243
Filename: iptables-legacy_1.8.7-7_aarch64_cortex-a53.ipk
Size: 1206
SHA256sum: 357584a46978699ab2017cb60719a076227d386a88e48e848361377be1d1a148
Description:  IP firewall administration tool.
--
Package: iptables-nft
Version: 1.8.7-7
Depends: libc, kmod-ipt-core, xtables-nft
Provides: iptables
Alternatives: 300:/usr/sbin/iptables:/usr/sbin/xtables-nft-multi, 300:/usr/sbin/iptables-restore:/usr/sbin/xtables-nft-multi, 300:/usr/sbin/iptables-save:/usr/sbin/xtables-nft-multi
License: GPL-2.0
Section: net
CPE-ID: cpe:/a:netfilter_core_team:iptables
Architecture: aarch64_cortex-a53
Installed-Size: 244
Filename: iptables-nft_1.8.7-7_aarch64_cortex-a53.ipk
Size: 1065
SHA256sum: 88500e71537d6fbee41cba40e3a6303c8574dad900689f802a129b71234784f4
Description:  Extra iptables nftables nft binaries.
```
I don't have the time to look into this much deeper.  Apparently, `opkg` has to decide which package to install based on the contents of files under `/tmp/opkg-lists` (it does not download every package providing `iptables` to peek at their metadata).  Unless we change the way this works--at least making the behavior of installing dependent packages match the command line action in a predictable way--we may need to rely on the name preference I mentioned above.

2022-05-27 14:55 UTC, cotequeiroz commented
> I think that when the Makefile defines so many packages, it is unclear which packages the DEFAULT_VARIANT concerns.

`DEFAULT_VARIANT` does make its way to `$(TOPDIR)/tmp/.packagedata`:
```
$ sed -n '/Package: iptables-\(nft\|legacy\)$/,/Description:/p' tmp/.packageinfo
Package: iptables-legacy
Submenu: Firewall
Version: 1.8.7-7
Depends: +libc +USE_GLIBC:librt +USE_GLIBC:libpthread +xtables-legacy
Conflicts:
Menu-Depends:
Provides: iptables
Section: net
Category: Network
Title: IP firewall administration tool
Maintainer:
Source: iptables-1.8.7.tar.bz2
License: GPL-2.0
Type: ipkg
Description: IP firewall administration tool.
Package: iptables-nft
Submenu: Firewall
Version: 1.8.7-7
Depends: +libc +USE_GLIBC:librt +USE_GLIBC:libpthread +kmod-ipt-core +xtables-nft
Conflicts:
Menu-Depends:
Provides: iptables
Build-Variant: nft
Default-Variant: nft
Section: net
Category: Network
Title: IP firewall administration tool nft
Maintainer:
Source: iptables-1.8.7.tar.bz2
License: GPL-2.0
Type: ipkg
Description: Extra iptables nftables nft binaries.
```
If I add a variant to the legacy version, it will just add a `Build-Variant:` line below `Provides`, and does not change the `opkg` metadata.

2022-06-26 05:38 UTC, champtar commented
Another proposal to fix this issue #10124

2022-06-29 06:59 UTC, feckert commented
Superseeded by https://github.com/openwrt/openwrt/pull/10124

2022-06-29 06:59 UTC, closed without merging