ar71xx: add support for OCEDO Raccoon
openwrt/openwrt pull request #994
Opened 2018-05-29 23:51 UTC by blocktrron

This commit adds support for the OCEDO Raccoon

SOC:	Atheros AR9344
RAM:    128MB
FLASH:  16MiB
WLAN1:  AR9344 2.4 GHz 802.11bgn 2x2
WLAN2:  AR9382 5 GHz 802.11an 2x2
INPUT:  RESET button
LED:    Power, LAN, WiFi 2.4, WiFi 5
Serial: Header Next to Black metal shield
        Pinout is 3.3V - GND - TX - RX (Arrow Pad is 3.3V)
        The Serial setting is 115200-8-N-1.

	NOTE: The U-Boot won't boot with the serial attached.
	Boot the device without serial attached and attach it
	after 3 seconds.

Tested and working:
 - Ethernet
 - 2.4 GHz WiFi
 - 5 GHz WiFi
 - TFTP boot from ramdisk image
 - Installation via ramdisk image
 - OpenWRT sysupgrade
 - Buttons
 - LEDs

Installation seems to be possible only through booting an OpenWRT
ramdisk image.

Hold down the reset button while powering on the device. It will load a
ramdisk image named 'raccoon-uImage-initramfs-lzma.bin' from 192.168.100.8.

Wait for the ramdisk image to boot. OpenWRT can be written to the flash
via sysupgrade or mtd.

Due to the flip-flop bootloader which we not (yet) support, you need to
set the partition the bootloader is selecting. It is possible from the
initramfs image with

 > fw_setenv bootcmd run bootcmd_1

Afterwards you can reboot the device.

Signed-off-by: David Bauer <mail@david-bauer.net>

2018-05-30 22:17 UTC, herrbett commented
We testet the PR on a few of our Devices.
It works flawlessly.
Thank you for your Work. 👍

2018-06-07 07:26 UTC, blogic commented on target/linux/ar71xx/files/arch/mips/ath79/machtypes.h
> +	ATH79_MACH_RACCOON,			/* Ocedo Raccoon */
alphabetical ordering

2018-06-07 07:27 UTC, blogic commented on target/linux/ar71xx/generic/config-default
> +CONFIG_ATH79_MACH_RACCOON=y
...

2018-07-05 23:07 UTC, mkresin requested changes

2018-07-05 23:07 UTC, mkresin commented on target/linux/ar71xx/image/generic-senao.mk
> +define Device/raccoon
Please have a look at my remarks to https://github.com/openwrt/openwrt/pull/1016. The very same applies here.

2018-07-06 14:45 UTC, blocktrron commented
@mkresin adjusted to match your requests in #1016

2018-07-06 14:49 UTC, mkresin approved these changes

2018-07-07 19:43 UTC, mkresin commented
I merged ath79 patch for the same board instead. I see more no than a little chance that this PR will be ever merged. Hence I'll close the PR.

If you disagree with the my decision, please start a discussion on the OpenWrt development mailinglist.

2018-07-07 19:43 UTC, closed without merging